<!doctype html>
<html class="fixed">
    <head>
        <!-- Basic -->
        <meta charset="UTF-8">
        <meta name="keywords" content="Website Admin" />
        <meta name="description" content="Porto Admin - Responsive HTML5 Template">
        <meta name="author" content="okler.net">

        <!-- Mobile Metas -->
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

        <!-- Web Fonts  -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

        <!-- Vendor CSS -->
        <link rel="stylesheet" href="<?php echo $pfurl; ?>adminfiles/assets/vendor/bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="<?php echo $pfurl; ?>adminfiles/assets/vendor/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="<?php echo $pfurl; ?>adminfiles/assets/vendor/magnific-popup/magnific-popup.css" />
        <link rel="stylesheet" href="<?php echo $pfurl; ?>adminfiles/assets/vendor/bootstrap-datepicker/css/datepicker3.css" />

        <!-- Theme CSS -->
        <link rel="stylesheet" href="<?php echo $pfurl; ?>adminfiles/assets/stylesheets/theme.css" />

        <link rel="stylesheet" href="<?php echo $pfurl; ?>adminfiles/assets/stylesheets/mainadmin.css" />

        <!-- Skin CSS -->
        <link rel="stylesheet" href="<?php echo $pfurl; ?>adminfiles/assets/stylesheets/skins/default.css" />

        <!-- Theme Custom CSS -->
        <link rel="stylesheet" href="<?php echo $pfurl; ?>adminfiles/assets/stylesheets/theme-custom.css">


        <!-- Vendor -->
        <script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/jquery/jquery.js"></script>


        <title>
            Website Admin
        </title>
    </head>
    <body>
        <section class="body">

            <!-- start: header -->
            <?php echo $this->partial("layouts/header"); ?>
            <!-- end: header -->

            <div class="inner-wrapper">
                <!-- start: sidebar -->
                <?php echo $this->partial("layouts/sidebar"); ?>
                <!-- end: sidebar -->

                <section role="main" class="content-body">
                    <header class="page-header">
                        <h2><?php echo $formTitle; ?></h2>

                        <!--                        <div class="right-wrapper pull-right">
                                                    <ol class="breadcrumbs">
                                                        <li>
                                                            <a href="index.html">
                                                                <i class="fa fa-home"></i>
                                                            </a>
                                                        </li>
                                                        <li><span>Forms</span></li>
                                                        <li><span>Layouts</span></li>
                                                    </ol>
                                                    <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>
                                                </div>-->
                    </header>

                    <!-- start: page -->
                    <?php echo $this->getContent() ?>
                    <!-- end: page -->
                </section>
            </div>

            <aside id="sidebar-right" class="sidebar-right">
                <div class="nano">
                    <div class="nano-content">
                        <a href="#" class="mobile-close visible-xs">
                            Collapse <i class="fa fa-chevron-right"></i>
                        </a>

                        <div class="sidebar-right-wrapper">

                            <div class="sidebar-widget widget-calendar">
                                <h6>Upcoming Tasks</h6>
                                <div data-plugin-datepicker data-plugin-skin="dark" ></div>

                                <ul>
                                    <li>
                                        <time datetime="2014-04-19T00:00+00:00">04/19/2014</time>
                                        <span>Company Meeting</span>
                                    </li>
                                </ul>
                            </div>

                            <div class="sidebar-widget widget-friends">
                                <h6>Friends</h6>
                                <ul>
                                    <li class="status-online">
                                        <figure class="profile-picture">
                                            <img src="<?php echo $pfurl; ?>adminfiles/assets/images/!sample-user.jpg" alt="Joseph Doe" class="img-circle">
                                        </figure>
                                        <div class="profile-info">
                                            <span class="name">Joseph Doe Junior</span>
                                            <span class="title">Hey, how are you?</span>
                                        </div>
                                    </li>
                                    <li class="status-online">
                                        <figure class="profile-picture">
                                            <img src="<?php echo $pfurl; ?>adminfiles/assets/images/!sample-user.jpg" alt="Joseph Doe" class="img-circle">
                                        </figure>
                                        <div class="profile-info">
                                            <span class="name">Joseph Doe Junior</span>
                                            <span class="title">Hey, how are you?</span>
                                        </div>
                                    </li>
                                    <li class="status-offline">
                                        <figure class="profile-picture">
                                            <img src="<?php echo $pfurl; ?>adminfiles/assets/images/!sample-user.jpg" alt="Joseph Doe" class="img-circle">
                                        </figure>
                                        <div class="profile-info">
                                            <span class="name">Joseph Doe Junior</span>
                                            <span class="title">Hey, how are you?</span>
                                        </div>
                                    </li>
                                    <li class="status-offline">
                                        <figure class="profile-picture">
                                            <img src="<?php echo $pfurl; ?>adminfiles/assets/images/!sample-user.jpg" alt="Joseph Doe" class="img-circle">
                                        </figure>
                                        <div class="profile-info">
                                            <span class="name">Joseph Doe Junior</span>
                                            <span class="title">Hey, how are you?</span>
                                        </div>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
            </aside>
        </section>
    </body>

    <!-- Head Libs -->
    <script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/modernizr/modernizr.js"></script>



    <script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
    <script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/nanoscroller/nanoscroller.js"></script>
    <script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/magnific-popup/magnific-popup.js"></script>
    <script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/jquery-placeholder/jquery.placeholder.js"></script>

    <!-- Theme Base, Components and Settings -->
    <script src="<?php echo $pfurl; ?>adminfiles/assets/javascripts/theme.js"></script>

    <!-- Theme Custom -->
    <script src="<?php echo $pfurl; ?>adminfiles/assets/javascripts/theme.custom.js"></script>

    <!-- Theme Initialization Files -->
    <script src="<?php echo $pfurl; ?>adminfiles/assets/javascripts/theme.init.js"></script>

</html>