<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel panel-default'>
                <header class='panel-heading'>
                    <h2 class='panel-title'>افزودن سازمان</h2>
                </header>
                <div class='panel-body'>
                    <div class="row">
                        <div class="col-sm-6">
                            <!--  ADD Name !-->
                            <?php $form->renderDecorated('name'); ?> 

                            <!--  ADD Address !-->
                            <?php $form->renderDecorated('address'); ?> 
                            
                            <!--  ADD Phone Number !-->
                            <?php $form->renderDecorated('phonenumber'); ?> 
                        </div>
                        <div class="col-sm-6">
                            
                            <!--  ADD State ID !-->
                            <?php $form->renderDecorated('stateid'); ?> 
                            
                            <!--  ADD City ID !-->
                            <?php $form->renderDecorated('cityid'); ?> 

                            <!--  ADD Description !-->
                            <?php $form->renderDecorated('description'); ?> 
                        </div>
                    </div

                    <!-- Submit Button !-->
                    <br/>
                    <div class="row">
                        <div class="col-sm-4 col-sm-offset-4">
                            <?php $form->renderDecorated('submit'); ?>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</form>
<script>
    $(function() {
        var state = {};
        <?php foreach($state as $st): ?>
        state["<?=$st->id?>"] = {};
        <?php endforeach; ?>
        <?php foreach($city as $ct): ?>
        state["<?=$ct->stateid?>"]["<?=$ct->id?>"] = '<?=$ct->name?>';        
        <?php endforeach; ?>

        $("#stateid").change(function() {
            $("#cityid").find('option').remove().end();
            if (state[$(this).val()]) {
                $.each(state[$(this).val()], function(id, name) {
                    $("#cityid").append('<option value="' + id + '">' + name + '</option>');
                });
            }
        });
    });
</script>

