<?php use Simpledom\Core\Classes\Helper;?>
<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<div class='row'>
    <div class='col-md-12'>
        <?php $form->renderDecorated('sentchart'); ?>
        <hr/>

        <div class="row">
            <!-- Total Users !-->
            <div class="col-md-12 col-lg-6 col-xl-6">
                <section class="panel-featured-quartenary">
                    <div class="panel-body panel-user">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-quartenary">
                                    <i class="fa fa-user"></i>
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    <h4 class="title">تعداد کاربران</h4>
                                    <div class="info">
                                        <strong class="amount"><?php echo $totalUsers; ?></strong> <span class="summery-info-title">کاربر</span>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                    <a class="text-muted text-uppercase" href="/admin/user/list">(نمایش همه)</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>

            <!-- Total Sales !-->
            <div class="col-md-12 col-lg-6 col-xl-6">
                <section class="panel-featured-primary">
                    <div class="panel-body panel-credit">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-success">
                                    <i class="fa fa-dollar"></i>
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    <h4 class="title">پیامکهای باقی مانده</h4>
                                    <div class="info">
                                        <strong class="amount"><?php echo $currentCredit; ?></strong> <span class="summery-info-title">پیام</span>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                    <a class="text-muted text-uppercase">(افزایش اعتبار)</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>


            <!-- Remaining SMS !-->
            <div class="col-md-12 col-lg-6 col-xl-6">
                <section class="panel-featured-primary">
                    <div class="panel-body panel-message">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-info">
                                    <i class="fa fa-envelope"></i>
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    <h4 class="title">تعداد پیامکها</h4>
                                    <div class="info">
                                        <strong class="amount"><?php echo $totalMessages; ?></strong> <span class="summery-info-title">پیامک</span>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
            <!-- Remaining SMS !-->
            <div class="col-md-12 col-lg-6 col-xl-6">
                <section class="panel-featured-primary">
                    <div class="panel-body panel-message">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-info">
                                    <i class="fa fa-envelope"></i>
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    <h4 class="title">تعداد پیامهکای این ماه</h4>
                                    <div class="info">
                                        <strong class="amount"><?php echo $thisMonthSentMessage; ?></strong> <span class="summery-info-title">پیامک</span>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>

        <hr/>

        <?php //echo $list->table; ?>
        <table class="table table-bordered table-striped table-center">
            <tr>
                <th>
                    شناسه
                </th>
                <th>
                    پیام
                </th>
                <th>
                    تاریخ
                </th>
                <th>
                    شماره ارسال کننده
                </th>
                <th>
                    از شماره
                </th>
                <th>
                    به شماره
                </th>
                <th>
                    هزینه
                </th>
            </tr>

            <?php foreach ($list->items as $item) : ?>
                <tr>
                    <td>
                        <?= $item->id ?>
                    </td>
                    <td style="text-align: right">
                        <?= Helper::wordLimiter($item->message, 10) ?>
                    </td>
                    <td>
                        <?= $item->getDate() ?>
                    </td>
                    <td>
                        <?= $item->sendernumber ?>
                    </td>
                    <td>
                        <?= $item->fromnumber ?>
                    </td>
                    <td>
                        <?= $item->tonumber ?>
                    </td>
                    <td>
                        <?= $item->cost ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>


    </div>
</div>