<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<blockquote>
    <a class="btn btn-sm btn-primary" href="<?php echo $this->url->get("organ/$organId/posts/add"); ?>">افزودن سمت</a>
</blockquote>
<div class='row'>
    <div class='col-md-12'>
        <?php
        echo $list->header;
        echo $list->table;
        echo $list->footer;
        ?>
    </div>
</div>