<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>



            <!--  ADD Name !-->
            <?php $form->renderDecorated('name'); ?> 

            <!--  ADD Address !-->
            <?php $form->renderDecorated('address'); ?> 

            <!--  ADD State ID !-->
            <?php $form->renderDecorated('stateid'); ?> 

            <!--  ADD City ID !-->
            <?php $form->renderDecorated('cityid'); ?> 

            <!--  ADD Description !-->
            <?php $form->renderDecorated('description'); ?> 

            <!--  ADD Phone Number !-->
            <?php $form->renderDecorated('phonenumber'); ?> 

            <!--  ADD Interface URL !-->
            <?php $form->renderDecorated('interfaceurl'); ?> 

            <!--  ADD Use Interface !-->
            <?php $form->renderDecorated('useinterface'); ?> 


            <!-- Submit Button !-->
            <br/>
            <?php $form->renderDecorated('submit'); ?>

        </div>
    </div>
</form>


