<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-sm-6'>
            <!--  ADD Name !-->
            <?php $form->renderDecorated('name'); ?> 

            <!--  ADD Address !-->
            <?php $form->renderDecorated('address'); ?> 

            <!--  ADD Phone Number !-->
            <?php $form->renderDecorated('phonenumber'); ?> 
            
            <!--  ADD Description !-->
            <?php $form->renderDecorated('description'); ?> 
        </div>
        <div class='col-sm-6'>
            <!--  ADD State ID !-->
            <?php $form->renderDecorated('stateid'); ?> 

            <!--  ADD City ID !-->
            <?php $form->renderDecorated('cityid'); ?> 
            
            <!--  ADD Use Interface !-->
            <?php $form->renderDecorated('useinterface'); ?> 

            <!--  ADD Interface URL !-->
            <div id="interface_url">
                <?php $form->renderDecorated('interfaceurl'); ?> 
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-4 col-sm-offset-4">
            <!-- Submit Button !-->
            <?php $form->renderDecorated('submit'); ?>
        </div>
    </div>
</form>


<script>
    $(function() {
        if (!$("#useinterface").is(":checked")) {
            $("#interface_url").hide();
        }
      
        $('#useinterface').on('switchChange.bootstrapSwitch', function(event, state) {
            if ($("#useinterface").is(":checked")) {
                $("#interface_url").show();
            } else {
                $("#interface_url").hide();
            }
        });
    });
</script>
<script>
    $(function() {
        var state = {};
        <?php foreach($state as $st): ?>
        state["<?=$st->id?>"] = {};
        <?php endforeach; ?>
        <?php foreach($city as $ct): ?>
        state["<?=$ct->stateid?>"]["<?=$ct->id?>"] = '<?=$ct->name?>';        
        <?php endforeach; ?>

        $("#stateid").change(function() {
            $("#cityid").find('option').remove().end();
            if (state[$(this).val()]) {
                $.each(state[$(this).val()], function(id, name) {
                    $("#cityid").append('<option value="' + id + '">' + name + '</option>');
                });
            }
        });
    });
</script>