<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel panel-primary'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>View Organ</h2>
                    <p class='panel-subtitle'Use this form to edit your Organ</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD ID !-->
                    <?php $form->renderInfo('id'); ?> 

                    <!--  ADD Name !-->
                    <?php $form->renderInfo('name'); ?> 

                    <!--  ADD By User !-->
                    <?php $form->renderInfo('byuserid'); ?> 

                    <!--  ADD Address !-->
                    <?php $form->renderInfo('address'); ?> 

                    <!--  ADD State ID !-->
                    <?php $form->renderInfo('stateid'); ?> 

                    <!--  ADD City ID !-->
                    <?php $form->renderInfo('cityid'); ?> 

                    <!--  ADD Description !-->
                    <?php $form->renderInfo('description'); ?> 

                    <!--  ADD Phone Number !-->
                    <?php $form->renderInfo('phonenumber'); ?> 

                    <!--  ADD SMS Credit !-->
                    <?php $form->renderInfo('smscredit'); ?> 

                    <!--  ADD Interface URL !-->
                    <?php $form->renderInfo('interfaceurl'); ?> 

                    <!--  ADD Use Interface !-->
                    <?php $form->renderInfo('userinterface'); ?> 

                    <!--  ADD Status !-->
                    <?php $form->renderInfo('status'); ?> 

                    <!--  ADD Disable Message !-->
                    <?php $form->renderInfo('disablemessage'); ?> 

                    <!--  ADD SMS NUMBER !-->
                    <?php $form->renderInfo('smsnumberid'); ?> 

                    <!--  ADD Date !-->
                    <?php $form->renderInfo('date'); ?> 


                </div>
            </section>
        </div>
    </div>
</form>


