<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'  enctype="multipart/form-data">
    <div class='row'>
        <div class='col-md-6 col-md-push-3 page-create-bongah'>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">عضویت بنگاه داران</h3>
                </div>
                <div class="panel-body">
                    <p>لطفا تمامی اطلاعات خواسته شده در فرم زیر را وارد نمایید</p>


                    <!-- Moshakhaste Moshaver Amlak !-->
                    <h3 class="melk-section-header">مشخصات مشاور املاک</h3>
                    <?php $form->renderDecorated('title'); ?> 
                    <div class='row'>
                        <div class='col-md-6'>
                            <?php $form->renderDecorated('fname'); ?>
                        </div>
                        <div class='col-md-6'>
                            <?php $form->renderDecorated('lname'); ?> 
                        </div>
                    </div>

                    <!--Moghiyate !-->
                    <h3 class="melk-section-header">موقعیت</h3>
                    <div class='row'>
                        <div class='col-md-6'>
                            <!--  ADD State ID !-->
                            <?php $form->renderDecorated('stateid'); ?> 
                        </div>
                        <div class='col-md-6'>
                            <!--  ADD City ID !-->
                            <?php $form->renderDecorated('cityid'); ?> 
                        </div>

                    </div>
                    <div class='row'>
                        <div class='col-md-12'>
                            <!--  ADD Address !-->
                            <?php $form->renderDecorated('address'); ?> 
                        </div>
                        <div class='col-md-12'>
                            <?php $form->renderDecorated('map'); ?> 
                        </div>
                    </div>

                    <!-- Location Can support !-->
                    <h3 class="melk-section-header">مناطق قابل پوشش</h3>
                    <div class='row'>
                        <div class='col-md-12'>
                            <?php $form->renderDecorated('locationscansupport'); ?> 
                        </div>
                    </div>

                    <!-- Contact Info !-->
                    <h3 class="melk-section-header">اطلاعات تماس</h3>
                    <div class='row'>
                        <div class='col-md-12'>
                            <?php if (!isset($user)) : ?>
                                <div class='row'>
                                    <div class='col-md-6'>
                                        <?php $form->renderDecorated('email'); ?> 
                                    </div>
                                    <div class='col-md-6'>
                                        <?php $form->renderDecorated('password'); ?> 
                                    </div>
                                </div>
                            <?php endif; ?>

                            <!--  ADD Private Phone !-->
                            <?php $form->renderDecorated('phone'); ?> 

                            <!--  ADD Private Mobile !-->
                            <?php $form->renderDecorated('mobile'); ?> 
                        </div>
                    </div>

                    <!-- Images !-->
                    <h3 class="melk-section-header">تصاویر آژانس شما</h3>
                    <div class='row'>
                        <div class='col-md-6'>
                            <?php $form->renderDecorated('img1'); ?> 
                            <?php $form->renderDecorated('img3'); ?> 
                            <?php $form->renderDecorated('img5'); ?> 
                        </div>
                        <div class='col-md-6'>
                            <?php $form->renderDecorated('img2'); ?> 
                            <?php $form->renderDecorated('img4'); ?> 
                            <?php $form->renderDecorated('img6'); ?> 
                        </div>
                    </div>

                    <!-- Submit !-->
                    <hr/>
                    <div class='row'>
                        <div class='col-md-12 center'>
                            <h3>برای ارسال مشخصات بر روی کلید زیر کلیک نمایید</h3>
                            <!-- Submit Button !-->
                            <br/>
                            <?php $form->renderDecorated('submit'); ?> 
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>

</form>
<script>


    // hide all steps at start
    $(".melk-step-panel").hide();


    /**
     * this function will go to the requestd step without any validate
     * @param {type} newStep
     * @param {type} oldStep
     * @returns {undefined}      */
    function showStep(newStep, oldStep)
    {
        // hide all steps at first time
        $(".melk-step-panel[data-step='" + oldStep + "']").fadeOut(250, function() {
            $(".melk-step-panel[data-step='" + newStep + "']").fadeIn(250, function() {
                if (newStep == 2)
                {
                    google.maps.event.trigger(map, 'resize');
                }
            });
        });
        // show in wizard mode
        $(".melk-wizard-step[data-step='" + oldStep + "']").removeClass('active').addClass("done");
        $(".melk-wizard-step[data-step='" + newStep + "']").addClass('active').removeClass("done");
    }

    /**
     * this function will ready step
     * @param {type} step
     * @returns {undefined}
     */
    function readyStep(step) {
        google.maps.event.trigger(map, 'resize');
    }

    /**
     * this function will validate step
     * @param {type} step
     * @returns {undefined}
     */
    function validStep(step) {
        if (step == 1) {
            if ($("#title").val().length == 0)
            {
                alert("شما میباست نام مشاور املاک را وارد نمایید");
                return false;
            }

            if ($("#fname").val().length == 0)
            {
                alert("شما میباست نام خود را وارد نمایید");
                return false;
            }

            if ($("#lname").val().length == 0)
            {
                alert("شما میباست نام خانوادگی خود را وارد نمایید");
                return false;
            }

            if ($("#peygiri").val().length == 0)
            {
                alert("شما میباست شماره پیگیری خود را وارد نمایید");
                return false;
            }
        }
        if (step == 2)
        {
            if ($("#address").val().length == 0)
            {
                alert("شما میباست  آدرس خود را وارد نمایید");
                return false;
            }
        }
        if (step == 4)
        {
            if ($("#phone").val().length == 0)
            {
                alert("شما میباست شماره تماس خود را وارد نمایید");
                return false;
            }

            if ($("#mobile").val().length == 0)
            {
                alert("شما میباست شماره موبایل خود را وارد نمایید");
                return false;
            }
        }

        return true;
    }


    // add event on next button click
    $('body').on('click', '#nextbtn', function() {
        // get step
        var currenctStep = $(this).data('step');
        if (validStep(currenctStep))
        {
            readyStep(currenctStep + 1);
            showStep(currenctStep + 1, currenctStep);
        }

    });
    // add event on next button click
    $('body').on('click', '#backbtn', function() {
        // get step
        var currenctStep = $(this).data('step');
        showStep(currenctStep - 1, currenctStep);
    });


    // show step 1
    showStep(1, 1);


</script>


<script>

    var citiesid = [];
    var cities = [];
<?php
foreach ($cities as $city) {
    echo "citiesid[$city->id] = \"$city->name\";\n";
    $ci = $city->getStateCitiesIDWithComma();
    echo "cities[$city->stateid] = \"$ci\";\n";
}
?>


    function onstatechange(selectedstate)
    {
        console.log(selectedstate);
        console.log(cities[selectedstate]);
        var ids = cities[selectedstate];
        var cityids = ids.split(",");
        console.log(cityids);
        // remove old cities
        var citylisteleemnt = $('#cityid');
        citylisteleemnt.find('option').remove().end();
        $.each(cityids, function(index, id) {
            if (index == 0)
            {
                oncitychange(citiesid[id]);
            }
            console.log(citiesid[id]);
            citylisteleemnt.append('<option value="' + id + '">' + citiesid[id] + '</option>');
        });
    }

    function locatteToAddress(address)
    {
        geocoder.geocode({'address': address}, function(results, status) {
            console.log(results);
            if (status == google.maps.GeocoderStatus.OK) {
                console.log(results[0].geometry.location.lat().toFixed(6));
                $("#map_latitude").val(results[0].geometry.location.lat().toFixed(6)).trigger("change");
                $("#map_longitude").val(results[0].geometry.location.lng().toFixed(6)).trigger("change");
            } else {
                alert("Lat and long cannot be found.");
            }
        });
    }

    function oncitychange(city)
    {
        var state = $("#stateid").find("option:selected").text();
        var address = "ایران، " + city;
        console.log(address);
        locatteToAddress(address);
    }

    $("#stateid").change(function() {
        onstatechange(this.value);
    });

    var geocoder = new google.maps.Geocoder();
    $("#cityid").change(function() {
        var city = citiesid[$(this).val()];
        oncitychange(city);
    });

    $("#cityid").change();
</script>