<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>

            <!-- Wizards -->
            <div class="nav nav-pills nav-justified navbar melk-wizard">
                <li data-step="1" class="melk-wizard-step active"><a href="#">مشخصات بنگاه و مالک بنگاه</a></li>
                <li data-step="2" class="melk-wizard-step "><a href="#">موقعیت بنگاه</a></li>
                <li data-step="3" class="melk-wizard-step "><a href="#">مناطق قابل پوشش</a></li>
                <li data-step="4" class="melk-wizard-step "><a href="#">اطلاعات تماس</a></li>
                <li data-step="5" class="melk-wizard-step "><a href="#">تصاویر بنگاه</a></li>
            </div>


            <!--  Moshaksate   !-->
            <div data-step="1" class="panel panel-default melk-step-panel" >
                <div class="panel-heading">
                    <h3 class="panel-title">مشخصات بنگاه و مالک بنگاه</h3>
                </div>
                <div class="panel-body">
                    <p>در این قسمت مشخصات خواسته شده را وارد نمایید</p>

                    <?php $form->renderDecorated('title'); ?> 

                    <?php $form->renderDecorated('fname'); ?> 

                    <?php $form->renderDecorated('lname'); ?> 

                    <?php $form->renderDecorated('peygiri'); ?> 
                </div>
                <div class="panel-footer panel-footer-btn-group">
                    <div id="nextbtn" data-step="1" class="btn btn-primary">مرحله بعد</div>
                </div>
            </div>

            <!--Moghiyate !-->
            <div data-step="2" class="panel panel-default melk-step-panel">
                <div class="panel-heading">
                    <h3 class="panel-title">موقعیت بنگاه</h3>
                </div>
                <div class="panel-body">
                    <p>در این قسمت شما میبایست محدوده و آدرس ملک را مشخص نمایید</p>

                    <div class='row'>
                        <div class='col-md-6'>
                            <!--  ADD State ID !-->
                            <?php $form->renderDecorated('stateid'); ?> 

                            <!--  ADD City ID !-->
                            <?php $form->renderDecorated('cityid'); ?> 

                            <!--  ADD Address !-->
                            <?php $form->renderDecorated('address'); ?> 

                        </div>
                        <div class='col-md-6'>
                            <!--  Map !-->
                            <?php $form->renderDecorated('map'); ?> 
                        </div>
                    </div>
                </div>
                <div class="panel-footer panel-footer-btn-group">
                    <div id="nextbtn" data-step="2" class="btn btn-primary">مرحله بعد</div>
                    <div id="backbtn" data-step="2" class="btn btn-default">مرحله قبل</div>
                </div>
            </div>


            <!-- Manategeh Ghabel Poshesh !-->
            <div data-step="3" class="panel panel-default melk-step-panel">
                <div class="panel-heading">
                    <h3 class="panel-title">مناطق قابل پوشش</h3>
                </div>
                <div class="panel-body">

                    <?php $form->renderDecorated('locationscansupport'); ?> 

                </div>
                <div class="panel-footer panel-footer-btn-group">
                    <div id="nextbtn" data-step="3" class="btn btn-primary">مرحله بعد</div>
                    <div id="backbtn" data-step="3" class="btn btn-default">مرحله قبل</div>
                </div>
            </div>


            <!-- Contact !-->
            <div data-step="4" class="panel panel-default melk-step-panel">
                <div class="panel-heading">
                    <h3 class="panel-title">اطلاعات تماس</h3>
                </div>
                <div class="panel-body">

                    <!--  ADD Private Phone !-->
                    <?php $form->renderDecorated('phone'); ?> 

                    <!--  ADD Private Mobile !-->
                    <?php $form->renderDecorated('mobile'); ?> 

                </div>
                <div class="panel-footer panel-footer-btn-group">
                    <div id="nextbtn" data-step="4" class="btn btn-primary">مرحله بعد</div>
                    <div id="backbtn" data-step="4" class="btn btn-default">مرحله قبل</div>
                </div>
            </div>



            <!-- Images  !-->
            <div data-step="5" class="panel panel-default melk-step-panel" >
                <div class="panel-heading">
                    <h3 class="panel-title">تصاویر ملک</h3>
                </div>
                <div class="panel-body">
                    <p>برای افزایش بازدهی، شما میتوانید در صورت تمایل تعدادی تصویر را برای ملک خود ارائه نمایید</p>
                    <!--  Image !-->
                    <div class='row'>
                        <div class='col-md-6'>
                            <?php $form->renderDecorated('img1'); ?> 
                            <?php $form->renderDecorated('img3'); ?> 
                            <?php $form->renderDecorated('img5'); ?> 
                        </div>
                        <div class='col-md-6'>
                            <?php $form->renderDecorated('img2'); ?> 
                            <?php $form->renderDecorated('img4'); ?> 
                            <?php $form->renderDecorated('img6'); ?> 
                        </div>
                    </div>


                </div>
                <div class="panel-footer panel-footer-btn-group">
                    <div id="nextbtn" data-step="5" class="btn btn-primary">پایان</div>
                    <div id="backbtn" data-step="5" class="btn btn-default">مرحله قبل</div>
                </div>
            </div>


            <!-- Finish  !-->
            <div data-step="6" class="panel panel-default melk-step-panel" >
                <div class="panel-heading">
                    <h3 class="panel-title">پایان</h3>
                </div>
                <div class="panel-body final-step">
                    <h3>بعد از ارسال، مشخصات شما توسط املاک گستر بررسی و تایید قرار خواهد گرفت</h3>
                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?> 
                </div>
                <div class="panel-footer panel-footer-btn-group">
                    <div id="backbtn" data-step="6" class="btn btn-default">مرحله قبل</div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>


    // hide all steps at start
    $(".melk-step-panel").hide();


    /**
     * this function will go to the requestd step without any validate
     * @param {type} newStep
     * @param {type} oldStep
     * @returns {undefined}
     */
    function showStep(newStep, oldStep)
    {
        // hide all steps at first time
        $(".melk-step-panel[data-step='" + oldStep + "']").fadeOut(250, function() {
            $(".melk-step-panel[data-step='" + newStep + "']").fadeIn(250);
        });

        // show in wizard mode
        $(".melk-wizard-step[data-step='" + oldStep + "']").removeClass('active').addClass("done");
        $(".melk-wizard-step[data-step='" + newStep + "']").addClass('active').removeClass("done");
    }

    /**
     * this function will ready step
     * @param {type} step
     * @returns {undefined}
     */
    function readyStep(step)
    {

    }

    /**
     * this function will validate step
     * @param {type} step
     * @returns {undefined}
     */
    function validStep(step) {
        return true;
    }


    // add event on next button click
    $('body').on('click', '#nextbtn', function() {
        // get step
        var currenctStep = $(this).data('step');
        if (validStep(currenctStep))
        {
            readyStep(currenctStep + 1);
            showStep(currenctStep + 1, currenctStep);
        }

    });
    // add event on next button click
    $('body').on('click', '#backbtn', function() {
        // get step
        var currenctStep = $(this).data('step');
        showStep(currenctStep - 1, currenctStep);
    });


    // show step 1
    showStep(1, 1);


</script>


<script>

    var citiesid = [];
    var cities = [];
<?php
foreach ($cities as $city) {
    echo "citiesid[$city->id] = \"$city->name\";\n";
    $ci = $city->getStateCitiesIDWithComma();
    echo "cities[$city->stateid] = \"$ci\";\n";
}
?>


    function onstatechange(selectedstate)
    {
        console.log(selectedstate);
        console.log(cities[selectedstate]);
        var ids = cities[selectedstate];
        var cityids = ids.split(",");
        console.log(cityids);
        // remove old cities
        var citylisteleemnt = $('#cityid');
        citylisteleemnt.find('option').remove().end();
        $.each(cityids, function(index, id) {
            if (index == 0)
            {
                oncitychange(citiesid[id]);
            }
            console.log(citiesid[id]);
            citylisteleemnt.append('<option value="' + id + '">' + citiesid[id] + '</option>');
        });
    }

    function locatteToAddress(address)
    {
        geocoder.geocode({'address': address}, function(results, status) {
            console.log(results);
            if (status == google.maps.GeocoderStatus.OK) {
                console.log(results[0].geometry.location.lat().toFixed(6));
                $("#map_latitude").val(results[0].geometry.location.lat().toFixed(6)).trigger("change");
                $("#map_longitude").val(results[0].geometry.location.lng().toFixed(6)).trigger("change");
            } else {
                alert("Lat and long cannot be found.");
            }
        });
    }

    function oncitychange(city)
    {
        var state = $("#stateid").find("option:selected").text();
        var address = "ایران، " + city;
        console.log(address);
        locatteToAddress(address);
    }

    $("#stateid").change(function() {
        onstatechange(this.value);
    });
    var addressChangeTimeOut = 0;
    $("#address").change(function() {

        clearTimeout(addressChangeTimeOut);
        addressChangeTimeOut = setTimeout(function() {
            var city = $("#cityid").find("option:selected").text();
            var address = $("#address").val();
            var address = "ایران، " + city + "،" + address;
            console.log(address);
            locatteToAddress(address);
        }, 150);
    });
    var geocoder = new google.maps.Geocoder();
    $("#cityid").change(function() {
        var city = citiesid[$(this).val()];
        oncitychange(city);
    });
</script>