<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<div class='row'>
    <div class='col-lg-12'>
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">تایید پیامک</h3>
            </div>
            <div class="panel-body">
                <p>در صورت تایید، بر روی گزینه ارسال کلیک نمایید</p>
                <hr/>
                <label class="bold" style="color: #CF2184;">متن پیامک</label>
                <blockquote style="font-size: 21px;" ><?php echo nl2br($message); ?></blockquote>
                <p >سایز پیامک: <?php echo $messageSize; ?></p>
                <hr />

                <label class="bold" style="color: #CF2184;">مناطق ارسالی</label>
                <ul>
                    <?php foreach ($areas as $area) : ?>
                        <li><?php echo $area; ?> </li>
                    <?php endforeach; ?>
                </ul>
                <hr />

                <?php if ($toAllUsers == TRUE) : ?>
                    <label class="bold" style="color: #CF2184;">ارسال پیامک به صاحبان املاک</label>
                    <p style="margin-bottom: 0px;">متن شما برای تمامی افرادی که که ملک خود را در منطقه مورد نظر ارائه نموده اند، ارسال میگردد</p>
                    <p>تعداد افراد در این گروه : <?php echo $haveMelkCount; ?></p>
                    <hr />
                <?php endif; ?>


                <?php if ($toPhoneListners == TRUE) : ?>
                    <label class="bold" style="color: #CF2184;">ارسال پیامک به کاربران گوش به زنگ</label>
                    <p style="margin-bottom: 0px;">متن شما برای تمامی کاربران درخواست کننده ملک مناطق مورد نظر ارسال خواهد شد</p>
                    <p>تعداد افراد در این گروه : <?php echo $phoneListnerCount; ?></p>
                    <hr />
                <?php endif; ?>

                <div class="alert alert-success">
                    <p style="font-size: 21px;">تعداد کل پیامک های ارسالی : <?php echo $totalSMSCount; ?></p>
                </div>

                <hr/>
                <form method="post" action="<?php echo $this->url->get("bongah/smssent"); ?>">
                    <input type="hidden" name="message" value="<?php echo $message; ?>" />
                    <input type="hidden" name="areas" value="<?php echo implode(",", $areas); ?>" />
                    <input type="hidden" name="toalluser" value="<?php echo $toAllUsers ? "1" : "0"; ?>" />
                    <input type="hidden" name="tophonelistner" value="<?php echo $toPhoneListners ? "1" : "0"; ?>" />
                    <?php $form->renderDecorated('submit'); ?> 
                </form>
            </div>
        </div>
    </div>
</div>