<div class="panel">
    <div class="panel-body">
        <!--        <h1>پنل بنگاه داران</h1>
                <hr/>-->
        <p>

        </p>
        <!-- row 1 !-->
        <div class='row center'>
            <div class='col-md-4'>
                <span class="fa fa-building"></span>
                <!-- Title !-->
                <h3 class="info-title">
                    دریافت آنی اطلاعات املاک
                </h3>
                <!-- Description !-->
                <p class="info-description">
                    سشی شسیشی سشیشس یتالشستالشستاش یمشسالیتایذ سشتایشسذ تیاشسذ یتاذشسیاتذیش ی 
                </p>
            </div>
            <div class='col-md-4'>
                <span class="fa fa-phone-square"></span>
                <h3 class="info-title">
                    مشاهده املاک درخواستی
                </h3>
                <p class="info-description">
                    سشی شسیشی سشیشس یتالشستالشستاش یمشسالیتایذ سشتایشسذ تیاشسذ یتاذشسیاتذیش ی 
                </p>
            </div>
            <div class='col-md-4'>
                <span class="fa fa-envelope"></span>
                <h3 class="info-title">
                    ارسال پیام به مالکان ملک
                </h3>
                <p class="info-description">
                    سشی شسیشی سشیشس یتالشستالشستاش یمشسالیتایذ سشتایشسذ تیاشسذ یتاذشسیاتذیش ی 
                </p>
            </div>
        </div>

        <!-- row 2 !-->
        <div class='row center'>
            <div class='col-md-4'>
                <span class="fa fa-envelope"></span>
                <h3 class="info-title">
                    ارسال پیام به مالکان ملک
                </h3>
                <p class="info-description">
                    سشی شسیشی سشیشس یتالشستالشستاش یمشسالیتایذ سشتایشسذ تیاشسذ یتاذشسیاتذیش ی 
                </p>
            </div>
            <div class='col-md-4'>
                <span class="fa fa-envelope"></span>
                <h3 class="info-title">
                    ارسال پیام به مالکان ملک
                </h3>
                <p class="info-description">
                    سشی شسیشی سشیشس یتالشستالشستاش یمشسالیتایذ سشتایشسذ تیاشسذ یتاذشسیاتذیش ی 
                </p>
            </div>
            <div class='col-md-4'>
                <span class="fa fa-envelope"></span>
                <h3 class="info-title">
                    ارسال پیام به مالکان ملک
                </h3>
                <p class="info-description">
                    سشی شسیشی سشیشس یتالشستالشستاش یمشسالیتایذ سشتایشسذ تیاشسذ یتاذشسیاتذیش ی 
                </p>
            </div>
        </div>
        <hr/>
        <!-- Login Button !-->
        <div class='row center'>
            <div class='col-md-12'>
                <a class="btn btn-lg btn-default" href="link">ورود</a>
                <a class="btn btn-lg btn-primary" href="link">عضویت</a>
            </div>
        </div>
    </div>
</div>