<div class="panel review">
    <div class="panel-body">
        <h1 class="center" style="font-family: naskh;color: #970FBA;">املاک گستر چیست؟</h1>
        <p style="font-size: 21px;font-family: naskh;color:#777;text-align: justify">
            املاک گستر جدیدترین روش ارتباط مشتری و مشاوران املاک می باشد که به مشاوران املاک  امکان می دهد تا در سریعترین زمان ممکن برای املاک خود مشتری پیدا نمایند و به مشتریان  کمک می کند بی هیچ دردسری، ملک مورد نظرخود را پیدا نمایید.        </p>
        <hr style="margin-bottom: 32px;"/>
        <!-- row 1 !-->
        <div class='row center'>
            <div class='col-md-4'>
                <span class="fa fa-building"></span>
                <!-- Title !-->
                <h3 class="info-title">
                    اضافه نمودن ملک
                </h3>
                <!-- Description !-->
                <p class="info-description">
                    بعد از عضویت در سامانه املاک گستر شما قادر خواهید بود املاک خود را به سامانه اضافه نمایید تا متقاضیان بتوانند به راحتی املاک شما را مشاهده نمایند
                </p>
            </div>
            <div class='col-md-4'>
                <span class="fa fa-phone"></span>
                <h3 class="info-title">
                    مشاهده املاک درخواستی
                </h3>
                <p class="info-description">
                    افرادی که نیازمند ملک هستند می توانند به راحتی مشخصات ملک درخواستی خود را به سامانه اضافه نمایند. شما مشاور املاک گرامی میتوانید به تمامی مشخصات املاک درخواستی به همراه شماره تماس فرد درخواست کننده دسترسی داشته باشید
                    <br/>
                    <a target="_blank" style="margin-top: 12px;" href="<?php echo $this->url->get("requestmelk/list"); ?>">مشاهده آخرین املاک درخواستی</a>
                </p>
            </div>
            <div class='col-md-4'>
                <span class="fa fa-users"></span>
                <h3 class="info-title">
                    پیشنهاد خودکار
                </h3>
                <p class="info-description">
                    بعد از اینکه ملک خود را در سامانه املاک گستر اضافه نمایید، سامانه با استفاده از الگوریتم های پیشرفته خود، شماره تماس و مشخصات املاک درخواست شده را به شما نشان خواهد داد تا شما بتوانید تنها با یک کلیک، مشخصات ملک خود را برای این افراد ارسال نمایید.
                </p>
            </div>

        </div>

        <!-- row 2 !-->
        <div class='row center'>
            <div class='col-md-4'>
                <span class="fa fa-envelope"></span>
                <h3 class="info-title">
                    ارسال پیام به مالکان ملک
                </h3>
                <p class="info-description">
                    با استفاده از پنل مشاوران املاک شما قادر خواهید بود به افراد نیازمند ملک و افرادی که ملک خود را ارسال نموده اند پیامک ارسال نمایید
                </p>
            </div>
            <div class='col-md-4'>
                <span class="fa fa-home"></span>
                <h3 class="info-title">
                    مشاهده املاک تحت پوشش
                </h3>
                <p class="info-description">
                    بر اساس موقعیت جغرافیایی شما، املاک نزدیک به مشاور املاک برای شما ارائه خواهد شد تا بتوانید بهترین بازدهی را داشته باشید
                </p>
            </div>
            <div class='col-md-4'>
                <span class="fa fa-map-marker"></span>
                <h3 class="info-title">
                    نمایش مشاور املاک در صفحه ملک
                </h3>
                <p class="info-description">
                    در صورتی که ملک توسط کاربران معمولی به سایت اضافه گردند، مشاور املاک شما به عنوان مشاور املاک قابل رجوع جهت مشاهده ملک در صفحه ملک اضافه خواهد گردید
                </p>
            </div>

        </div>
        <hr/>
        <div class="alert alert-info center" style="font-family: naskh;">
            در صورتی که نیاز به توضیحات تکمیلی دارید، لطفا با شماره<?php echo "<b>" . $websiteSettings->contactphone . "</b>"; ?>  تماس حاصل فرمایید
        </div>
        <hr/>
        <!-- Login Button !-->
        <div class='row center'>
            <div class='col-md-12'>
                <a class="btn btn-lg btn-default" href="<?php echo $this->url->get("user/login"); ?>">ورود به پنل مشاوران املاک</a>
                <a class="btn btn-lg btn-primary" href="<?php echo $this->url->get("bongah/add"); ?>">عضویت رایگان</a>
            </div>
        </div>
    </div>
</div>