<div class="panel">
    <div class="panel-body">
        <h1>پنل بنگاه داران</h1>
        <hr/>
        <p>

        </p>
        <!-- row 1 !-->
        <div class='row center'>
            <div class='col-md-4'>
                <h3 class="info-title">
                    دریافت آنی اطلاعات املاک
                </h3>
            </div>
            <div class='col-md-4'>
                <h3 class="info-title">
                    مشاهده املاک درخواستی
                </h3>
            </div>
            <div class='col-md-4'>
                <h3 class="info-title">
                    ارسال پیام به مالکان ملک
                </h3>
            </div>
        </div>

        <!-- row 2 !-->
        <div class='row'>
            <div class='col-md-4'>

            </div>
            <div class='col-md-4'>

            </div>
            <div class='col-md-4'>

            </div>
        </div>
    </div>
</div>