<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>

            <!--  Moshaksate   !-->
            <div data-step="1" class="panel panel-default melk-step-panel" >
                <div class="panel-heading">
                    <h3 class="panel-title">مشخصات بنگاه و مالک بنگاه</h3>
                </div>
                <div class="panel-body">
                    <p>در این قسمت مشخصات خواسته شده را وارد نمایید</p>

                    <?php $form->renderDecorated('title'); ?> 

                    <?php $form->renderDecorated('fname'); ?> 

                    <?php $form->renderDecorated('lname'); ?> 

                    <?php $form->renderDecorated('peygiri'); ?> 
                </div>
            </div>

            <!--Moghiyate !-->
            <div data-step="2" class="panel panel-default melk-step-panel">
                <div class="panel-heading">
                    <h3 class="panel-title">موقعیت بنگاه</h3>
                </div>
                <div class="panel-body">
                    <p>در این قسمت شما میبایست محدوده و آدرس ملک را مشخص نمایید</p>

                    <div class='row'>
                        <div class='col-md-6'>
                            <!--  ADD State ID !-->
                            <?php $form->renderDecorated('stateid'); ?> 

                            <!--  ADD City ID !-->
                            <?php $form->renderDecorated('cityid'); ?> 

                            <!--  ADD Address !-->
                            <?php $form->renderDecorated('address'); ?> 

                        </div>
                        <div class='col-md-6'>
                            <!--  Map !-->
                            <?php $form->renderDecorated('map'); ?> 
                        </div>
                    </div>
                </div>
            </div>


            <!-- Manategeh Ghabel Poshesh !-->
            <div data-step="3" class="panel panel-default melk-step-panel">
                <div class="panel-heading">
                    <h3 class="panel-title">مناطق قابل پوشش</h3>
                </div>
                <div class="panel-body">

                    <?php $form->renderDecorated('locationscansupport'); ?> 

                </div>
            </div>


            <!-- Contact !-->
            <div data-step="4" class="panel panel-default melk-step-panel">
                <div class="panel-heading">
                    <h3 class="panel-title">اطلاعات تماس</h3>
                </div>
                <div class="panel-body">

                    <!--  ADD Private Phone !-->
                    <?php $form->renderDecorated('phone'); ?> 

                    <!--  ADD Private Mobile !-->
                    <?php $form->renderDecorated('mobile'); ?> 

                </div>
            </div>

            <!-- Finish  !-->
            <div data-step="6" class="panel panel-default melk-step-panel" >
                <div class="panel-heading">
                    <h3 class="panel-title">پایان</h3>
                </div>
                <div class="panel-body final-step">
                    <h3>بعد از ارسال، مشخصات شما توسط املاک گستر بررسی و تایید قرار خواهد گرفت</h3>
                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?> 
                </div>
            </div>
        </div>
    </div>
</form>
<script>

    var citiesid = [];
    var cities = [];
<?php
foreach ($cities as $city) {
    echo "citiesid[$city->id] = \"$city->name\";\n";
    $ci = $city->getStateCitiesIDWithComma();
    echo "cities[$city->stateid] = \"$ci\";\n";
}
?>


    function onstatechange(selectedstate)
    {
        var ids = cities[selectedstate];
        var cityids = ids.split(",");
        // remove old cities
        var citylisteleemnt = $('#cityid');
        citylisteleemnt.find('option').remove().end();
        $.each(cityids, function(index, id) {
            if (index == 0)
            {
                oncitychange(citiesid[id]);
            }
            citylisteleemnt.append('<option value="' + id + '">' + citiesid[id] + '</option>');
        });
    }

    function locatteToAddress(address)
    {
        geocoder.geocode({'address': address}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                $("#map_latitude").val(results[0].geometry.location.lat().toFixed(6)).trigger("change");
                $("#map_longitude").val(results[0].geometry.location.lng().toFixed(6)).trigger("change");
            } else {
                alert("Lat and long cannot be found.");
            }
        });
    }

    function oncitychange(city)
    {
        var state = $("#stateid").find("option:selected").text();
        var address = "ایران، " + city;
        console.log(address);
        locatteToAddress(address);
    }

    $("#stateid").change(function() {
        onstatechange(this.value);
    });
    var addressChangeTimeOut = 0;
    $("#address").change(function() {

        clearTimeout(addressChangeTimeOut);
        addressChangeTimeOut = setTimeout(function() {
            var city = $("#cityid").find("option:selected").text();
            var address = $("#address").val();
            var address = "ایران، " + city + "،" + address;
            console.log(address);
            locatteToAddress(address);
        }, 150);
    });
    var geocoder = new google.maps.Geocoder();
    $("#cityid").change(function() {
        var city = citiesid[$(this).val()];
        oncitychange(city);
    });


</script>
