<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel panel-primary'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>View Bongah</h2>
                                                <p class='panel-subtitle'Use this form to edit your Bongah</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD ID !-->
                                <?php $form->renderInfo('id'); ?> 

                                <!--  ADD Title !-->
                                <?php $form->renderInfo('title'); ?> 

                                <!--  ADD Shomare Peygiri !-->
                                <?php $form->renderInfo('peygiri'); ?> 

                                <!--  ADD First Name !-->
                                <?php $form->renderInfo('fname'); ?> 

                                <!--  ADD Last Name !-->
                                <?php $form->renderInfo('lname'); ?> 

                                <!--  ADD Address !-->
                                <?php $form->renderInfo('address'); ?> 

                                <!--  ADD City !-->
                                <?php $form->renderInfo('cityid'); ?> 

                                <!--  ADD Latitude !-->
                                <?php $form->renderInfo('latitude'); ?> 

                                <!--  ADD Longitude !-->
                                <?php $form->renderInfo('longitude'); ?> 

                                <!--  ADD Locations Can Support !-->
                                <?php $form->renderInfo('locationscansupport'); ?> 

                                <!--  ADD Mobile !-->
                                <?php $form->renderInfo('mobile'); ?> 

                                <!--  ADD Phone !-->
                                <?php $form->renderInfo('phone'); ?> 

                                <!--  ADD Enable !-->
                                <?php $form->renderInfo('enable'); ?> 

                                <!--  ADD Featured !-->
                                <?php $form->renderInfo('featured'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderInfo('date'); ?> 


</div>
            </section>
        </div>
    </div>
</form>


