<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>

                    <h2 class='panel-title'>Add Feedback</h2>
                </header>
                <div class='panel-body'>


                    <!--  ADD User ID !-->
                    <?php $form->renderDecorated('userid'); ?>

                    <!--  ADD Devcie Info !-->
                    <?php $form->renderDecorated('devcieinfo'); ?>

                    <!--  ADD Result Type !-->
                    <?php $form->renderDecorated('result_type'); ?>

                    <!--  ADD Result Response !-->
                    <?php $form->renderDecorated('result_response'); ?>

                    <!--  ADD Result Comment !-->
                    <?php $form->renderDecorated('result_comment'); ?>


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


