<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>مشاهده تماس</h2>
                    <p class='panel-subtitle' Use this form to edit your Feedback</p>
                </header>
                <div class='panel-body'>


                    <div class="row">
                        <div class="col-md-7">
                            <h3>نتیجه تماس</h3>
                            <p>بعد از تماس با کاربر، لطفا اطلاعات زیر را وارد نمایید</p>

                            <!--  ADD Result Type !-->
                            <?php $form->renderDecorated('result_type'); ?>

                            <!--  ADD Result Response !-->
                            <?php $form->renderDecorated('result_response'); ?>

                            <!--  ADD Result Comment !-->
                            <?php $form->renderDecorated('result_comment'); ?>

                            <!-- Submit Button !-->
                            <br/>
                            <?php $form->renderDecorated('submit'); ?>
                        </div>
                        <div class="col-md-5">
                            <h3>مشخصات تماس گیرنده</h3>
                            <p>اطلاعات تماس گیرنده در زیر قابل مشاهده می باشد.</p>

                            <!--  ADD Devcie Info !-->
                            <dl class="dl-horizontal">
                                <dd>شماره تماس: <b style="color: #0b76b7;font-size: 170%;"><?php echo $item->phone ?></b></dd>
                                <dd>تاریخ: <b><?php echo $item->getDate(); ?></b></dd>
                            </dl>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</form>


