<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel panel-primary'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>View Feedback</h2>
                    <p class='panel-subtitle' Use this form to edit your Feedback</p>
                </header>
                <div class='panel-body'>


                    <!--  ADD ID !-->
                    <?php $form->renderInfo('id'); ?>

                    <!--  ADD User ID !-->
                    <?php $form->renderInfo('userid'); ?>

                    <!--  ADD Date !-->
                    <?php $form->renderInfo('date'); ?>

                    <!--  ADD Devcie Info !-->
                    <?php $form->renderInfo('devcieinfo'); ?>

                    <!--  ADD Result Type !-->
                    <?php $form->renderInfo('result_type'); ?>

                    <!--  ADD Result Response !-->
                    <?php $form->renderInfo('result_response'); ?>

                    <!--  ADD Result Comment !-->
                    <?php $form->renderInfo('result_comment'); ?>


                </div>
            </section>
        </div>
    </div>
</form>


