<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>

                    <h2 class='panel-title'>Add LoginRequest</h2>
                </header>
                <div class='panel-body'>


                    <!--  ADD Device Model !-->
                    <?php $form->renderDecorated('devicemodel'); ?>

                    <!--  ADD Device ID !-->
                    <?php $form->renderDecorated('deviceid'); ?>

                    <!--  ADD Android Version Code !-->
                    <?php $form->renderDecorated('androidversioncode'); ?>

                    <!--  ADD Phone Number !-->
                    <?php $form->renderDecorated('phonenumber'); ?>

                    <!--  ADD Android Version Name !-->
                    <?php $form->renderDecorated('androidversionname'); ?>

                    <!--  ADD IP !-->
                    <?php $form->renderDecorated('ip'); ?>

                    <!--  ADD Token !-->
                    <?php $form->renderDecorated('token'); ?>


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


