<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>

                    <h2 class='panel-title'>افزودن گزینه حدید</h2>
                </header>
                <div class='panel-body'>



                    <!--  ADD تیتر !-->
                    <?php $form->renderDecorated('title'); ?> 

                    <!--  ADD نحوه ارسال مربوطه !-->
                    <?php $form->renderDecorated('delivery_mode_id'); ?> 

                    <!--  ADD توضیحات !-->
                    <?php $form->renderDecorated('description'); ?> 

                    <!--  ADD وضعیت !-->
                    <?php $form->renderDecorated('status'); ?> 

                    <!--  ADD ساعت شروع !-->
                    <?php $form->renderDecorated('time_start'); ?> 

                    <!--  ADD ساعت پایان !-->
                    <?php $form->renderDecorated('time_end'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


