<?php $actionName = $this->dispatcher->getActionName(); ?>
<!-- Header !-->
<?php if ($actionName != "add" && $actionName != "review") : ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class='row'>
                <div class='col-md-7'>
                    <h2 style="margin-bottom: 20px;margin-top: 13px;"><span style="top:7px;padding-left: 10px;" class="glyphicon glyphicon-home"></span>پنل بنگاه داران <small><?php echo $currentBongah->title; ?></small></h2>
                </div>
                <div class='col-md-5 bongah-cuurent-subscription'>
                    <p class="bongah-subscription-info">وضعیت اشتراک: <?php echo $subscriptionText; ?></p>
                    <p class="bongah-smscredit">اعتبار پیامک: <?php echo $currentSMSCredit; ?></p>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <div class='page-bongah'>
                <ul class="nav nav-pills nav-justified bongah-panel">
                    <li class="<?php echo $actionName == "tutorial" ? "active" : "" ?>"><a href="<?php echo $this->url->get("bongah/$currentBongah->id/tutorial/"); ?>">راهنمای استفاده</a></li> 
                    <li class="<?php echo $actionName == "melks" ? "active" : "" ?>"><a href="<?php echo $this->url->get("bongah/$currentBongah->id/melks/"); ?>">املاک شما</a></li> 
                    <li class="<?php echo $actionName == "userscansupport" ? "active" : "" ?>"><a href="<?php echo $this->url->get("bongah/$currentBongah->id/userscansupport"); ?>">املاک درخواستی</a></li> 
                    <!--<li class="<?php echo $actionName == "allmelks" ? "active" : "" ?>"><a href="<?php echo $this->url->get("bongah/$currentBongah->id/allmelks/"); ?>">لیست کامل املاک</a></li>--> 
                    <li class="<?php echo $actionName == "melkcansupport" ? "active" : "" ?>"><a href="<?php echo $this->url->get("bongah/$currentBongah->id/melkcansupport/"); ?>">املاک تحت پوشش شما</a></li> 
                    <li class="<?php echo $actionName == "settings" ? "active" : "" ?>"><a href="<?php echo $this->url->get("bongah/$currentBongah->id/settings"); ?>">تنظیمات بنگاه</a></li> 
                    <li class="<?php echo ($actionName == "sendsms" || $actionName == "checksms") ? "active" : "" ?>"><a href="<?php echo $this->url->get("bongah/$currentBongah->id/sendsms"); ?>">ارسال پیامک</a></li> 
                </ul>
                <hr/>    
                <?php echo $this->getContent(); ?>
            </div>
        </div>
    </div>
<?php else : ?>
    <div class="page-bongah">
        <?php echo $this->getContent(); ?>
    </div>
<?php endif; ?>