<footer>
    <div class="footer congruent-outline-bg">
        <div class="container">
            <div class="row">
                <!-- Contact Us !-->
                <div class="col-md-4">
                    <h3 class="head"><?php echo $websiteSettings->footertitle; ?></h3>
                    <p class="about-description">
                        <?php echo $websiteSettings->footertext; ?>
                    </p>
                </div>
                <!-- Links !-->
                <div class="col-md-4">
                    <h3 class="head"><?= _("Useful Links"); ?></h3>
                    <ul>
                        <?php echo $websiteSettings->footermenus; ?>
                    </ul>
                </div>
                <?php if ((bool) $websiteSettings->footerenablecontact) : ?>
                    <!-- About Us !-->
                    <div class="col-md-4">
                        <form>
                            <h3 class="head"><?= _("Contact Us"); ?></h3>
                            <p><?= _("Use this form to contact us"); ?></p>
                            <input type="text" name="name" placeholder="<?= _("Name"); ?>" class="form-control">
                            <br>
                            <input type="text" name="email" placeholder="<?= _("Email"); ?>" class="form-control">
                            <br>
                            <textarea type="text" name="message" placeholder="<?= _("Type your messages here"); ?>" class="form-control"></textarea>
                            <br>
                            <input type="submit" name="sendcount" value="<?= _("Send"); ?>" class="btn btn-info pull-left">
                            <div class="clearfix"></div>
                        </form>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>   
</footer>
<script type="text/javascript">
    $(document).ready(function() {
        var docHeight = $(window).height();
        var footerHeight = $('footer').height();
        var footerTop = $('footer').position().top + footerHeight;
        if (footerTop < docHeight) {
            $('footer').css('margin-top', (docHeight - footerTop) - 66 + 'px');
        }
        
    });
</script>