<footer>
    <div class="footer">
        <div class="container">
            <div class="row">
                <!-- Contact Us !-->
                <div class="col-md-4">
                    <h3 class="head"><span class="glyphicon glyphicon-certificate"></span><?php echo $websiteSettings->footertitle; ?></h3>
                    <p class="about-description">
                        <?php echo $websiteSettings->footertext; ?>
                    </p>
                </div>
                <!-- Links !-->
                <div class="col-md-4">
                    <h3 class="head"><span class="glyphicon glyphicon-link"></span><?= _("Useful Links"); ?></h3>
                    <ul>
                        <?php echo $websiteSettings->footermenus; ?>
                    </ul>
                </div>
                <?php if ((bool) $websiteSettings->footerenablecontact) : ?>
                    <!-- About Us !-->
                    <div class="col-md-4">
                        <form method="get">
                            <h3 class="head"><span class="glyphicon glyphicon-phone"></span><?= _("Contact Us"); ?></h3>
                            <p><?= _("Use this form to contact us"); ?></p>
                            <input type="text" name="name" placeholder="<?= _("Name"); ?>" class="form-control">
                            <br>
                            <input type="text" name="email" placeholder="<?= _("Email"); ?>" class="form-control">
                            <br>
                            <textarea type="text" name="message" placeholder="<?= _("Type your messages here"); ?>" class="form-control"></textarea>
                            <br>
                            <input type="submit" name="sendcount" value="<?= _("Send"); ?>" class="btn btn-bootique">
                        </form>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </div>   
</footer>