<nav class="navbar navbar-default  navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url->get("") ?>"><?php echo $websiteSettings->websitename; ?></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="<?php echo $this->url->get("contact"); ?>">CONTACT US</a></li>
                <li><a href="<?php echo $this->url->get("faq"); ?>">FAQ</a></li>
                <li><a href="<?php echo $this->url->get("opinion"); ?>">OPINIONS</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" action="<?php echo $this->url->get("search/request/1/all/") ?>" method="get">
                <div class="form-group">
                    <input name="query" type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <!-- User Panel !-->

                <?php if ($this->session->has("userid") && $this->session->get("level") == 9) : ?>
                    <li><a href="./admin/">Administrator</a></li>
                <?php endif; ?>
                <?php if ($this->session->has("userid")) : ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->session->get("fname"); ?> <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">

                            <li><a href="<?php echo $this->url->get("user/edit") ?>">Profile Settings</a></li>
                            <li class="separator"></li>
                            <li><a href="<?php echo $this->url->get("user/logout") ?>">Logout</a></li>
                        </ul>
                    </li>
                    <li><img src="<?php echo $this->session->get("imagelink"); ?>"  class="img _header-profile-image" /></li>
                    <?php else: ?>
                    <li><a href="<?php echo $this->url->get("user/login") ?>">Login</a></li>
                    <li><a href="<?php echo $this->url->get("user/register") ?>">Register</a></li>
                <?php endif; ?>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>