<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>

                    <h2 class='panel-title'>افزودن تغییرات اعتبار</h2>
                </header>
                <div class='panel-body'>

                    <h3>اطلاعات کاربر و دلیل تغییر</h3>
                    <div class="row">
                        <div class="col-md-6">
                            <!--  ADD دلیل تغییر !-->
                            <?php $form->renderDecorated('reasonid'); ?> 
                        </div>
                        <div class="col-md-6">
                            <!--  ADD کاربر !-->
                            <?php $form->renderDecorated('userid'); ?> 
                        </div>
                    </div>

                    <!--  ADD مقدار !-->
                    <?php $form->renderDecorated('amount'); ?> 

                    <hr/>
                    <p>در صورتی که قصد دارید توضیحات بیشتری در مورد این تغییرات اعتبار بیان کنید، این قسمت را مشخص کنید</p>
                    <!--  ADD اطلاعات بیشتر !-->
                    <?php $form->renderDecorated('more'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


