<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>ویرایش</h2>
                    <p class='panel-subtitle'Use this form to edit your Usercachchange</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD کاربر !-->
                    <?php $form->renderDecorated('userid'); ?> 

                    <!--  ADD مقدار !-->
                    <?php $form->renderDecorated('amount'); ?> 

                    <!--  ADD تاریخ !-->
                    <?php $form->renderDecorated('date'); ?> 

                    <!--  ADD دلیل تغییر !-->
                    <?php $form->renderDecorated('reasonid'); ?> 

                    <!--  ADD اطلاعات بیشتر !-->
                    <?php $form->renderDecorated('more'); ?> 

                    <!--  ADD هدیه !-->
                    <?php $form->renderDecorated('isgift'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


