<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel panel-primary'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>View Usercachchange</h2>
                                                <p class='panel-subtitle'Use this form to edit your Usercachchange</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD کد !-->
                                <?php $form->renderInfo('id'); ?> 

                                <!--  ADD کاربر !-->
                                <?php $form->renderInfo('userid'); ?> 

                                <!--  ADD مقدار !-->
                                <?php $form->renderInfo('amount'); ?> 

                                <!--  ADD تاریخ !-->
                                <?php $form->renderInfo('date'); ?> 

                                <!--  ADD دلیل تغییر !-->
                                <?php $form->renderInfo('reasonid'); ?> 

                                <!--  ADD اطلاعات بیشتر !-->
                                <?php $form->renderInfo('more'); ?> 

                                <!--  ADD هدیه !-->
                                <?php $form->renderInfo('isgift'); ?> 


</div>
            </section>
        </div>
    </div>
</form>


