<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>Edit PromotionProduct</h2>
                    <p class='panel-subtitle'Use this form to edit your PromotionProduct</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD Date !-->
                    <?php $form->renderDecorated('date'); ?> 

                    <!--  ADD By User ID !-->
                    <?php $form->renderDecorated('byuserid'); ?> 

                    <!--  ADD Product ID !-->
                    <?php $form->renderDecorated('productid'); ?> 

                    <!--  ADD Promotion ID !-->
                    <?php $form->renderDecorated('promotionid'); ?> 

                    <!--  ADD Total Order Per User !-->
                    <?php $form->renderDecorated('totalorderperuser'); ?> 

                    <!--  ADD Total Order !-->
                    <?php $form->renderDecorated('totalorder'); ?> 

                    <!--  ADD Title !-->
                    <?php $form->renderDecorated('title'); ?> 

                    <!--  ADD Percent !-->
                    <?php $form->renderDecorated('percent'); ?> 

                    <!--  ADD Fee !-->
                    <?php $form->renderDecorated('fee'); ?> 

                    <!--  ADD Status !-->
                    <?php $form->renderDecorated('status'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


