<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel panel-primary'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>View MelkArea</h2>
                                                <p class='panel-subtitle'Use this form to edit your MelkArea</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD ID !-->
                                <?php $form->renderInfo('id'); ?> 

                                <!--  ADD Melk ID !-->
                                <?php $form->renderInfo('melkid'); ?> 

                                <!--  ADD Area ID !-->
                                <?php $form->renderInfo('areaid'); ?> 

                                <!--  ADD City ID !-->
                                <?php $form->renderInfo('cityid'); ?> 

                                <!--  ADD By User ID !-->
                                <?php $form->renderInfo('byuserid'); ?> 

                                <!--  ADD IP !-->
                                <?php $form->renderInfo('ip'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderInfo('date'); ?> 


</div>
            </section>
        </div>
    </div>
</form>


