<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>Edit OrganSentMessage</h2>
                                                <p class='panel-subtitle'Use this form to edit your OrganSentMessage</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD Organ ID !-->
                                <?php $form->renderDecorated('organid'); ?> 

                                <!--  ADD Message !-->
                                <?php $form->renderDecorated('message'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderDecorated('date'); ?> 

                                <!--  ADD Sender Number !-->
                                <?php $form->renderDecorated('sendernumber'); ?> 

                                <!--  ADD From Number !-->
                                <?php $form->renderDecorated('fromnumber'); ?> 

                                <!--  ADD To Number !-->
                                <?php $form->renderDecorated('tonumber'); ?> 

                                <!--  ADD Cost !-->
                                <?php $form->renderDecorated('cost'); ?> 


                                <!-- Submit Button !-->
                                <br/>
                                <?php $form->renderDecorated('submit'); ?>

</div>
            </section>
        </div>
    </div>
</form>


