<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel panel-primary'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>View OrganSentMessage</h2>
                                                <p class='panel-subtitle'Use this form to edit your OrganSentMessage</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD ID !-->
                                <?php $form->renderInfo('id'); ?> 

                                <!--  ADD Organ ID !-->
                                <?php $form->renderInfo('organid'); ?> 

                                <!--  ADD Message !-->
                                <?php $form->renderInfo('message'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderInfo('date'); ?> 

                                <!--  ADD Sender Number !-->
                                <?php $form->renderInfo('sendernumber'); ?> 

                                <!--  ADD From Number !-->
                                <?php $form->renderInfo('fromnumber'); ?> 

                                <!--  ADD To Number !-->
                                <?php $form->renderInfo('tonumber'); ?> 

                                <!--  ADD Cost !-->
                                <?php $form->renderInfo('cost'); ?> 


</div>
            </section>
        </div>
    </div>
</form>


