<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post' enctype="multipart/form-data">
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>

                    <h2 class='panel-title'>ویرایش</h2>
                </header>
                <div class='panel-body'>


                    <div class="row">
                        <div class="col-md-9">
                            <!--  ADD Parent Category !-->
                            <?php $form->renderDecorated('parentcategory'); ?> 

                            <hr/>

                            <div class="row">
                                <div class="col-md-6">
                                    <!--  ADD Title !-->
                                    <?php $form->renderDecorated('title'); ?> 
                                </div>
                                <div class="col-md-6">
                                    <!--  ADD Image ID !-->
                                    <?php $form->renderDecorated('imageid'); ?> 
                                </div>
                            </div>

                            <!--  ADD Active !-->
                            <?php $form->renderDecorated('active'); ?> 

                            <!--  ADD Description !-->
                            <?php $form->renderDecorated('description'); ?> 


                            <!-- Submit Button !-->
                            <br/>
                            <?php $form->renderDecorated('submit'); ?>
                        </div>
                        <div class="col-md-3">
                            <?php if ($category->imageid > 0): ?>
                                <img style="width: 256px;height: 256px;" class="img img-responsive img-polaroid" src="<?php echo $category->getImageLink(); ?>" />
                            <?php endif; ?>
                        </div>
                    </div>




                </div>
            </section>
        </div>
    </div>
</form>


