<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel panel-primary'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>مشاهده کارمندان</h2>
                    <p class='panel-subtitle'Use this form to edit your Worker</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD ID !-->
                    <?php $form->renderInfo('id'); ?> 

                    <!--  ADD User ID !-->
                    <?php $form->renderInfo('userid'); ?> 

                    <!--  ADD First Name !-->
                    <?php $form->renderInfo('firstname'); ?> 

                    <!--  ADD Last Name !-->
                    <?php $form->renderInfo('lastname'); ?> 

                    <!--  ADD Father Name !-->
                    <?php $form->renderInfo('fathername'); ?> 

                    <!--  ADD Identity Number !-->
                    <?php $form->renderInfo('identitynumber'); ?> 

                    <!--  ADD Birthday !-->
                    <?php $form->renderInfo('birthday'); ?> 

                    <!--  ADD Worker Section ID !-->
                    <?php $form->renderInfo('workersectionid'); ?> 

                    <!--  ADD Date !-->
                    <?php $form->renderInfo('date'); ?> 

                    <!--  ADD Address !-->
                    <?php $form->renderInfo('address'); ?> 

                    <!--  ADD Phone !-->
                    <?php $form->renderInfo('phone'); ?> 

                    <!--  ADD Mobile !-->
                    <?php $form->renderInfo('mobile'); ?> 

                    <!--  ADD Status !-->
                    <?php $form->renderInfo('status'); ?> 


                </div>
            </section>
        </div>
    </div>
</form>


