<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>ویرایش شماره پیامک</h2>
                    <p class='panel-subtitle'Use this form to edit your SmsNumber</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD Number !-->
                    <?php $form->renderDecorated('number'); ?> 

                    <!--  ADD Enable !-->
                    <?php $form->renderDecorated('enable'); ?> 

                    <!--  ADD Sent Count !-->
                    <?php $form->renderDecorated('sentcount'); ?> 

                    <!--  ADD Date !-->
                    <?php $form->renderDecorated('date'); ?> 

                    <!--  ADD Description !-->
                    <?php $form->renderDecorated('description'); ?> 

                    <!--  ADD Provider Name !-->
                    <?php $form->renderDecorated('providerid'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


