<script src="<?php echo $this->url->publicurl . "ckeditor/ckeditor.js" ?>"></script>
<div class="row">
    <div class="col-md-12">
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method="post">
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">Send Bulk Email</h2>
                </header>
                <div class="panel-body">

                    <p>You can send bulk email here</p>

                    <!-- Name !-->
                    <?php $sendForm->renderDecorated("from"); ?>

                    <!-- Subject !-->
                    <?php $sendForm->renderDecorated("subject"); ?>

                    <!-- Message !-->
                    <?php $sendForm->renderDecorated("message"); ?>

                    <!-- Submit Button !-->
                    <br/>
                    <?php $sendForm->renderDecorated("submit"); ?>
                </div>
            </section>
        </div>
    </div>
</form>