<section class="panel">
    <header class="panel-heading">
        <div class="panel-actions">
            <a href="#" class="fa fa-caret-down"></a>
            <a href="#" class="fa fa-times"></a>
        </div>

        <h2 class="panel-title">Contacts</h2>
    </header>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-bordered table-striped table-condensed mb-none ">
                <tr>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Date</th>
                    <th>Replied</th>
                    <th>Action</th>
                </tr>
                <?php foreach ($contactsList->items as $item) { ?>
                    <tr>
                        <td><?php echo $item->name; ?></td>
                        <td><?php echo $item->email; ?></td>
                        <td><?php echo $item->getDate(); ?></td>
                        <td><?php echo $item->isReplied() ? "Yes" : "No"; ?></td>
                        <td>
                            <a href="<?php echo $this->url->get("contact/view/" . $item->id); ?>" class="on-default edit-row"><i class="fa fa-pencil"></i></a>
                            <a href="<?php echo $this->url->get("contact/delete/" . $item->id); ?>" class="on-default remove-row"><i class="fa fa-trash-o"></i></a>
                        </td>
                    </tr>
                <?php } ?>
            </table>
        </div>
        <!-- Paginatoing Items !-->
        <div class="center">
            <div class="pagination pagination-centered">
                <li><a class="pag" href="<?php echo $this->url->get("user/list/") ?>">First</a> </li>
                <li> <a href="<?php echo $this->url->get("user/list/$contactsList->before") ?>">Previous</a></li>
                <li> <a href="<?php echo $this->url->get("user/list/$contactsList->next") ?>">Next</a></li>
                <li> <a href="<?php echo $this->url->get("user/list/$contactsList->last") ?>">Last</a></li>
            </div>
            <div>
                <?php echo "You are in page ", $contactsList->current, " of ", $contactsList->total_pages; ?>
            </div>
        </div>
    </div>
</section>


