<div class='row'>
    <div class='col-md-8 col-md-push-2'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<div class='row'>
    <div class='col-md-8'>
        <form method='post'>
            <!-- Moshavers !-->
            <div class="well hidden">
                <div class='row'>
                    <?php foreach ($moshavers as $moshaver) : ?>
                        <div class='col-md-2'>
                            <div class="moshaver-item center">
                                <img class="img img-responsive" src="<?php echo $moshaver->getUser()->getImageLink(); ?>" />
                                <p class="name">
                                    <?php echo $moshaver->getUser()->getFullName(); ?>
                                </p>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <!-- Question Form -->
            <div>
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><span class="fa fa-question-circle"></span>پرسش سوال از مشاور</h3>
                    </div>
                    <div class="panel-body">
                        <!--  ADD Moshaver ID !-->
                        <?php $form->renderDecorated('moshaverid'); ?> 

                        <!--  ADD Question !-->
                        <?php $form->renderDecorated('question'); ?> 

                        <div class='row'>
                            <div class='col-md-6'>
                                <?php $form->renderDecorated('disorderhistory'); ?> 
                            </div>
                            <div class='col-md-6'>
                                <?php $form->renderDecorated('usingtablet'); ?> 
                            </div>
                        </div>


                        <div class='row'>
                            <div class='col-md-6'>
                                <!--  ADD City ID !-->
                                <?php $form->renderDecorated('stateid'); ?> 
                            </div>
                            <div class='col-md-6'>
                                <!--  ADD City ID !-->
                                <?php $form->renderDecorated('cityid'); ?> 
                            </div>
                        </div>

                        <!-- Check if user not logged in, handle the email and phone !-->
                        <?php if (!$this->session->has("userid")): ?>
                            <hr/>   
                            <div class='row'>
                                <div class='col-md-4'>
                                    <?php $form->renderDecorated('fname'); ?> 
                                </div>
                                <div class='col-md-4'>
                                    <?php $form->renderDecorated('lname'); ?> 
                                </div>
                                <div class='col-md-4'>
                                    <?php $form->renderDecorated('email'); ?> 
                                </div>
                            </div>
                            <hr/>    
                        <?php endif; ?>


                        <div class='row'>
                            <div class='col-md-4'>
                                <!-- Age !-->
                                <?php $form->renderDecorated('age'); ?> 
                            </div>
                            <div class='col-md-4'>
                                <!-- Gender !-->
                                <?php $form->renderDecorated('gender'); ?> 
                            </div>
                            <div class='col-md-4'>
                                <!--  Phone !-->
                                <?php $form->renderDecorated('phone'); ?> 
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <!-- Submit Button !-->
                        <?php $form->renderDecorated('submit'); ?>
                    </div>
                </div>

            </div>
        </form>
    </div>
    <!-- Old Questions !-->
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="fa fa-list"></span>سوالات <?php echo $moshaverType->name; ?></h3>
            </div>
            <div class="panel-body">
                <ul>
                    <?php foreach ($questions as $question) : ?>
                        <li>
                            <a href="<?php echo $this->url->get("question/view/$question->id"); ?>"><?php echo $question->getSmallQuestion(); ?></a>
                            <p style="color: #aaa;font-size: 12px;"><?php echo $question->getDate(); ?></p>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <div class="panel-footer">
                <a href="<?php echo $this->url->get("question/list/$moshaverType->id/1"); ?>">سوالات بیشتر بخش <?php echo $moshaverType->name; ?></a>
            </div>
        </div>
    </div>
</div>


<script>

    var citiesid = [];
    var cities = [];
<?php
foreach ($cities as $city) {
    echo "citiesid[$city->id] = \"$city->name\";\n";
    $ci = $city->getStateCitiesIDWithComma();
    echo "cities[$city->stateid] = \"$ci\";\n";
}
?>


    function onstatechange(selectedstate)
    {
        var ids = cities[selectedstate];
        var cityids = ids.split(",");
        // remove old cities
        var citylisteleemnt = $('#cityid');
        citylisteleemnt.find('option').remove().end();
        $.each(cityids, function(index, id) {
            if (index == 0)
            {
                oncitychange(citiesid[id]);
            }
            citylisteleemnt.append('<option value="' + id + '">' + citiesid[id] + '</option>');
        });
    }

    function locatteToAddress(address)
    {

    }

    function oncitychange(city)
    {
        var state = $("#stateid").find("option:selected").text();
        var address = "ایران، " + city;
        console.log(address);
        locatteToAddress(address);
    }

    $("#stateid").change(function() {
        onstatechange(this.value);
    });
    var addressChangeTimeOut = 0;
    $("#address").change(function() {

        clearTimeout(addressChangeTimeOut);
        addressChangeTimeOut = setTimeout(function() {
            var city = $("#cityid").find("option:selected").text();
            var address = $("#address").val();
            var address = "ایران، " + city + "،" + address;
            console.log(address);
            locatteToAddress(address);
        }, 150);
    });

    $("#cityid").change(function() {
        var city = citiesid[$(this).val()];
        oncitychange(city);
    });


</script>

