<div class='row'>
    <div class='col-md-8 col-md-push-2'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<div class='row'>
    <div class='col-md-8 col-md-push-2'>
        <div class="alert alert-info moshaver-type-info">
            <h1><?php echo $moshaverType->name; ?></h1>
            <p><?php echo $moshaverType->description; ?></p>
        </div>
        <form method='post'>
            <!-- Moshavers !-->
            <div class="well hidden">
                <div class='row'>
                    <?php foreach ($moshavers as $moshaver) : ?>
                        <div class='col-md-2'>
                            <div class="moshaver-item center">
                                <img class="img img-responsive" src="<?php echo $moshaver->getUser()->getImageLink(); ?>" />
                                <p class="name">
                                    <?php echo $moshaver->getUser()->getFullName(); ?>
                                </p>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>

            <!-- Question Form -->
            <div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">پرسش سوال از مشاور</h3>
                    </div>
                    <div class="panel-body">
                        <!--  ADD Moshaver ID !-->
                        <?php $form->renderDecorated('moshaverid'); ?> 

                        <!--  ADD Question !-->
                        <?php $form->renderDecorated('question'); ?> 

                        <div class='row'>
                            <div class='col-md-6'>
                                <?php $form->renderDecorated('disorderhistory'); ?> 
                            </div>
                            <div class='col-md-6'>
                                <?php $form->renderDecorated('usingtablet'); ?> 
                            </div>
                        </div>


                        <div class='row'>
                            <div class='col-md-6'>
                                <!--  ADD City ID !-->
                                <?php $form->renderDecorated('stateid'); ?> 
                            </div>
                            <div class='col-md-6'>
                                <!--  ADD City ID !-->
                                <?php $form->renderDecorated('cityid'); ?> 
                            </div>
                        </div>

                        <!-- Check if user not logged in, handle the email and phone !-->
                        <?php if (!$this->session->has("userid")): ?>
                            <hr/>   
                            <div class='row'>
                                <div class='col-md-4'>
                                    <?php $form->renderDecorated('fname'); ?> 
                                </div>
                                <div class='col-md-4'>
                                    <?php $form->renderDecorated('lname'); ?> 
                                </div>
                                <div class='col-md-4'>
                                    <?php $form->renderDecorated('email'); ?> 
                                </div>
                            </div>
                            <hr/>    
                        <?php endif; ?>


                        <div class='row'>
                            <div class='col-md-4'>
                                <!-- Age !-->
                                <?php $form->renderDecorated('age'); ?> 
                            </div>
                            <div class='col-md-4'>
                                <!-- Gender !-->
                                <?php $form->renderDecorated('gender'); ?> 
                            </div>
                            <div class='col-md-4'>
                                <!--  Phone !-->
                                <?php $form->renderDecorated('phone'); ?> 
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <!-- Submit Button !-->
                        <?php $form->renderDecorated('submit'); ?>
                    </div>
                </div>

            </div>
        </form>
    </div>
</div>


