<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<div class='row'>
    <div class='col-md-8'>
        <!-- Question !-->
        <div class="panel panel-warning">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="fa fa-question-circle"></span>سوال</h3>
            </div>
            <div class="panel-body">
                <p class="question-view-question"><?php echo nl2br($question->question); ?></p>
            </div>
        </div>
        <!-- Answer !-->
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="fa fa-pencil"></span>جواب مشاور</h3>
            </div>
            <div class="panel-body">

                <!-- Check if User Logged IN !-->
                <?php if (!isset($user)) : ?>
                    <!-- User Not Logged In Yet !-->
                    <div class="alert alert-success center" style="padding-bottom: 55px;">
                        <div class='row'>
                            <div class='col-md-8 col-md-push-2'>
                                <span class="glyphicon glyphicon-log-in" style="font-size: 150px;"></span>  
                                <h2>ورود به سایت</h2>
                                <h4>برای مشاهده جواب مشاور، ابتدا میبایست در سایت ثبت نام نمایید، در صورتی که از قبل در سایت ثبت نام نموده اید، ابتدا وارد سایت شوید</h4>
                            </div>
                        </div>
                    </div>
                <?php else : ?>
                    <?php if ($user->userid == $question->userid) : ?>
                        <!-- Vitisor Question !-->
                        <!-- Check for user paid !-->
                        <?php if ($isPaid == true): ?>
                            <blockquote>
                                <?php foreach ($answers as $answer) : ?>

                                    <div class="media">
                                        <img src="<?php echo $answer->getUser()->getImageLink(); ?>" class="img-rounded pull-right media-object" style="width: 64px">
                                        <div class="media-body">
                                            <h4 style="margin-top: 8px;" class="media-heading"><?php echo $answer->getUserName(); ?></h4>
                                            <p><?php echo $answer->message; ?></p>
                                            <p style="font-size: 80%;color:#888;"><?php echo $answer->getDate(); ?></p>
                                        </div>
                                    </div>

                                <?php endforeach; ?>
                            </blockquote>
                            <hr/>
                            <h3>ارسال جواب</h3>
                            <form method="post">
                                <?php $form->renderDecorated('answer'); ?>

                                <?php $form->renderDecorated('submit'); ?> 
                            </form>
                        <?php else : // User Not Paid?>
                            <!-- Check if question is anwered !-->
                            <?php if ($isAnswered == true) : ?>
                                <div class='row'>
                                    <div class='col-md-10 col-md-push-1'>
                                        <div class="unpaid-question-alert">
                                            <span class="fa fa-eye"></span>
                                            <p>جهت مشاهده جواب شما میبایست حق الزحمه مشاوره را پرداخت نمایید، به محض پرداخت شما قادر خواهید بود جواب مشاور را مشاهده نمایید و در صورت لزوم به مشاور پاسخ دهید</p>
                                            <a class="btn btn-lg btn-primary" href="<?php echo $this->url->get("question/order/" . $question->id); ?>">پرداخت آنلاین</a>
                                        </div>
                                    </div>
                                </div>
                            <?php else : // Not Answered?>
                                <div class="alert alert-success center" style="padding-bottom: 55px;">
                                    <div class='row'>
                                        <div class='col-md-8 col-md-push-2'>
                                            <span class="glyphicon glyphicon-user" style="font-size: 150px;"></span>  
                                            <h2>منتظر پاسخ</h2>
                                            <h3>سوال شما در حال انتظار برای جواب توسط مشاور مرتبط میباشد، به محض ارسال جواب شما توسط پیامک و ایمیل با خبر خواهید شد</h3>
                                        </div>
                                    </div>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    <?php else : ?>
                        <!-- This is not user question -->
                        <div class="alert alert-warning center" style="padding-bottom: 55px;">
                            <div class='row'>
                                <div class='col-md-8 col-md-push-2'>
                                    <span class="fa fa-eye" style="font-size: 150px;"></span>  
                                    <h2>غیر قابل مشاهده</h2>
                                    <h3>جواب مشاوران به سوال، تنها برای سوال کننده قابل مشاهده میباشد.</h3>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <!-- Question Info !-->
    <div class="col-md-4">

        <!-- Moshaver !-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="fa fa-user"></span> اطلاعات مشاور</h3>
            </div>
            <div class="panel-body">
                <?php $moshaver = $question->getMoshaver(); ?>
                <div class="media question-moshaver">
                    <img style="width: 96px;" src="<?php echo $moshaver->getUser()->getImageLink(); ?>" class="img-rounded img-responsive img media-object pull-right" />
                    <div class="media-body">
                        <h3 class="media-heading name"><?php echo $moshaver->getUser()->getFullName(); ?></h3>
                        <p><?php echo $moshaver->getTypeName(); ?></p>
                    </div>
                </div>
            </div>
        </div>

        <!-- Submitter Info !-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">اطلاعات ارسال کننده</h3>
            </div>
            <div class="panel-body">
                <!-- Name !-->
                <?php if (isset($user) && $user->userid == $question->userid) : ?>
                    <label>
                        ارسال کننده
                    </label>
                    <p><?php echo $question->getUser()->getFullName(); ?></p>
                    <hr/>
                <?php endif; ?>
                <label>
                    تاریخ
                </label>
                <p><?php echo $question->getDate(); ?></p>
                <hr/>
                <label>
                    سن
                </label>
                <p><?php echo $question->age . " ساله"; ?></p>
                <hr/>
                <label>
                    جنسیت
                </label>
                <p><?php echo $question->gender == 1 ? "مرد" : "زن"; ?></p>
                <hr/>
                <label>
                    شهر
                </label>
                <p><?php echo $question->getCityName(); ?></p>
            </div>
        </div>

        <!-- Disorder History !-->
        <?php if (isset($question->disorderhistory) && strlen($question->disorderhistory) > 0): ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">سابقه بیماری </h3>
                </div>
                <div class="panel-body">
                    <p><?php echo $question->disorderhistory; ?></p>
                </div>
            </div>
        <?php endif; ?>

        <!-- Tablet Usage History !-->
        <?php if (isset($question->usingtablet) && strlen($question->usingtablet) > 0): ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">سابقه مصرف دارو </h3>
                </div>
                <div class="panel-body">
                    <p><?php echo $question->usingtablet; ?></p>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>


