<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<div class='row'>
    <div class='col-md-8'>
        <!-- Question !-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">سوال</h3>
            </div>
            <div class="panel-body">
                <p class="question-view-question"><?php echo nl2br($question->question); ?></p>
            </div>
        </div>
        <!-- Answer !-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جواب</h3>
            </div>
            <div class="panel-body">
                <!-- Check for user paid !-->
                <?php if ($isPaid == true): ?>
                    <blockquote>
                        <?php foreach ($answers as $answer) : ?>

                            <div class="media">
                                <img src="<?php echo $answer->getUser()->getImageLink(); ?>" class="img-rounded pull-right media-object" style="width: 64px">
                                <div class="media-body">
                                    <h4 style="margin-top: 8px;" class="media-heading"><?php echo $answer->getUserName(); ?></h4>
                                    <?php echo $answer->message; ?>
                                </div>
                            </div>

                        <?php endforeach; ?>
                    </blockquote>
                    <hr/>
                    <h3>ارسال جواب</h3>
                    <form method="post">
                        <?php $form->renderDecorated('answer'); ?>

                        <?php $form->renderDecorated('submit'); ?> 
                    </form>
                <?php else : // User Not Paid?>

                    <!-- Check if question is anwered !-->
                    <?php if ($isAnswered == true) : ?>
                        <div class='row'>
                            <div class='col-md-10 col-md-push-1'>
                                <div class="unpaid-question-alert">
                                    <span class="fa fa-eye"></span>
                                    <p>جهت مشاهده جواب شما میبایست حق الزحمه مشاوره را پرداخت نمایید، به محض پرداخت شما قادر خواهید بود جواب مشاور را مشاهده نمایید و در صورت لزوم به مشاور پاسخ دهید</p>
                                    <a class="btn btn-lg btn-primary" href="<?php echo $this->url->get("question/order/" . $question->id); ?>">پرداخت آنلاین</a>
                                </div>
                            </div>
                        </div>
                    <?php else : // Not Answered?>
                        <div class="alert alert-info center">
                            <div class='row'>
                                <div class='col-md-6 col-md-push-3'>
                                    <span class="glyphicon glyphicon-user" style="font-size: 150px;"></span>  
                                    <h2>منتظر پاسخ</h2>
                                    <h3>سوال شما در حال انتظار برای جواب توسط مشاور مرتبط میباشد، به محض ارسال جواب شما توسط پیامک و ایمیل با خبر خواهید شد</h3>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <!-- Question Info !-->
    <div class="col-md-4">

        <!-- Submitter Info !-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">اطلاعات ارسال کننده</h3>
            </div>
            <div class="panel-body">
                <label>
                    ارسال کننده
                </label>
                <p><?php echo $question->getUser()->getFullName(); ?></p>
                <hr/>
                <label>
                    تاریخ
                </label>
                <p><?php echo $question->getDate(); ?></p>
                <hr/>
                <label>
                    سن
                </label>
                <p><?php echo $question->age . " ساله"; ?></p>
                <hr/>
                <label>
                    جنسیت
                </label>
                <p><?php echo $question->gender == 1 ? "مرد" : "زن"; ?></p>
                <hr/>
                <label>
                    شهر
                </label>
                <p><?php echo $question->getCityName(); ?></p>
            </div>
        </div>

        <!-- Disorder History !-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">سابقه بیماری </h3>
            </div>
            <div class="panel-body">
                <p><?php echo $question->disorderhistory; ?></p>
            </div>
        </div>

        <!-- Disorder History !-->
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">سابقه مصرف دارو </h3>
            </div>
            <div class="panel-body">
                <p><?php echo $question->usingtablet; ?></p>
            </div>
        </div>
    </div>
</div>


