<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel panel-primary'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>View Seller</h2>
                                                <p class='panel-subtitle'Use this form to edit your Seller</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD ID !-->
                                <?php $form->renderInfo('id'); ?> 

                                <!--  ADD User ID !-->
                                <?php $form->renderInfo('userid'); ?> 

                                <!--  ADD Parent Seller !-->
                                <?php $form->renderInfo('parent_seller'); ?> 

                                <!--  ADD Type !-->
                                <?php $form->renderInfo('type'); ?> 

                                <!--  ADD Title !-->
                                <?php $form->renderInfo('title'); ?> 

                                <!--  ADD Description !-->
                                <?php $form->renderInfo('description'); ?> 

                                <!--  ADD City ID !-->
                                <?php $form->renderInfo('cityid'); ?> 

                                <!--  ADD Latitude !-->
                                <?php $form->renderInfo('latitude'); ?> 

                                <!--  ADD Longitude !-->
                                <?php $form->renderInfo('longitude'); ?> 

                                <!--  ADD Address !-->
                                <?php $form->renderInfo('address'); ?> 

                                <!--  ADD Phone !-->
                                <?php $form->renderInfo('phone'); ?> 

                                <!--  ADD Postal Code !-->
                                <?php $form->renderInfo('postal_code'); ?> 

                                <!--  ADD Business Code !-->
                                <?php $form->renderInfo('business_code'); ?> 

                                <!--  ADD Fax !-->
                                <?php $form->renderInfo('fax'); ?> 

                                <!--  ADD Image ID !-->
                                <?php $form->renderInfo('imageid'); ?> 

                                <!--  ADD Location Can Send !-->
                                <?php $form->renderInfo('location_can_send'); ?> 

                                <!--  ADD Status !-->
                                <?php $form->renderInfo('status'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderInfo('date'); ?> 


</div>
            </section>
        </div>
    </div>
</form>


