<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>

                    <h2 class='panel-title'>افزودن انبار جدید</h2>
                </header>
                <div class='panel-body'>

                    <div class="row">
                        <div class="col-md-6">
                            <h3>اطلاعات انبار</h3>
                            <p>اطلاعات شامل نام و وضعیت انبار را مشخص نمایید</p>

                            <!--  ADD Address !-->
                            <?php $form->renderDecorated('address'); ?> 

                            <!--  ADD City ID !-->
                            <?php $form->renderDecorated('cityid'); ?> 

                            <!--  ADD Status !-->
                            <?php $form->renderDecorated('status'); ?> 

                            <hr/>
                            <!-- Submit Button !-->
                            <br/>
                            <?php $form->renderDecorated('submit'); ?>
                        </div>
                        <div class="col-md-6">
                            <h3>موقعیت جغرافیایی</h3>
                            <p>شما میتوانید موقعیت جغرافیایی انبار خود را در این قسمت مشخص نمایید</p>
                            <!--  ADD Longitude !-->
                            <?php $form->renderDecorated('map'); ?> 




                        </div>
                    </div>


                </div>
            </section>
        </div>
    </div>
</form>


