<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>View SystemLog</h2>
                    <p class='panel-subtitle'Use this form to edit your SystemLog</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD ID !-->
                    <?php $form->renderInfo('id'); ?> 

                    <!--  ADD Title !-->
                    <?php $form->renderInfo('title'); ?> 

                    <!--  ADD IP !-->
                    <?php $form->renderInfo('ip'); ?> 

                    <!--  ADD Message !-->
                    <?php $form->renderInfo('message'); ?> 

                    <!--  ADD Date !-->
                    <?php $form->renderInfo('date'); ?> 

                </div>
            </section>
        </div>
    </div>
</form>


