<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>

                    <h2 class='panel-title'>واردات کالای جدید</h2>
                </header>
                <div class='panel-body'>



                    <h3>افزودن ورودی جدید محصولات</h3>
                    <p>در صورت وارد کردن یک محصول جدید به انبار، اطلاعات مصحول را در این بخش وارد نمایید</p>

                    <!--  ADD Product ID !-->
                    <?php $form->renderDecorated('productid'); ?> 
                    <!--  ADD Total !-->
                    <?php $form->renderDecorated('total'); ?> 
                    <!--  ADD Expire Date !-->
                    <?php $form->renderDecorated('expiredate'); ?> 

                    <h3>قیمت خرید و فروش</h3>
                    <p>وارد کردن قیمت خرید و فروش هر دو اجباری می باشد</p>


                    <!--  ADD Buy Price !-->
                    <?php $form->renderDecorated('buyprice'); ?> 

                    <!--  ADD Sell Price !-->
                    <?php $form->renderDecorated('sellprice'); ?> 




                    <h3>محل قرارگیری محصول</h3>
                    <p>موقعیت دقیق قرارگیری محصول را مشخص نمایید</p>

                    <!--  ADD Warehouse Part ID !-->
                    <?php $form->renderDecorated('warehousepartid'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>
                </div>
            </section>
        </div>
    </div>
</form>


