<h1><?= _("Contact US"); ?></h1>
<div class='row'>
    <div class='col-md-6'>
        <?php echo $this->getContent(); ?>
        <form method="post">

            <!-- First Name !-->
            <?php echo $form->renderDecorated('name'); ?>

            <!-- Email !-->
            <?php echo $form->renderDecorated('email'); ?>

            <!-- Section !-->
            <?php echo $form->renderDecorated('section'); ?>

            <!-- Password !-->
            <?php echo $form->renderDecorated('message'); ?>

            <br/>
            <!-- Submit !-->
            <?php echo $form->renderDecorated('submit'); ?>

        </form>

    </div>
    <div class='col-md-6'>
        <!-- Map !-->
        <?php echo $form->renderDecorated('map'); ?>

        <hr/>

        <h3><?= _("Address"); ?></h3>
        <p><?php echo $websiteSettings->address; ?></p>

        <h3><?= _("Phone"); ?></h3>
        <p><?php echo $websiteSettings->contactphone; ?></p>

        <h3><?= _("Email"); ?></h3>
        <p><?php echo $websiteSettings->contactemail; ?></p>
    </div>
</div>

