<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel panel-default'>
                <header class='panel-heading'>
                    <h2 class='panel-title'>ویرایش سمت</h2>
                </header>
                <div class='panel-body'>
                    <div class="row">
                        <div class="col-sm-6">
                            <!--  ADD Organ ID !-->
                    <?php $form->renderDecorated('organid'); ?> 

                    <!--  ADD Name !-->
                    <?php $form->renderDecorated('name'); ?> 
                        </div>
                        <div class="col-sm-6">
                            <!--  ADD Key !-->
                    <?php $form->renderDecorated('key'); ?> 

                    <!--  ADD SMS Key !-->
                    <?php $form->renderDecorated('smskey'); ?> 
                        </div>
                    </div>
                    <hr>
                    <!-- Submit Button !-->
                    <div class="row">
                        <div class="col-sm-4"><?php $form->renderDecorated('submit'); ?></div>
                        <div class="col-sm-4"></div>
                        <div class="col-sm-4">
                            <a href="<?php echo $this->url->get("organ/$organId/posts/") ?>" class="btn btn-info pull-left">بازگشت</a>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</form>


