<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>

                                                <h2 class='panel-title'>Add Bongah</h2>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD Title !-->
                                <?php $form->renderDecorated('title'); ?> 

                                <!--  ADD Shomare Peygiri !-->
                                <?php $form->renderDecorated('peygiri'); ?> 

                                <!--  ADD First Name !-->
                                <?php $form->renderDecorated('fname'); ?> 

                                <!--  ADD Last Name !-->
                                <?php $form->renderDecorated('lname'); ?> 

                                <!--  ADD Address !-->
                                <?php $form->renderDecorated('address'); ?> 

                                <!--  ADD City !-->
                                <?php $form->renderDecorated('cityid'); ?> 

                                <!--  ADD Latitude !-->
                                <?php $form->renderDecorated('latitude'); ?> 

                                <!--  ADD Longitude !-->
                                <?php $form->renderDecorated('longitude'); ?> 

                                <!--  ADD Locations Can Support !-->
                                <?php $form->renderDecorated('locationscansupport'); ?> 

                                <!--  ADD Mobile !-->
                                <?php $form->renderDecorated('mobile'); ?> 

                                <!--  ADD Phone !-->
                                <?php $form->renderDecorated('phone'); ?> 

                                <!--  ADD Enable !-->
                                <?php $form->renderDecorated('enable'); ?> 

                                <!--  ADD Featured !-->
                                <?php $form->renderDecorated('featured'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderDecorated('date'); ?> 


                                <!-- Submit Button !-->
                                <br/>
                                <?php $form->renderDecorated('submit'); ?>

</div>
            </section>
        </div>
    </div>
</form>


