<h1>Edit Profile Information</h1>
<div class='row'>
    <div class='col-md-6'>
        <p>You can edit your basic profile information here</p>
        <?php $this->partial("layouts/usersettingsheader") ?>
        <div class="_account-settings-tab-content">
            <?php echo $this->getContent(); ?>
            <form method="post" >

                <!-- Email !-->
                <?php echo $form->renderDecorated('email'); ?>

                <hr/>
                <p class="alert alert-info alert-small">In order to change your password, set new password and click on submit button</p>   

                <!-- Password !-->
                <?php echo $form->renderDecorated('password'); ?>

                <!-- New Password !-->
                <?php echo $form->renderDecorated('newpassword'); ?>

                <!-- Confirm New Password !-->
                <?php echo $form->renderDecorated('newpasswordconfirm'); ?>

                <br/>
                <!-- Submit !-->
                <?php echo $form->renderDecorated('submit'); ?>

            </form>
        </div>
        <div class='col-md-6'>

        </div>
    </div>
</div>

