<div class="panel panel-default">
    <div class="panel-heading">
        <h1 class="panel-title"><?= _("View And Edit Login Details"); ?></h1>
    </div>
    <div class="panel-body">
        <p><?= _("You can edit your basic profile information here"); ?></p>
        <?php $this->partial("layouts/usersettingsheader") ?>
        <div class="_account-settings-tab-content">
            <?php echo $this->getContent(); ?>
            <form method="post" >

                <!-- Email !-->
                <?php echo $form->renderDecorated('email'); ?>

                <hr/>
                <p class="alert alert-info alert-small"><?= _("In order to change your password, set new password and click on submit button"); ?></p>   

                <!-- Password !-->
                <?php echo $form->renderDecorated('password'); ?>

                <!-- New Password !-->
                <?php echo $form->renderDecorated('newpassword'); ?>

                <!-- Confirm New Password !-->
                <?php echo $form->renderDecorated('newpasswordconfirm'); ?>

                <br/>
                <!-- Submit !-->
                <?php echo $form->renderDecorated('submit'); ?>

            </form>
        </div>
    </div>
</div>
