<div class="panel panel-default">
    <div class="panel-heading">
        <h1 class="panel-title"><?= _("Edit Profile Information"); ?></h1>
    </div>
    <div class="panel-body">
        <p><?= _("You can edit your basic profile information here"); ?></p>
        <?php $this->partial("layouts/usersettingsheader") ?>
        <div class="_account-settings-tab-content">
            <?php echo $this->getContent(); ?>
            <form method="post">

                <!-- First Name !-->
                <?php echo $form->renderDecorated('firstname'); ?>

                <!-- Last Name!-->
                <?php echo $form->renderDecorated('lastname'); ?>

                <!-- Gender !-->
                <?php echo $form->renderDecorated('gender'); ?>
                <br/>
                <!-- Submit !-->
                <?php echo $form->renderDecorated('submit'); ?>

            </form>
        </div>
    </div>
</div>
