<div class="panel panel-default">
    <div class="panel-heading">
        <h1 class="panel-title"><?= _("Forget Your Password"); ?></h1>
    </div>
    <div class="panel-body">
        <p><?= _("Please enter your email address to reset your password"); ?></p>
        <?php echo $this->getContent(); ?>
        <form method="post">

            <!-- Email !-->
            <?php echo $form->renderDecorated('email'); ?>

            <br/>
            <!-- Submit !-->
            <?php echo $form->renderDecorated('submit'); ?>

        </form>
    </div>
</div>