<h1>Forget Your Password</h1>
<div class='row'>
    <div class='col-md-6'>
        <p>Please enter your email address to reset your password</p>
        <?php echo $this->getContent(); ?>
        <form method="post">

            <!-- Email !-->
            <?php echo $form->renderDecorated('email'); ?>

            <br/>
            <!-- Submit !-->
            <?php echo $form->renderDecorated('submit'); ?>

        </form>

    </div>
    <div class='col-md-6'>

    </div>
</div>

