<div class='row'>
    <div class='col-md-6 col-md-push-3'>
        <?php echo $this->getContent(); ?>
    </div>
</div>
<div class='row'>
    <div class='col-md-6 col-md-push-3'>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title"><?= _("Login Details"); ?></h1>
            </div>
            <div class="panel-body">
                <p><?= _("Please enter your information to login to site"); ?></p>
                <form method="post">

                    <!-- First Name !-->
                    <?php echo $loginform->renderDecorated('email'); ?>

                    <!-- Last Name!-->
                    <?php echo $loginform->renderDecorated('password'); ?>

                    <br/>
                    <p>
                        <a href="<?php echo $this->url->get("user/forgetpassword") ?>"><?= _("Forget Password"); ?></a>
                    </p>

                    <!-- Submit !-->
                    <?php echo $loginform->renderDecorated('submit'); ?>

                </form
            </div>
        </div>
    </div>
</div>