<div class="panel panel-default">
    <div class="panel-heading">
        <h1 class="panel-title"><?= _("Orders"); ?></h1>
    </div>
    <div class="panel-body">
        <p><?= _("View your orders"); ?></p>
        <?php $this->partial("layouts/usersettingsheader") ?>
        <div class="_account-settings-tab-content">
            <?php echo $this->getContent(); ?>
            <?php
            echo $list->header;
            echo $list->table;
            echo $list->footer;
            ?>
        </div>
    </div>
</div>