<h1><?= _("Manage Your Phones"); ?></h1>
<div class='row'>
    <div class='col-md-6'>
        <p><?= _("you can add, delete or edit your phone numbers here"); ?></p>
        <?php $this->partial("layouts/usersettingsheader") ?>
        <div class="_account-settings-tab-content">
            <?php echo $this->getContent(); ?>
            <?php
            echo $list->header;
            echo $list->table;
            echo $list->footer;
            ?>
        </div>
    </div>
</div>

