<?php

use Simpledom\Core\Classes\Config; ?>
<div class='row signup-form'>
    <div class='col-md-3'>

    </div>
    <div class='col-md-6'>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title"><span class="fa fa-user"></span><?= _("Register to the site"); ?></h1>
            </div>
            <div class="panel-body">
                <p><?= _("Here you can register to the site"); ?></p>
                <?php echo $this->getContent(); ?>
                <form method="post">

                    <div class='row'>
                        <div class='col-md-6'>
                            <!-- First Name !-->
                            <?php echo $registerform->renderDecorated('firstname'); ?>
                        </div>
                        <div class='col-md-6'>
                            <!-- Last Name!-->
                            <?php echo $registerform->renderDecorated('lastname'); ?>
                        </div>
                    </div>

                    <!-- Gender !-->
                    <?php echo $registerform->renderDecorated('gender'); ?>

                    <!-- Email !-->
                    <?php echo $registerform->renderDecorated('email'); ?>

                    <!-- Password !-->
                    <?php echo $registerform->renderDecorated('password'); ?>

                    <?php if (intval(Settings::Get()->requestuserphoneonregister) == 1) : ?>
                        <!-- Phone !-->
                        <?php echo $registerform->renderDecorated('phone'); ?>
                    <?php endif; ?>

                    <br/>

                    <!-- Agreement !-->
                    <?php echo $registerform->renderDecorated('agreement'); ?>


                    <!-- Captcha !-->
                    <?php echo Recaptcha::get(Config::GetRecaptchaPublicKey()); ?>

                    <!-- Submit !-->
                    <?php echo $registerform->renderDecorated('submit'); ?>

                </form>
            </div>
        </div>
    </div>
    <div class='col-md-3'>

    </div>
</div>