<?php use Simpledom\Core\Classes\Config; ?>
<h1><?= _("Register to the site"); ?></h1>
<div class='row'>
    <div class='col-md-6'>
        <p><?= _("Here you can register to the site"); ?></p>
        <?php echo $this->getContent(); ?>
        <form method="post">

            <!-- First Name !-->
            <?php echo $registerform->renderDecorated('firstname'); ?>

            <!-- Last Name!-->
            <?php echo $registerform->renderDecorated('lastname'); ?>

            <!-- Gender !-->
            <?php echo $registerform->renderDecorated('gender'); ?>

            <!-- Email !-->
            <?php echo $registerform->renderDecorated('email'); ?>

            <!-- Password !-->
            <?php echo $registerform->renderDecorated('password'); ?>

            <?php if (intval(Settings::Get()->requestuserphoneonregister) == 1) : ?>
                <!-- Phone !-->
                <?php echo $registerform->renderDecorated('phone'); ?>
            <?php endif; ?>

            <br/>

            <!-- Agreement !-->
            <?php echo $registerform->renderDecorated('agreement'); ?>
            
            
            <!-- Captcha !-->
            <?php echo Recaptcha::get(Config::GetRecaptchaPublicKey()); ?>

            <!-- Submit !-->
            <?php echo $registerform->renderDecorated('submit'); ?>

        </form>

    </div>
    <div class='col-md-6'>

    </div>
</div>

