<div class='row'>
    <div class='col-md-3'>

    </div>
    <div class='col-md-6'>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1 class="panel-title"><span class="fa fa-refresh"></span>بازیابی رمز عبور</h1>
            </div>
            <div class="panel-body">
                <?php echo $this->getContent(); ?>
                <?php if (isset($form)): ?>
                    <p>لطفا رمز عبور جدید خود را وارد نمایید</p>
                    <form method="post">

                        <?php echo $form->renderDecorated('newpassword'); ?>
                        <?php echo $form->renderDecorated('newpasswordconfirm'); ?>

                        <br/>
                        <!-- Submit !-->
                        <?php echo $form->renderDecorated('submit'); ?>

                    </form>
                <?php endif; ?>
            </div>
        </div>
    </div>
    <div class='col-md-3'>

    </div>
</div>