<h1>Edit Profile Information</h1>
<div class='row'>
    <div class='col-md-6'>
        <p>You can edit your basic profile information here</p>
        <?php $this->partial("layouts/usersettingsheader") ?>
        <div class="_account-settings-tab-content">
            <?php
            echo $list->table;
            echo $list->footer;
            ?>
        </div>
        <div class='col-md-6'>

        </div>
    </div>
</div>
