<h1><?= _("View Login History"); ?></h1>
<div class='row'>
    <div class='col-md-6'>
        <p><?= _("You can see your login history here"); ?></p>
        <?php $this->partial("layouts/usersettingsheader") ?>
        <div class="_account-settings-tab-content">
            <?php
            echo $list->table;
            echo $list->footer;
            ?>
        </div>
        <div class='col-md-6'>

        </div>
    </div>
</div>
