<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>Edit BongahSubscribeItem</h2>
                                                <p class='panel-subtitle'Use this form to edit your BongahSubscribeItem</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD Name !-->
                                <?php $form->renderDecorated('name'); ?> 

                                <!--  ADD Description !-->
                                <?php $form->renderDecorated('description'); ?> 

                                <!--  ADD Melks Can Add !-->
                                <?php $form->renderDecorated('melkscanadd'); ?> 

                                <!--  ADD Price !-->
                                <?php $form->renderDecorated('price'); ?> 

                                <!--  ADD Valid Days !-->
                                <?php $form->renderDecorated('validdate'); ?> 

                                <!--  ADD Send Message To Users !-->
                                <?php $form->renderDecorated('sendmessagetousers'); ?> 

                                <!--  ADD Featured !-->
                                <?php $form->renderDecorated('featured'); ?> 

                                <!--  ADD Can See User Phone !-->
                                <?php $form->renderDecorated('canseeuserphone'); ?> 

                                <!--  ADD Default SMS Credit !-->
                                <?php $form->renderDecorated('defaultsmscredit'); ?> 

                                <!--  ADD Receive Portal !-->
                                <?php $form->renderDecorated('receiveportal'); ?> 

                                <!--  ADD Enable !-->
                                <?php $form->renderDecorated('enable'); ?> 


                                <!-- Submit Button !-->
                                <br/>
                                <?php $form->renderDecorated('submit'); ?>

</div>
            </section>
        </div>
    </div>
</form>


