<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel panel-primary'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>View PaymentPayline</h2>
                                                <p class='panel-subtitle'Use this form to edit your PaymentPayline</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD ID !-->
                                <?php $form->renderInfo('id'); ?> 

                                <!--  ADD User ID !-->
                                <?php $form->renderInfo('userid'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderInfo('date'); ?> 

                                <!--  ADD Amount !-->
                                <?php $form->renderInfo('amount'); ?> 

                                <!--  ADD Currency !-->
                                <?php $form->renderInfo('cur'); ?> 

                                <!--  ADD User Transaction ID !-->
                                <?php $form->renderInfo('usertransactionid'); ?> 

                                <!--  ADD Payline ID Get !-->
                                <?php $form->renderInfo('paylineidget'); ?> 

                                <!--  ADD Payline Transaction ID !-->
                                <?php $form->renderInfo('paylinetransactionid'); ?> 

                                <!--  ADD Done !-->
                                <?php $form->renderInfo('done'); ?> 


</div>
            </section>
        </div>
    </div>
</form>


