<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>

            <!-- Wizards -->
            <div class="nav nav-pills nav-justified navbar melk-wizard">
                <li data-step="1" class="melk-wizard-step active"><a href="#">نوع ملک</a></li>
                <li data-step="2" class="melk-wizard-step "><a href="#">مشخصات ملک</a></li>
                <li data-step="3" class="melk-wizard-step "><a href="#">موقعیت ملک</a></li>
                <li data-step="4" class="melk-wizard-step "><a href="#">قیمت</a></li>
                <li data-step="5" class="melk-wizard-step "><a href="#">اطلاعات تماس</a></li>
                <li data-step="6" class="melk-wizard-step "><a href="#">تصاویر ملک</a></li>
            </div>


            <!-- Noe Melk  !-->
            <div data-step="1" class="panel panel-default melk-step-panel" >
                <div class="panel-heading">
                    <h3 class="panel-title">نوع ملک</h3>
                </div>
                <div class="panel-body">
                    <p>در این فرم، نوع ملک و منظور از ارائه ملک را مشخص نموده</p>
                    <!--  ADD Type !-->
                    <?php $form->renderDecorated('melktypeid'); ?> 

                    <!--  ADD Purpose !-->
                    <?php $form->renderDecorated('melkpurposeid'); ?> 
                </div>
                <div class="panel-footer panel-footer-btn-group">
                    <div id="nextbtn" data-step="1" class="btn btn-primary">مرحله بعد</div>
                </div>
            </div>


            <!-- Moshakasate Melk !-->
            <div data-step="2" class="panel panel-default melk-step-panel">
                <div class="panel-heading">
                    <h3 class="panel-title">مشخصات ملک</h3>
                </div>
                <div class="panel-body">

                    <p>مشخصات کلی ملک را در این قسمت وارد نمایید</p>

                    <!--  ADD Home Size !-->
                    <?php $form->renderDecorated('home_size'); ?> 

                    <!--  ADD Lot Size !-->
                    <?php $form->renderDecorated('lot_size'); ?>

                    <!--  ADD Bedrooms !-->
                    <?php $form->renderDecorated('bedroom'); ?> 

                    <!--  ADD Bath !-->
                    <?php $form->renderDecorated('bath'); ?> 
                </div>
                <div class="panel-footer panel-footer-btn-group">
                    <div id="nextbtn" data-step="2" class="btn btn-primary">مرحله بعد</div>
                    <div id="backbtn" data-step="2" class="btn btn-default">مرحله قبل</div>
                </div>
            </div>


            <!--Moghiyate Melk !-->
            <div data-step="3" class="panel panel-default melk-step-panel">
                <div class="panel-heading">
                    <h3 class="panel-title">موقعیت ملک</h3>
                </div>
                <div class="panel-body">
                    <p>در این قسمت شما میبایست محدوده و آدرس ملک را مشخص نمایید</p>

                    <div class='row'>
                        <div class='col-md-6'>
                            <!--  ADD State ID !-->
                            <?php $form->renderDecorated('stateid'); ?> 

                            <!--  ADD City ID !-->
                            <?php $form->renderDecorated('cityid'); ?> 

                            <!--  ADD Address !-->
                            <?php $form->renderDecorated('address'); ?> 

                            <!--  ADD Private Address !-->
                            <?php $form->renderDecorated('private_address'); ?>
                        </div>
                        <div class='col-md-6'>
                            <!--  Map !-->
                            <?php $form->renderDecorated('map'); ?> 
                        </div>
                    </div>
                </div>
                <div class="panel-footer panel-footer-btn-group">
                    <div id="nextbtn" data-step="3" class="btn btn-primary">مرحله بعد</div>
                    <div id="backbtn" data-step="3" class="btn btn-default">مرحله قبل</div>
                </div>
            </div>


            <!--Gheymat !-->
            <div data-step="4" class="panel panel-default melk-step-panel">
                <div class="panel-heading">
                    <h3 class="panel-title">قیمت</h3>
                </div>
                <div class="panel-body">
                    <p> هزینه ای که برای فروش یا اجاره بر روی ملک گزاشتید را وارد نمایید </p>

                    <!--  ADD Sale Price !-->
                    <?php $form->renderDecorated('sale_price'); ?> 

                    <!--  ADD Ejare !-->
                    <?php $form->renderDecorated('rent_price'); ?> 

                    <!--  ADD Rahn !-->
                    <?php $form->renderDecorated('rent_pricerahn'); ?> 

                </div>
                <div class="panel-footer panel-footer-btn-group">
                    <div id="nextbtn" data-step="4" class="btn btn-primary">مرحله بعد</div>
                    <div id="backbtn" data-step="4" class="btn btn-default">مرحله قبل</div>
                </div>
            </div>


            <!-- Contact !-->
            <div data-step="5" class="panel panel-default melk-step-panel">
                <div class="panel-heading">
                    <h3 class="panel-title">اطلاعات تماس</h3>
                </div>
                <div class="panel-body">
                    <p>اطلاعات تماس مستقیم خودتان را وارد نمایید تا در صورت نیاز مشتریان بتوانند با شما تماس داشته باشند</p>


                    <!--  ADD Private Phone !-->
                    <?php $form->renderDecorated('private_phone'); ?> 

                    <!--  ADD Private Mobile !-->
                    <?php $form->renderDecorated('private_mobile'); ?> 


                </div>
                <div class="panel-footer panel-footer-btn-group">
                    <div id="nextbtn" data-step="5" class="btn btn-primary">مرحله بعد</div>
                    <div id="backbtn" data-step="5" class="btn btn-default">مرحله قبل</div>
                </div>
            </div>


            <!-- Images  !-->
            <div data-step="6" class="panel panel-default melk-step-panel" >
                <div class="panel-heading">
                    <h3 class="panel-title">تصاویر ملک</h3>
                </div>
                <div class="panel-body">
                    <p>برای افزایش بازدهی، شما میتوانید در صورت تمایل تعدادی تصویر را برای ملک خود ارائه نمایید</p>
                    <!--  Image !-->
                    <div class='row'>
                        <div class='col-md-6'>
                            <?php $form->renderDecorated('img1'); ?> 
                            <?php $form->renderDecorated('img3'); ?> 
                            <?php $form->renderDecorated('img5'); ?> 
                            <?php $form->renderDecorated('img7'); ?> 
                            <?php $form->renderDecorated('img9'); ?> 
                            <?php $form->renderDecorated('img11'); ?> 
                        </div>
                        <div class='col-md-6'>
                            <?php $form->renderDecorated('img2'); ?> 
                            <?php $form->renderDecorated('img4'); ?> 
                            <?php $form->renderDecorated('img6'); ?> 
                            <?php $form->renderDecorated('img8'); ?> 
                            <?php $form->renderDecorated('img10'); ?> 
                            <?php $form->renderDecorated('img12'); ?> 
                        </div>
                    </div>


                </div>
                <div class="panel-footer panel-footer-btn-group">
                    <div id="nextbtn" data-step="6" class="btn btn-primary">پایان</div>
                    <div id="backbtn" data-step="6" class="btn btn-default">مرحله قبل</div>
                </div>
            </div>


            <!-- Images  !-->
            <div data-step="7" class="panel panel-default melk-step-panel" >
                <div class="panel-heading">
                    <h3 class="panel-title">پایان</h3>
                </div>
                <div class="panel-body final-step">
                    <h3>برای ارسال نهایی ملک بر روی کلید ارسال کلیک نمایید</h3>
                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?> 
                </div>
                <div class="panel-footer panel-footer-btn-group">
                    <div id="backbtn" data-step="7" class="btn btn-default">مرحله قبل</div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>


    // hide all steps at start
    $(".melk-step-panel").hide();


    /**
     * this function will go to the requestd step without any validate
     * @param {type} newStep
     * @param {type} oldStep
     * @returns {undefined}
     */
    function showStep(newStep, oldStep)
    {
        // hide all steps at first time
        $(".melk-step-panel[data-step='" + oldStep + "']").fadeOut(250, function() {
            $(".melk-step-panel[data-step='" + newStep + "']").fadeIn(250);
        });

        // show in wizard mode
        $(".melk-wizard-step[data-step='" + oldStep + "']").removeClass('active').addClass("done");
        $(".melk-wizard-step[data-step='" + newStep + "']").addClass('active').removeClass("done");
    }

    /**
     * this function will ready step
     * @param {type} step
     * @returns {undefined}
     */
    function readyStep(step)
    {
        if (step == 2)
        {
            // get melk type
            console.log("type", $("#melktypeid").val());
            console.log("purpose", $("#melkpurposeid").val());

            // we have to show all optiosn first
            $("#lot_size_holder").show();
            $("#bedroom_holder").show();
            $("#bath_holder").show();
            $("#home_size_holder").show();

            switch ($("#melktypeid").val())
            {
                case "1":
                    // khane
                    break;
                case "2":
                    // aparteman
                    $("#lot_size_holder").hide();
                    break;
                case "3":
                    // daftar kar
                    $("#bath_holder").hide();
                    $("#lot_size_holder").hide();
                    break;
                case "4":
                    // vila
                    break;
                case "5":
                    // zamin
                    $("#bedroom_holder").hide();
                    $("#bath_holder").hide();
                    $("#home_size_holder").hide();
                    break;
                case "6":
                    // otaghe kar
                    $("#lot_size_holder").hide();
                    $("#bedroom_holder").hide();
                    $("#bath_holder").hide();
                    break;
                default:
                    // Type Is Not valid
                    alert("نوع ملک معتبر نمیباشد");
                    break;
            }


            // check for purpose
            switch ($("#melkpurposeid").val())
            {
                case "1":
                    // forosh
                    $("#sale_price_holder").show();
                    $("#rent_price_holder").hide();
                    $("#rent_pricerahn_holder").hide();
                    break;
                case "2":
                    // ejare
                    $("#sale_price_holder").hide();
                    $("#rent_price_holder").show();
                    $("#rent_pricerahn_holder").show();
                    break;
                case "3":
                    // forosh va ejare
                    $("#sale_price_holder").show();
                    $("#rent_price_holder").show();
                    $("#rent_pricerahn_holder").show();
                    break;
                default:
                    // Type Is Not valid
                    alert("منظور ملک معتبر نمیباشد");
                    break;
            }
        }


        if (step == 3)
        {

        }



        if (step == 4)
        {

        }


        if (step == 5)
        {

        }


        if (step == 6)
        {

        }
    }

    /**
     * this function will validate step
     * @param {type} step
     * @returns {undefined}
     */
    function validStep(step) {

        // step one is choose type and purpose
        if (step == 1)
        {
            return true;
        } else if (step == 2)
        {
            // step two is select information
        }


        return true;
    }


    // add event on next button click
    $('body').on('click', '#nextbtn', function() {
        // get step
        var currenctStep = $(this).data('step');
        if (validStep(currenctStep))
        {
            readyStep(currenctStep + 1);
            showStep(currenctStep + 1, currenctStep);
        }

    });
    // add event on next button click
    $('body').on('click', '#backbtn', function() {
        // get step
        var currenctStep = $(this).data('step');
        showStep(currenctStep - 1, currenctStep);
    });


    // show step 1
    showStep(1, 1);


</script>

