<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<section class='panel panel-danger'>
    <header class='panel-heading'>
        <h2 class='panel-title'>حذف ملک</h2>
    </header>
    <div class='panel-body'>
        <p>آیا برای حذف این ملک اطمینان دارید؟</p>
        <form method='post'>
            <input class='btn btn-danger' type='submit' name='delete' value='حذف' />
        </form>
    </div>
</section>