<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<script>
    window.saleValuesMap = [<?php echo implode(", ", $salePriceOptions); ?>];
    window.rahnValuesMap = [<?php echo implode(", ", $largePriceOptions); ?>];
    window.ejareValuesMap = [<?php echo implode(", ", $smallPriceOptions); ?>];

</script>    
<form method="post">
    <div class="panel panel-default" style="box-shadow: 0px 0px 6px #D0BFBF;">
        <div class="panel-heading">
            <h1 class="panel-title"><span class="glyphicon glyphicon-search"></span>جستجو در املاک <?php echo $cityName; ?></h1>
        </div>
        <div class="panel-body">
            <div class='col-md-12'>
                <div  class='row hidden'>
                    <div class='col-md-6'>
                        <?php $form->renderDecorated('stateid'); ?> 
                    </div>
                    <div class='col-md-6'>
                        <?php $form->renderDecorated('cityid'); ?> 
                    </div>
                </div>
                <hr class="hidden"/>
                <div class='row'>
                    <div class='row'>
                        <div class='col-md-6 col-xs-12 col-sm-12'>
                            <div class='row'>

                                <!-- Melk Type And Purpose -->
                                <div class="col-md-12">
                                    <div class='row'>
                                        <div class='col-md-6'>
                                            <div data-colname="melktypeid" >
                                                <?php $form->renderDecorated('melktypeid'); ?> 
                                            </div>
                                        </div>
                                        <div class='col-md-6'>
                                            <div data-colname="melkpurposeid" >
                                                <?php $form->renderDecorated('melkpurposeid'); ?> 
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <!-- Range Infos !-->
                                <div data-colname="bedroom_range" class='col-md-12'>
                                    <?php $form->renderDecorated('bedroom_range'); ?>
                                </div>

                                <div data-colname="sale_range" class='col-md-12'>
                                    <?php $form->renderDecorated('sale_range'); ?> 
                                </div>

                                <div data-colname="rahn_range" class='col-md-12'>
                                    <?php $form->renderDecorated('rahn_range'); ?> 
                                </div>

                                <div data-colname="ejare_range" class='col-md-12'>
                                    <?php $form->renderDecorated('ejare_range'); ?> 
                                </div>

                                <div  class='col-md-12'>
                                    <?php //$form->renderDecorated('address'); ?> 
                                </div>


                            </div>
                        </div>
                        <div class='col-md-3'>

                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="panel-footer search-footer">
            <div class='row'>
                <div class='col-md-3'>
                    <?php $form->renderDecorated('submit'); ?> 
                </div>
            </div>
        </div>
        <?php if (isset($showMobileForm)) : ?>
            <div class='row'>
                <div class='col-md-12'>
                    <div class="melk-subscribe-phone">
                        <div class="row">
                            <div class="col-md-8">
                                <p style="margin-top: 6px;margin-bottom: 0;"><span class="fa fa-mobile"></span> شماره تماس خود را وارد نمایید تا املاک جدید مطابق با جستجوی شما به رایگان توسط پیامک برای شما ارسال گردد</p>
                            </div>
                            <div class="col-md-4 melk-view-subscribe-box">
                                <div class="input-group">
                                    <input type="text" name="subscribephone" class="form-control" placeholder="شماره موبایل">
                                    <div class="input-group-btn">
                                        <input type="submit" name="search" class="btn btn-primary" value="دریافت">
                                    </div>
                                </div>
                            </div>
                        </div>  
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <div class='search-result-list'>
            <?php
            echo $list->table;
            echo $list->footer;
            ?>
        </div>
    </div>
</form>


<script>


    function onBedroomChange() {
        // get start
        var val = $("#bedroom_start").val();
        $.each($("#bedroom_end").children('option'), function(index, item) {
            $(item).show();
        });
        var selected = false;
        $.each($("#bedroom_end").children('option'), function(index, item) {
            if (index < val) {
                $(item).hide();
            } else
            {
                if (selected == false) {
                    selected = true;
                    $(item).attr('selected', 'selected');
                }
            }
        });
    }

    function onSaleStartChange() {
        // get start
        var val = parseInt($("#sale_price_start").val());
        $.each($("#sale_price_end").children('option'), function(index, item) {
            $(item).show();
        });
        var selected = false;
        $.each($("#sale_price_end").children('option'), function(index, item) {
            if (parseInt($(item).val()) < val) {
                $(item).hide();
            } else
            {
                if (selected == false) {
                    selected = true;
                    $(item).attr('selected', 'selected');
                }
            }

        });
    }

    function onEjareStartChange() {
        // get start
        var val = parseInt($("#rahn_pricerahn_start").val());
        $.each($("#rahn_pricerahn_end").children('option'), function(index, item) {
            $(item).show();
        });
        $.each($("#rahn_pricerahn_end").children('option'), function(index, item) {
            if (parseInt($(item).val()) < val) {
                $(item).hide();
            }
        });
    }


    function onRahnStartChange() {
        // get start
        var val = parseInt($("#rahn_price_start").val());
        $.each($("#rahn_price_end").children('option'), function(index, item) {
            $(item).show();
        });
        $.each($("#rahn_price_end").children('option'), function(index, item) {
            if (parseInt($(item).val()) < val) {
                $(item).hide();
            }
        });
    }

    function onPurposeChange() {
        $("div[data-colname='sale_range']").hide();

        $("div[data-colname='ejare_range']").hide();

        $("div[data-colname='rahn_range']").hide();


        switch ($("#melkpurposeid").val())
        {
            case "1":
                // forosh
                $("div[data-colname='sale_range']").show().focus();
                break;
            case "2":
                //  ejare
                $("div[data-colname='ejare_range']").show().focus();
                $("div[data-colname='rahn_range']").show();
                break;
            default:
                // Type Is Not valid
                alert("منظور ملک معتبر نمیباشد");
                break;
        }
    }

    function onMelkTypeChange() {
        // hide all fields 
        hideAll();

        switch ($("#melktypeid").val())
        {
            case "1":
                // khane
                $("div[data-colname='bedroom_range']").show();
                break;
            case "2":
                // aparteman
                $("div[data-colname='bedroom_range']").show();
                break;
            case "3":
                // daftar kar
                $("div[data-colname='bedroom_range']").show();
                break;
            case "4":
                // vila
                break;
            case "5":
                // zamin
                break;
            case "6":
                // otaghe kar
                $("div[data-colname='bedroom_range']").show();
                break;
            default:
                // Type Is Not valid
                alert("نوع ملک معتبر نمیباشد");
                break;
        }

    }

    function hideAll() {


        $("div[data-colname='bedroom_range']").hide();
    }

    $("#melkpurposeid").change(function() {
        onPurposeChange();
    });


    $("#melktypeid").change(function() {
        onMelkTypeChange();

        // focous on purpose
        $("#melkpurposeid").focus();
    });

    $("#bedroom_start").change(function() {
        onBedroomChange();
    });
    $("#sale_price_start").change(function() {
        onSaleStartChange();
    });

    onPurposeChange();
    onMelkTypeChange();

    $('#ui-slider-handle').draggable();

</script>