<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<script>
    window.saleValuesMap = [<?php echo implode(", ", $salePriceOptions); ?>];
    window.rahnValuesMap = [<?php echo implode(", ", $largePriceOptions); ?>];
    window.ejareValuesMap = [<?php echo implode(", ", $smallPriceOptions); ?>];

</script>    
<form method="post">


    <div class='row'>
        <!-- Right Panel !-->
        <div class='col-md-3'>
            <div>
                <!-- Search Box !-->
                <div class="panel panel-default melklist-search-box">
                    <div class="panel-heading">
                        <h3 class="panel-title"><span class="glyphicon glyphicon-search"></span>جستجو در املاک <?php echo $cityName; ?></h3>
                    </div>
                    <div class="panel-body">

                        <!-- State City !-->
                        <div class='row'>
                            <div class='col-md-6 col-xs-6'>
                                <?php $form->renderElement('stateid'); ?> 
                            </div>
                            <div class='col-md-6  col-xs-6'>
                                <?php $form->renderElement('cityid'); ?>
                            </div>
                        </div>

                        <div class='row'>
                            <div class='col-md-12  col-xs-6'>
                                <div data-colname="melktypeid" >
                                    <?php $form->renderElement('melktypeid'); ?> 
                                </div>
                            </div>
                            <div class='col-md-12 col-xs-6'>
                                <div data-colname="melkpurposeid" >
                                    <?php $form->renderElement('melkpurposeid'); ?> 
                                </div>
                            </div>
                        </div>


                        <div data-colname="bedroom_range">
                            <?php $form->renderDecorated('bedroom_range'); ?>
                        </div>
                        <div data-colname="sale_range">
                            <?php $form->renderDecorated('sale_range'); ?> 
                        </div>
                        <div data-colname="rahn_range">
                            <?php $form->renderDecorated('rahn_range'); ?> 
                        </div>
                        <div data-colname="ejare_range">
                            <?php $form->renderDecorated('ejare_range'); ?> 
                        </div>
                        <?php $form->renderDecorated('submit'); ?> 
                    </div>
                </div>

                <!-- Advertise !-->
                <?php if (count($cityBanner) > 0) : ?>
                    <div class="panel panel-default hidden-xs hidden-sm">
                        <div class="panel-heading">
                            <h3 class="panel-title">تبلیغات</h3>
                        </div>
                        <div class="panel-body city-banner-holder">
                            <div class='row'>
                                <?php foreach ($cityBanner as $item) : ?>
                                    <div class='col-md-12 center'>
                                        <div class="thumbnail city-banner-item">
                                            <div>
                                                <p class="title">مشاور املاک <?php echo $item->getUser()->getFirstBongah()->title; ?></p>
                                                <p class="description">مشاور املاک مناطق <?php echo $item->getUser()->getFirstBongah()->getSupporrtedLocationsNameAsString(); ?></p>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                        <div class="panel-footer">
                            <p class="center" style="margin-bottom: 0px;">
                                <a href="<?php echo $this->url->get("bongahbanneradvert/plans"); ?>">سفارش تبلیغ</a>
                            </p>
                        </div>
                    </div>
                <?php endif; ?>


                <!-- Tag Cloud !-->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">لینک های مفید</h3>
                    </div>
                    <div class="panel-body">
                        <?php echo $tagCloud; ?>
                    </div>
                </div>
            </div>

        </div>
        <!-- Box !-->
        <div class='col-md-9'>

            <!-- Request Phone Subscribe !-->
            <?php if (isset($showMobileForm)) : ?>
                <div class="panel panel-default fixme">
                    <div class="panel-body melk-subscribe-phone">
                        <div class='row'>
                            <div class='col-md-12'>
                                <div class="row holder">
                                    <div class="col-md-8 col-sm-8 col-xs-12">
                                        <div class="media">
                                            <span class="fa fa-mobile media-object pull-right" style="font-size: 60px;"></span>
                                            <div class="media-body">
                                                <p style="margin-top: 6px;margin-bottom: 0;"> شماره تماس خود را وارد نمایید تا املاک جدید مطابق با جستجوی شما به رایگان توسط پیامک برای شما ارسال گردد</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 col-sm-4  col-xs-12 melk-view-subscribe-box">
                                        <div class="input-group">
                                            <input type="text" name="subscribephone" class="form-control" placeholder="شماره موبایل">
                                            <div class="input-group-btn">
                                                <input type="submit" name="search" class="btn btn-primary" value="دریافت">
                                            </div>
                                        </div>
                                    </div>

                                </div>  
                            </div>
                        </div>
                    </div>
                </div>
            <?php endif; ?>

            <div class="panel panel-default">
                <div class="panel-heading" style="border-bottom: 0px;">
                    <h3 class="panel-title"> 
                        <span class="pull-right">املاک موجود</span>
                        <!-- Check For Tyoe !-->
                        <?php if ($viewType == "grid") : ?>
                            <a><span class="fa fa-list pull-left disabled melk-view-icon" data-type="list"></span></a>
                            <a><span class="fa fa-image pull-left melk-view-icon" data-type="grid"></span></a>
                        <?php else : ?>
                            <a><span class="fa fa-list pull-left  melk-view-icon" data-type="list"></span></a>
                            <a><span class="fa fa-image pull-left disabled melk-view-icon" data-type="grid"></span></a>
                        <?php endif; ?>
                        <div class="clearfix"></div> 
                    </h3>
                </div>
                <div class="panel-body" style="padding: 0px;">
                    <div class='search-result-list'>

                        <!-- Check For Tyoe !-->
                        <?php if ($viewType == "grid") : ?>

                            <!-- Grid Items !-->
                            <div style="padding: 15px;">
                                <div class='row'>
                                    <?php foreach ($list->items as $melk) : ?>
                                        <a style="color: inherit;" href="<?php echo $this->url->get("melk/view/$melk->id"); ?>">
                                            <div class='col-md-4'>
                                                <div class="thumbnail melk-item" data-toggle="popover"  data-trigger="hover"  title="اطلاعات ملک" data-content="<?php echo $melk->getQuickInfo(); ?>">
                                                    <div class="media">
                                                        <div class="media-object pull-left">
                                                            <img class="image" src="<?php echo $melk->getImageLink(); ?>"><br/>
                                                        </div>
                                                        <div class="media-body">
                                                            <h4 class="title media-heading"><?php echo $melk->getPurposeType(); ?>&nbsp;<?php echo $melk->getTypeName(); ?></h4>
                                                            <p class="blvd oneline"><?php echo $melk->getBlvd(); ?></p>
                                                            <p class="time timeago" data-time="<?php echo $melk->date; ?>"><?php echo $melk->getSimpleDate(); ?></p>
                                                        </div>
                                                    </div>
                                                </div> 
                                            </div>
                                        </a>
                                    <?php endforeach; ?>
                                </div>
                            </div>

                            <!-- Paginator !-->
                            <?php
                            echo $list->footer;
                            ?>
                        <?php else : ?>
                            <?php
                            echo $list->table;
                            echo $list->footer;
                            ?>
                        <?php endif; ?>

                    </div>
                </div>
            </div>
        </div>
    </div>
</form>


<script>


    function onBedroomChange() {
        // get start
        var val = $("#bedroom_start").val();
        $.each($("#bedroom_end").children('option'), function(index, item) {
            $(item).show();
        });
        var selected = false;
        $.each($("#bedroom_end").children('option'), function(index, item) {
            if (index < val) {
                $(item).hide();
            } else
            {
                if (selected == false) {
                    selected = true;
                    $(item).attr('selected', 'selected');
                }
            }
        });
    }

    function onSaleStartChange() {
        // get start
        var val = parseInt($("#sale_price_start").val());
        $.each($("#sale_price_end").children('option'), function(index, item) {
            $(item).show();
        });
        var selected = false;
        $.each($("#sale_price_end").children('option'), function(index, item) {
            if (parseInt($(item).val()) < val) {
                $(item).hide();
            } else
            {
                if (selected == false) {
                    selected = true;
                    $(item).attr('selected', 'selected');
                }
            }

        });
    }

    function onEjareStartChange() {
        // get start
        var val = parseInt($("#rahn_pricerahn_start").val());
        $.each($("#rahn_pricerahn_end").children('option'), function(index, item) {
            $(item).show();
        });
        $.each($("#rahn_pricerahn_end").children('option'), function(index, item) {
            if (parseInt($(item).val()) < val) {
                $(item).hide();
            }
        });
    }


    function onRahnStartChange() {
        // get start
        var val = parseInt($("#rahn_price_start").val());
        $.each($("#rahn_price_end").children('option'), function(index, item) {
            $(item).show();
        });
        $.each($("#rahn_price_end").children('option'), function(index, item) {
            if (parseInt($(item).val()) < val) {
                $(item).hide();
            }
        });
    }

    function onPurposeChange() {
        $("div[data-colname='sale_range']").hide();

        $("div[data-colname='ejare_range']").hide();

        $("div[data-colname='rahn_range']").hide();


        switch ($("#melkpurposeid").val())
        {
            case "1":
                // forosh
                $("div[data-colname='sale_range']").show().focus();
                break;
            case "2":
                //  ejare
                $("div[data-colname='ejare_range']").show().focus();
                $("div[data-colname='rahn_range']").show();
                break;
            default:
                // Type Is Not valid
                alert("منظور ملک معتبر نمی باشد");
                break;
        }
    }

    function onMelkTypeChange() {
        // hide all fields 
        hideAll();

        switch ($("#melktypeid").val())
        {
            case "1":
                // khane
                $("div[data-colname='bedroom_range']").show();
                break;
            case "2":
                // aparteman
                $("div[data-colname='bedroom_range']").show();
                break;
            case "3":
                // daftar kar
                $("div[data-colname='bedroom_range']").show();
                break;
            case "4":
                // vila
                break;
            case "5":
                // zamin
                break;
            case "6":
                // otaghe kar
                $("div[data-colname='bedroom_range']").show();
                break;
            default:
                // Type Is Not valid
                alert("نوع ملک معتبر نمی باشد");
                break;
        }

    }

    function hideAll() {


        $("div[data-colname='bedroom_range']").hide();
    }

    $("#melkpurposeid").change(function() {
        onPurposeChange();
    });


    $("#melktypeid").change(function() {
        onMelkTypeChange();

        // focous on purpose
        $("#melkpurposeid").focus();
    });

    $("#bedroom_start").change(function() {
        onBedroomChange();
    });
    $("#sale_price_start").change(function() {
        onSaleStartChange();
    });

    onPurposeChange();
    onMelkTypeChange();

    $('#ui-slider-handle').draggable();

    $(".melk-view-icon").click(function() {
        var type = $(this).data("type");
    });

</script>


<script>


    $(function() {
        function formatDate(dates) {
            dates.each(function() {
                //get date
                formattedDate = $(this).data('time');

                //format it
                moment.locale('fa');
                var d = new moment(new Date(formattedDate * 1000));
                
                //replace it
                $(this).html(d.fromNow());
            });
        }
        ;

        formatDate($('.timeago'));
    });


    function insertParam(key, value)
    {
        key = encodeURI(key);
        value = encodeURI(value);

        var s = document.location.search;
        var kvp = key + "=" + value;

        var r = new RegExp("(&|\\?)" + key + "=[^\&]*");

        s = s.replace(r, "$1" + kvp);

        if (!RegExp.$1) {
            s += (s.length > 0 ? '&' : '?') + kvp;
        }
        ;

        //again, do what you will here
        document.location.search = s;
    }

    $(".melk-view-icon").click(function() {
        var type = $(this).data("type");
        insertParam("melkviewtype", type);
    });


    $('.melk-item').popover({
        container: "body"
    });




//    $('.affixitem').affix({
//        offset: {
//            top: 100,
//            bottom: function() {
//                return (this.bottom = $('footer').outerHeight(true));
//            }
//        }
//    });
//
//
//    var fixmeTop = $('.fixme').offset().top;
//    $(window).scroll(function() {
//        var currentScroll = $(window).scrollTop();
//        if (currentScroll >= fixmeTop) {
//            $('.fixme').addClass('fixed-search-bar');
//        } else {
//            $('.fixme').removeClass('fixed-search-bar');
//        }
//    });
</script>