<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<div class='row'>
    <div class='col-md-12'>
        <h1>اضافه کردن ملک</h1>
        <hr/>
        <p>برای اضافه کردن ملک ابتدا باید عضو سایت شوی، در صورتی که قبلا در سایت ثبت نام کرده اید، از کلید ورود و در غیر این صورت از کلید ثبت نام استفاده نماییدد</p>
        <a class="btn btn-primary" href="<?php echo $this->url->get("user/login"); ?>">ورود</a>
        <a class="btn btn-success" href="<?php echo $this->url->get("user/register"); ?>">عضویت</a>
    </div>
</div>

