<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<?php if ($canRemove) : ?>
    <div class='row'>
        <div class='col-md-12'>
            <div class='alert alert-info'>
                <p> ملک شما به مدت <?php echo $validDate; ?> روز قابل نمایش است، در صورتی که قصد حذف این ملک را دارید، بر روی گزینه حذف کلیک نمایید</p>
                <a href="<?php echo $this->url->get("melk/delete/$melk->id"); ?>">حذف ملک</a>
            </div>
        </div>
    </div>
<?php endif; ?>
<div class='row'>
    <div class='col-lg-12'>
        <!-- Load Images !-->
        <div class='row'>
            <div class='col-md-4'>
                <!-- Quick Review !-->
                <div class="panel panel-success melk-quick-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">در یک نگاه</h3>
                    </div>
                    <div class="panel-body">
                        <!-- Melk Info !-->
                        <dl class="dl-horizontal">

                            <dt>کد ملک</dt>
                            <dd><?php echo $melk->id; ?></dd>

                            <dt>نوع ملک</dt>
                            <dd><?php echo $melk->getTypeName(); ?></dd>

                            <dt>منطقه</dt>
                            <dd><?php echo $melk->getInfo()->address; ?></dd>

                            <dt>منظور</dt>
                            <dd><?php echo $melk->getPurposeType(); ?></dd>

                            <dt>وضعیت</dt>
                            <dd><?php echo $melk->getCondiationType(); ?></dd>

                            <dt>شهر</dt>
                            <dd><?php echo $melk->getCityName(); ?></dd>

                            <dt>شماره تماس</dt>
                            <dd><?php echo $melk->getContactPhone(); ?></dd>
                            <hr/>
                            <?php switch ($melk->melktypeid) : case 1: ?>
                                    <!-- Khane !-->
                                    <dt>متراژ زمین</dt>
                                    <dd><?php echo $melk->getMetraj(); ?></dd>

                                    <dt>زیربنا</dt>
                                    <dd><?php echo $melk->getZirbana(); ?></dd>

                                    <dt>اتاق خواب</dt>
                                    <dd><?php echo $melk->bedroom; ?></dd>

                                    <dt>حمام</dt>
                                    <dd><?php echo $melk->bath; ?></dd>

                                    <?php break; ?>
                                <?php case 2: ?>
                                    <!-- Apartemant !-->
                                    <dt>زیربنا</dt>
                                    <dd><?php echo $melk->getZirbana(); ?></dd>

                                    <dt>اتاق خواب</dt>
                                    <dd><?php echo $melk->bedroom; ?></dd>

                                    <dt>حمام</dt>
                                    <dd><?php echo $melk->bath; ?></dd>
                                    <?php break; ?>
                                <?php case 3: ?>
                                    <!-- daftar kar !-->
                                    <dt>زیربنا</dt>
                                    <dd><?php echo $melk->getZirbana(); ?></dd>

                                    <dt>تعداد اتاق</dt>
                                    <dd><?php echo $melk->bedroom; ?></dd>
                                    <?php break; ?>
                                <?php case 4: ?>
                                    <!-- vila !-->
                                    <dt>متراژ زمین</dt>
                                    <dd><?php echo $melk->getMetraj(); ?></dd>

                                    <dt>زیربنا</dt>
                                    <dd><?php echo $melk->getZirbana(); ?></dd>

                                    <dt>اتاق خواب</dt>
                                    <dd><?php echo $melk->bedroom; ?></dd>

                                    <dt>حمام</dt>
                                    <dd><?php echo $melk->bath; ?></dd>
                                    <?php break; ?>
                                <?php case 5: ?>
                                    <!-- zamin !-->
                                    <dt>متراژ زمین</dt>
                                    <dd><?php echo $melk->getMetraj(); ?></dd>
                                    <?php break; ?>
                                <?php case 6: ?>
                                    <!-- otaghe kar !-->
                                    <dt>زیربنا</dt>
                                    <dd><?php echo $melk->getZirbana(); ?></dd>
                                    <?php break; ?>
                                <?php default : ?>
                                    <?php BaseSystemLog::init($item)->setTitle("Problem in View")->setMessage("Invalid Melk Type")->setIP($_SERVER["REMOTE_ADDR"])->setType(SystemLogType::Error)->create(); ?>
                                    <?php break; ?>
                            <?php endswitch; ?>

                            <hr/>

                            <!-- Purpose !-->
                            <?php switch ($melk->melkpurposeid) : case 1: ?>
                                    <!-- Sale !-->
                                    <dt>قیمت فروش</dt>
                                    <dd><?php echo $melk->getSalePrice(); ?></dd>
                                    <?php break; ?>
                                <?php case 2: ?>

                                    <dt>رهن</dt>
                                    <dd><?php echo $melk->getRahnPrice(); ?></dd>

                                    <!-- Rent !-->
                                    <dt>اجاره</dt>
                                    <dd><?php echo $melk->getEjarePrice(); ?></dd>
                                    <?php break; ?>
                                <?php case 3: ?>
                                    <!-- Sale AND Rent !-->
                                    <dt>قیمت فروش</dt>
                                    <dd><?php echo $melk->getSalePrice(); ?></dd>

                                    <dt>رهن</dt>
                                    <dd><?php echo $melk->getRahnPrice(); ?></dd>

                                    <dt>اجاره</dt>
                                    <dd><?php echo $melk->getEjarePrice(); ?></dd>

                                    <?php break; ?>
                                <?php default : ?>
                                    <?php BaseSystemLog::init($item)->setTitle("Problem in Purpose")->setMessage("Invalid Melk Porpuse")->setIP($_SERVER["REMOTE_ADDR"])->setType(SystemLogType::Error)->create(); ?>
                                    <?php break; ?>
                            <?php endswitch; ?>
                            <hr/>

                            <dt>ارائه شده توسط</dt>
                            <dd><?php echo $melk->getCreateByTilte(); ?></dd>

                            <dt>تاریخ</dt>
                            <dd><?php echo $melk->getDate(); ?></dd>

                        </dl>
                    </div>
                </div>

                <!-- Contact !-->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">تماس با مالک</h3>
                    </div>
                    <div class="panel-body">
                        <form method="post">
                            <?php $contactform->renderDecorated('name'); ?> 
                            <?php $contactform->renderDecorated('phone'); ?> 
                            <?php $contactform->renderDecorated('message'); ?> 
                            <?php $contactform->renderDecorated('submit'); ?> 
                        </form>
                    </div>
                </div>

            </div>
            <div class='col-md-8'>
                <!-- Images !-->
                <?php if ($melk->getImages()->count() > 0) : ?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">تصاویر ملک </h3>
                        </div>
                        <div class="panel-body">
                            <div id="slider" class="carousel slide" data-ride="carousel">
                                <!-- Indicators -->
                                <ol class="carousel-indicators">
                                    <?php $isFirst = true; ?>
                                    <?php foreach ($melk->getImages() as $image) : ?>
                                        <li data-target="#slider" data-slide-to="0" class="<?php
                                        if ($isFirst) {
                                            echo "active";
                                            $isFirst = false;
                                        }
                                        ?>">
                                        </li>
                                    <?php endforeach; ?>
                                </ol>

                                <!-- Wrapper for slides -->
                                <div class="carousel-inner">
                                    <?php $isFirst = true; ?>
                                    <?php foreach ($melk->getImages() as $image) : ?>
                                        <div class="item <?php
                                        if ($isFirst) {
                                            echo "active";
                                            $isFirst = false;
                                        }
                                        ?>">
                                            <img style="width: 100%;" src="<?php echo $image->getImage()->link; ?>">
                                        </div>
                                    <?php endforeach; ?>
                                </div>

                                <!-- Controls -->
                                <a class="left carousel-control" href="#slider" role="button" data-slide="prev">
                                    <span class="glyphicon glyphicon-chevron-left"></span>
                                </a>
                                <a class="right carousel-control" href="#slider" role="button" data-slide="next">
                                    <span class="glyphicon glyphicon-chevron-right"></span>
                                </a>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>


                <!-- Description !-->
                <?php if (isset($melk->getInfo()->description) && strlen($melk->getInfo()->description) > 0) : ?>
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">توضیحات</h3>
                        </div>
                        <div class="panel-body">
                            <?php echo $melk->getInfo()->description; ?>
                        </div>
                    </div>
                <?php endif; ?>


                <!-- Map !-->
                <div class="panel panel-default">
                    <div class="panel-heading">

                        <h3 class="panel-title"><i class="fa fa-map-marker"></i>موقعیت ملک</h3>
                    </div>
                    <div class="panel-body">
                        <?php $form->renderDecorated('map'); ?> 
                    </div>
                </div>

                <!-- Facilties -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">امکانات ملک</h3>
                    </div>
                    <div class="panel-body">
                        <div class='row'>
                            <?php $facilties = MelkFacilities::find(); ?>
                            <?php foreach ($facilties as $facilityItem) : ?>
                                <div class='col-md-3'>
                                    <p class='facility-item <?php echo $melk->hasFacility($facilityItem->id) ? "active" : "" ?>'><?php echo $melk->hasFacility($facilityItem->id) ? "<span class='glyphicon glyphicon-check'></span>" : "<span class='glyphicon glyphicon-unchecked'></span>" ?> <?php echo $facilityItem->name; ?></p>
                                </div>
                            <?php endforeach; ?>

                        </div>

                    </div>
                </div>
            </div>

        </div>
        <!-- Bongah Ha !-->
        <?php if ($melk->createby == 1) : ?>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">بنگاه ارائه کننده</h3>
                </div>
                <div class="panel-body">
                    <?php
                    $bongah = $melk->getBongah();
                    ?>
                    <div class='row'>
                        <div class='col-md-6'>
                            <dl class="dl-horizontal bongah-info">

                                <dt>کد بنگاه</dt>
                                <dd><?php echo $bongah->id; ?></dd>

                                <dt>نام بنگاه</dt>
                                <dd><?php echo $bongah->title; ?></dd>

                                <dt>مسئول بنگاه</dt>
                                <dd><?php echo $bongah->fname . " " . $bongah->lname; ?></dd>

                                <dt>شماره تلفن بنگاه</dt>
                                <dd><?php echo $bongah->phone; ?></dd>

                                <dt>شماره موبایل بنگاه</dt>
                                <dd><?php echo $bongah->mobile; ?></dd>

                            </dl>
                        </div>
                        <div class='col-md-6'>
                            <?php
                            //create map
                            $map = new MapElement("bongah_map");
                            $map->setLathitude($bongah->latitude);
                            $map->setLongtude($bongah->longitude);
                            $map->setZoom(13);
                            $map->setMarkDescription($bongah->title);
                            $map->setMarkTitle("موقعیت بنگاه");
                            echo $map;
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        <?php else : ?>
            <div class='row'>
                <div class='col-md-12'>
                    <h3>بنگاه های قابل مراجعه</h3>
                    <hr/>
                    <div class='row'>
                        <?php foreach ($bongahs as $bongah) : ?>
                            <div class='col-md-4'>
                                <div class="thumbnail">
                                    <h4><?php echo $bongah->title; ?> (<small>فاصله تا بنگاه : <?php echo sprintf("%.2f", $bongah->distance) . " کیلومتر"; ?></small>)</h4>
                                    <p style="margin-bottom: 0px;">آدرس: <?php echo $bongah->address; ?></p>
                                    <p>شماره تماس: <?php echo $bongah->phone; ?></p>
                                    <div>
                                        <?php
                                        $mapElement = new MapElement("bongah_" . $bongah->id);
                                        $mapElement->setLathitude($bongah->latitude);
                                        $mapElement->setLongtude($bongah->longitude);
                                        $mapElement->setName("melk");
                                        $mapElement->setZoom(14);
                                        $mapElement->setMarkTitle("بنگاه " . $bongah->title);
                                        $mapElement->setMarkDescription("بنگاه " . $bongah->title);
                                        echo $mapElement;
                                        ?>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                </div>
            </div>
        <?php endif; ?> 

    </div>
</div>


