<div class='row center'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div> 
</div>
<div class='row'>
    <div class='col-md-12'>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="fa fa-mobile-phone"></span>برنامه اختصاصی مشاوران املاک</h3>
            </div>
            <div class="panel-body">
                <div class='row'>
                    <div class='col-md-4 center'>
                        <img src="<?php echo $this->url->get("img/Amlak-Shoma.jpg"); ?>" class="img img-responsive img-rounded" />
                        <a class='btn btn-primary btn-block btn-lg hidden-lg hidden-md' href="<?php echo $this->url->get("index/downloadbongahapp"); ?>" style="margin-top: 16px;">دانلود برنامه</a>
                    </div>
                    <div class='col-md-8' style="font-family: naskh">
                        <h1>اولین برنامه تخصصی مشاوران املاک</h1>
                        <p>املاک گستر مفتخر است اولین برنامه اختصاصی اندروید، ویژه مشاوران املاک را ارائه دهد. از مزیت های این برنامه می توان به موارد زیر اشاره نمود.</p>
                        <ul class="app-download-description-holder">
                            <li>
                                <h3>دریافت روازنه مشتری</h3>
                                <p>با استفاده از سامانه املاک گستر، شما روزانه تعداد زیادی مشتری جدید دریافت خواهید نمود. سامانه با استفاده از الگوریتم های خود به هر مشتری امتیاز خواهد داد و شما قادر خواهید بود املاک مناسب خود برای هر مشتری را مشاهده نمایید<a href="<?php echo $this->url->get("index/downloadbongahapp"); ?>" >دانلود برنامه</a></p>
                            </li>
                            <li>
                                <h3>مدیریت املاک</h3>
                                <p>با استفاده از سامانه املاک گستر می توانید هم از طریق وب سایت و هم از طریق موبایل املاک خود را به سامانه اضافه نمایید. با استفاده از برنامه موبایل قادر خواهید بود تا همیشه لیست کاملی از املاک خود را به همراه داشته باشید.<a href="<?php echo $this->url->get("index/downloadbongahapp"); ?>" >دانلود برنامه</a></p>
                            </li>
                            <li>
                                <h3>جستجو در املاک</h3>
                                <p>دیگر نیازی به حضور همیشگی در مشاور املاک نیست. با استفاده از برنامه املاک گستر قادر خواهید بود در هر زمان که بخواهید، در املاک خود جستجو نمایید و نتایج جستجو را برای مشتری خود ارسال نمایید.<a href="<?php echo $this->url->get("index/downloadbongahapp"); ?>" >دانلود برنامه</a></p>
                            </li>
                            <li>
                                <h3>قابلیت افزدون آفلاین ملک</h3>
                                <p>در صورتی که در لحظه اضافه کردن ملک به اینترنت دسترسی نداشته باشید، اطلاعات ملک به صورت آفلاین ذخیره شده و در هنگام اتصال به اینترنت به صورت خودکار به سامانه ارسال می گردد<a href="<?php echo $this->url->get("index/downloadbongahapp"); ?>" >دانلود برنامه</a></p>
                            </li>
                            <li>
                                <h3>مشاهده اطلاعات املاک</h3>
                                <p>روزانه تعداد زیادی مشتری با استفاده از وبسایت www.amlakgostar.ir به دنبال ملک مورد نظر خود میگردند. املاکی که شما از طریق برنامه اضافه می نمایید تا در دسترس مشتریان قرار گیرد، به طور خودکار به وبسایت ارسال می گردید، همچنین اطلاعات مشاور املاک شما به عنوان بنگاه قابل مراجعه در سایت نمایش داده خواهد شد<a href="<?php echo $this->url->get("index/downloadbongahapp"); ?>" >دانلود برنامه</a></p>
                            </li>
                        </ul>
                         <a class='btn btn-primary btn-lg btn-block' href="<?php echo $this->url->get("index/downloadbongahapp"); ?>" style="margin-top: 16px;">دانلود برنامه</a>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>


