<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<?php if (isset($toSendBongahs) && count($toSendBongahs) > 0) : ?>
    <?php
    $namesArray = array();
    foreach ($toSendBongahs as $bongah) {
        $namesArray[] = "<span data-toggle='tooltip' data-placement='top' role='tooltip' title='$bongah->address'>" . $bongah->name . "</span>";
    }
    $namesArray = implode("، ", $namesArray);
    ?>
    <div class="alert alert-success send-melk-to-bongah-notice">
        <h1 style="margin-top: 0px;"><span class="fa fa-envelope"></span> ارسال ملک به مشاوران املاک</h1>
        <p>آیا می دانستید بدون مراجعه به مشاور املاک می توانید همین حالا، مشخصات ملک خود را به<?php echo " <b>" . count($toSendBongahs) . "</b>"; ?> مشاور املاک که در<?php echo "<b>" . $melk->getInfo()->address . "</b>"; ?> واقع هستند، ارسال نمایید! <br/>برای مشاهده آدرس هر مشاور املاک نشانگر ماوس را بر روی هر مشاور املاک نگه دارید.</p>
        <p class="addresses"><blockquote><?php echo $namesArray; ?></blockquote></p>
    <p>در صورت تمایل به ارسال اطلاعات ملک به مشاوران املاک، یکی از پلان های زیر را خریداری نمایید</p>
    </div>
    <script>
        $('span[role="tooltip"]').tooltip();
    </script>
<?php endif; ?>
<div class='row'>
    <div class='col-md-12'>
        <?php echo $plans; ?>
    </div>
</div>