<div class="row">
    <div class="col-md-12">
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method="post">
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">Website Info</h2>
                </header>
                <div class="panel-body">

                    <p>You can change website info here</p>

                    <!-- Offline !-->
                    <?php $siteInfoForm->renderDecorated("offline"); ?>

                    <!-- Offline Message !-->
                    <?php $siteInfoForm->renderDecorated("offlinemessage"); ?>

                    <!-- Submit Button !-->
                    <br/>
                    <?php $siteInfoForm->renderDecorated("submit"); ?>
                </div>
            </section>
        </div>
    </div>
</form>