<div class="row">
    <div class="col-md-12">
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method="post">
    <div class="row">
        <div class="col-lg-12">
            <section class="panel panel-success">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">Website Info</h2>
                </header>
                <div class="panel-body">

                    <p>You can change website info here</p>

                    <!-- Website Name !-->
                    <?php $siteInfoForm->renderDecorated("websitename"); ?>

                    <!-- Enable\Disable Signup Mode!-->
                    <?php $siteInfoForm->renderDecorated("enabledisablesignup"); ?>

                    <!-- Enable\Disable Signin Mode!-->
                    <?php $siteInfoForm->renderDecorated("enabledisablesignin"); ?>

                    <!-- Enable\Disable Search !-->
                    <?php $siteInfoForm->renderDecorated("enablesearch"); ?>

                    <!-- Enable\Disable RTL Support !-->
                    <?php $siteInfoForm->renderDecorated("rtl"); ?>

                    <!-- Recaptcha Public Key !-->
                    <?php $siteInfoForm->renderDecorated("recaptchapublic"); ?>

                    <!-- Recaptcha Private Key !-->
                    <?php $siteInfoForm->renderDecorated("recaptchaprivate"); ?>


                    <!-- Submit Button !-->
                    <br/>
                    <?php $siteInfoForm->renderDecorated("submit"); ?>
                </div>
            </section>
        </div>
    </div>
    <!-- SEO !-->
    <div class="row">
        <div class="col-lg-12">
            <section class="panel panel-info">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">SEO</h2>
                </header>
                <div class="panel-body">
                    <p>In order to change your search engine rank, you may define your SEO options right there</p>

                    <!-- keywords !-->
                    <?php $siteInfoForm->renderDecorated("keywords"); ?>

                    <!-- keywords !-->
                    <?php $siteInfoForm->renderDecorated("metadata"); ?>


                    <!-- Submit Button !-->
                    <br/>
                    <?php $siteInfoForm->renderDecorated("submit"); ?>
                </div>
            </section>
        </div>
    </div>
    <!-- Location !-->
    <div class="row">
        <div class="col-lg-12">
            <section class="panel panel-primary">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">Location</h2>
                </header>
                <div class="panel-body">
                    <p>You can define your location right there</p>

                    <!-- address !-->
                    <?php $siteInfoForm->renderDecorated("address"); ?>

                    <!-- email !-->
                    <?php $siteInfoForm->renderDecorated("email"); ?>

                    <!-- phone !-->
                    <?php $siteInfoForm->renderDecorated("phone"); ?>

                    <!-- latitude !-->
                    <?php $siteInfoForm->renderDecorated("latitude"); ?>

                    <!-- longtude !-->
                    <?php $siteInfoForm->renderDecorated("longtude"); ?>


                    <!-- Submit Button !-->
                    <br/>
                    <?php $siteInfoForm->renderDecorated("submit"); ?>
                </div>
            </section>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <section class="panel panel-dark">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">Analytics</h2>
                </header>
                <div class="panel-body">

                    <p>You may add your Website analytics code to this system</p>

                    <!-- Clicky Analytics!-->
                    <?php $siteInfoForm->renderDecorated("clickya"); ?>

                    <!-- Google Analytics!-->
                    <?php $siteInfoForm->renderDecorated("googlea"); ?>

                    <!-- Submit Button !-->
                    <br/>
                    <?php $siteInfoForm->renderDecorated("submit"); ?>
                </div>
            </section>
        </div>
    </div>

    <!-- Payment Recipet !-->
    <div class="row">
        <div class="col-lg-12">
            <section class="panel panel-dark">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">Payment Receipt</h2>
                </header>
                <div class="panel-body">
                    <p>What we should do when a user finish a payment</p>

                    <?php $siteInfoForm->renderDecorated("sendpaymentreceiptbyemail"); ?>

                    <?php $siteInfoForm->renderDecorated("sendpaymentreceiptbysms"); ?>

                    <!-- Submit Button !-->
                    <br/>
                    <?php $siteInfoForm->renderDecorated("submit"); ?>
                </div>
            </section>
        </div>
    </div>

    <!-- Phone Settings !-->
    <div class="row">
        <div class="col-lg-12">
            <section class="panel panel-dark">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">Phone Setting</h2>
                </header>
                <div class="panel-body">

                    <?php $siteInfoForm->renderDecorated("requestuserphoneonregister"); ?>

                    <?php $siteInfoForm->renderDecorated("requestverifiedphone"); ?>

                    <!-- Submit Button !-->
                    <br/>
                    <?php $siteInfoForm->renderDecorated("submit"); ?>
                </div>
            </section>
        </div>
    </div>


    <!-- News Settings !-->
    <div class="row">
        <div class="col-lg-12">
            <section class="panel panel-dark">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">News Setting</h2>
                </header>
                <div class="panel-body">

                    <div class='row'>
                        <div class='col-md-6'>
                            <?php $siteInfoForm->renderDecorated("shownews"); ?>
                        </div>
                        <div class='col-md-6'>
                            <?php $siteInfoForm->renderDecorated("shownewsandroid"); ?>
                        </div>
                    </div>

                    <?php $siteInfoForm->renderDecorated("globalmessage"); ?>

                    <!-- Submit Button !-->
                    <br/>
                    <?php $siteInfoForm->renderDecorated("submit"); ?>
                </div>
            </section>
        </div>
    </div>
</form>