<div class="row">
    <div class="col-md-12">
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method="post">
    <div class="row">
        <div class="col-lg-12">
            <section class="panel panel-success">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">Website Info</h2>
                </header>
                <div class="panel-body">

                    <p>You can change website info here</p>

                    <!-- Website Name !-->
                    <?php $siteInfoForm->renderDecorated("websitename"); ?>

                    <!-- Enable\Disable Signup Mode!-->
                    <?php $siteInfoForm->renderDecorated("enabledisablesignup"); ?>

                    <!-- Enable\Disable Signin Mode!-->
                    <?php $siteInfoForm->renderDecorated("enabledisablesignin"); ?>


                    <!-- Submit Button !-->
                    <br/>
                    <?php $siteInfoForm->renderDecorated("submit"); ?>
                </div>
            </section>
        </div>
    </div>
    <!-- SEO !-->
    <div class="row">
        <div class="col-lg-12">
            <section class="panel panel-info">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">SEO</h2>
                </header>
                <div class="panel-body">
                    <p>In order to change your search engine rank, you may define your SEO options right there</p>

                    <!-- keywords !-->
                    <?php $siteInfoForm->renderDecorated("keywords"); ?>

                    <!-- keywords !-->
                    <?php $siteInfoForm->renderDecorated("metadata"); ?>


                    <!-- Submit Button !-->
                    <br/>
                    <?php $siteInfoForm->renderDecorated("submit"); ?>
                </div>
            </section>
        </div>
    </div>
    <!-- Location !-->
    <div class="row">
        <div class="col-lg-12">
            <section class="panel panel-primary">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">Location</h2>
                </header>
                <div class="panel-body">
                    <p>You can define your location right there</p>

                    <!-- address !-->
                    <?php $siteInfoForm->renderDecorated("address"); ?>

                    <!-- email !-->
                    <?php $siteInfoForm->renderDecorated("email"); ?>

                    <!-- phone !-->
                    <?php $siteInfoForm->renderDecorated("phone"); ?>

                    <!-- latitude !-->
                    <?php $siteInfoForm->renderDecorated("latitude"); ?>

                    <!-- longtude !-->
                    <?php $siteInfoForm->renderDecorated("longtude"); ?>


                    <!-- Submit Button !-->
                    <br/>
                    <?php $siteInfoForm->renderDecorated("submit"); ?>
                </div>
            </section>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <section class="panel panel-dark">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">Analytics</h2>
                </header>
                <div class="panel-body">

                    <p>You may add your Website analytics code to this system</p>

                    <!-- Clicky Analytics!-->
                    <?php $siteInfoForm->renderDecorated("clickya"); ?>

                    <!-- Google Analytics!-->
                    <?php $siteInfoForm->renderDecorated("googlea"); ?>

                    <!-- Submit Button !-->
                    <br/>
                    <?php $siteInfoForm->renderDecorated("submit"); ?>
                </div>
            </section>
        </div>
    </div>
</form>