<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>ویرایش ملک درخواستی</h2>
                    <p class='panel-subtitle'Use this form to edit your MelkPhoneListner</p>
                </header>
                <div class='panel-body'>


                    <h4>نوع ملک</h4>
                    <hr/>
                    <div class='row'>
                        <div class='col-md-3'>
                            <!--  ADD Purpose ID !-->
                            <?php $form->renderDecorated('melkpurposeid'); ?> 
                        </div>
                        <div class='col-md-3'>
                            <!--  ADD Type ID !-->
                            <?php $form->renderDecorated('melktypeid'); ?> 
                        </div>
                        <div class='col-md-3'>
                            <!--  ADD City ID !-->
                            <?php $form->renderDecorated('cityid'); ?> 
                        </div>
                        <div class='col-md-3'>
                            <!--  ADD Status !-->
                            <?php $form->renderDecorated('status'); ?> 
                        </div>
                    </div>
                    <?php $form->renderDecorated('address'); ?> 


                    <h4>قیمت</h4>
                    <hr/>
                    <div class='row'>
                        <div class='col-md-6'>
                            <!--  ADD Bedroom Start !-->
                            <?php $form->renderDecorated('bedroom_start'); ?> 
                        </div>
                        <div class='col-md-6'>
                            <!--  ADD Bedroom End !-->
                            <?php $form->renderDecorated('bedroom_end'); ?> 
                        </div>
                        <div class='col-md-6'>
                            <!--  ADD Rent Price Start !-->
                            <?php $form->renderDecorated('rent_price_start'); ?> 
                        </div>
                        <div class='col-md-6'>

                            <!--  ADD Rent Price End !-->
                            <?php $form->renderDecorated('rent_price_end'); ?> 
                        </div>
                        <div class='col-md-6'>
                            <!--  ADD Rahn Start !-->
                            <?php $form->renderDecorated('rent_pricerahn_start'); ?> 
                        </div>
                        <div class='col-md-6'>
                            <!--  ADD Rahn End !-->
                            <?php $form->renderDecorated('rent_pricerahn_end'); ?> 
                        </div>
                        <div class='col-md-6'>
                            <!--  ADD Sale Start !-->
                            <?php $form->renderDecorated('sale_price_start'); ?> 
                        </div>
                        <div class='col-md-6'>
                            <!--  ADD Sale End !-->
                            <?php $form->renderDecorated('sale_price_end'); ?> 
                        </div>
                    </div>

                    <h4>اطلاعات تماس</h4>
                    <hr/>
                    <div class='row'>
                        <div class='col-md-4'>
                            <!--  ADD Phone ID !-->
                            <?php $form->renderDecorated('phoneid'); ?> 
                        </div>
                        <div class='col-md-4'>
                            <!--  ADD Received Count !-->
                            <?php $form->renderDecorated('receivedcount'); ?> 
                        </div>
                        <div class='col-md-4'>
                            <!--  ADD Date !-->
                            <?php $form->renderDecorated('date'); ?> 
                        </div>
                    </div>
                    <!-- Submit Button !-->
                    <br/>
                    <hr/>
                    <?php $form->renderDecorated('submit'); ?>
                    <hr/>
                    <?php
                    echo $list->header;
                    echo $list->table;
                    echo $list->footer;
                    ?>
                </div>
            </section>
        </div>
    </div>
</form>


