<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel panel-primary'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>View MelkPhoneListner</h2>
                                                <p class='panel-subtitle'Use this form to edit your MelkPhoneListner</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD ID !-->
                                <?php $form->renderInfo('id'); ?> 

                                <!--  ADD Purpose ID !-->
                                <?php $form->renderInfo('melkpurposeid'); ?> 

                                <!--  ADD Type ID !-->
                                <?php $form->renderInfo('melktypeid'); ?> 

                                <!--  ADD Bedroom Start !-->
                                <?php $form->renderInfo('bedroom_start'); ?> 

                                <!--  ADD Bedroom End !-->
                                <?php $form->renderInfo('bedroom_end'); ?> 

                                <!--  ADD Phone ID !-->
                                <?php $form->renderInfo('phoneid'); ?> 

                                <!--  ADD Received Count !-->
                                <?php $form->renderInfo('receivedcount'); ?> 

                                <!--  ADD Status !-->
                                <?php $form->renderInfo('status'); ?> 

                                <!--  ADD Rent Price Start !-->
                                <?php $form->renderInfo('rent_price_start'); ?> 

                                <!--  ADD Rent Price End !-->
                                <?php $form->renderInfo('rent_price_end'); ?> 

                                <!--  ADD Rahn Start !-->
                                <?php $form->renderInfo('rent_pricerahn_start'); ?> 

                                <!--  ADD Rahn End !-->
                                <?php $form->renderInfo('rent_pricerahn_end'); ?> 

                                <!--  ADD Sale Start !-->
                                <?php $form->renderInfo('sale_price_start'); ?> 

                                <!--  ADD Sale End !-->
                                <?php $form->renderInfo('sale_price_end'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderInfo('date'); ?> 

                                <!--  ADD City ID !-->
                                <?php $form->renderInfo('cityid'); ?> 


</div>
            </section>
        </div>
    </div>
</form>


