<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<div class='row'>
    <div class='col-md-8 col-md-push-2 moshaver-register-form'>
        <form method="post">

            <h3 style="margin-top: 10px;">اطلاعات مشاور</h3>
            <hr/>
            <div class='row'>
                <div class='col-md-6'>
                    <!--  ADD Moshaver Type !-->
                    <?php $form->renderDecorated('moshavertypeid'); ?> 
                </div>
                <div class='col-md-6'>
                    <!--  ADD Degree Type !-->
                    <?php $form->renderDecorated('degreetypeid'); ?> 
                </div>
            </div>

            <h3>موقعیت مشاور</h3>
            <hr/>

            <div class='row'>
                <div class='col-md-6'>
                    <!--  ADD State ID !-->
                    <?php $form->renderDecorated('stateid'); ?> 
                </div>
                <div class='col-md-6'>
                    <!--  ADD City ID !-->
                    <?php $form->renderDecorated('cityid'); ?> 
                </div>
            </div>

            <!--  ADD Address !-->
            <?php $form->renderDecorated('address'); ?> 

            <h3>اطلاعات تماس</h3>
            <hr/>
            <!--  ADD Phone !-->
            <?php $form->renderDecorated('phone'); ?> 

            <h3>اطلاعات عمومی</h3>
            <hr/>
            <!--  ADD Info !-->
            <?php $form->renderDecorated('info'); ?> 


            <!-- Submit Button !-->
            <br/>
            <?php $form->renderDecorated('submit'); ?>

        </form>
    </div>
</div>

<script>

    var citiesid = [];
    var cities = [];
<?php
foreach ($cities as $city) {
    echo "citiesid[$city->id] = \"$city->name\";\n";
    $ci = $city->getStateCitiesIDWithComma();
    echo "cities[$city->stateid] = \"$ci\";\n";
}
?>


    function onstatechange(selectedstate)
    {
        var ids = cities[selectedstate];
        var cityids = ids.split(",");
        // remove old cities
        var citylisteleemnt = $('#cityid');
        citylisteleemnt.find('option').remove().end();
        $.each(cityids, function(index, id) {
            if (index == 0)
            {
                oncitychange(citiesid[id]);
            }
            citylisteleemnt.append('<option value="' + id + '">' + citiesid[id] + '</option>');
        });
    }

    function locatteToAddress(address)
    {

    }

    function oncitychange(city)
    {
        var state = $("#stateid").find("option:selected").text();
        var address = "ایران، " + city;
        console.log(address);
        locatteToAddress(address);
    }

    $("#stateid").change(function() {
        onstatechange(this.value);
    });
    var addressChangeTimeOut = 0;
    $("#address").change(function() {

        clearTimeout(addressChangeTimeOut);
        addressChangeTimeOut = setTimeout(function() {
            var city = $("#cityid").find("option:selected").text();
            var address = $("#address").val();
            var address = "ایران، " + city + "،" + address;
            console.log(address);
            locatteToAddress(address);
        }, 150);
    });

    $("#cityid").change(function() {
        var city = citiesid[$(this).val()];
        oncitychange(city);
    });


</script>

