<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<div class='row'>
    <div class='col-md-3'>
    </div>

    <div class='col-md-6'>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">عضویت مشاور</h3>
            </div>
            <div class="panel-body">
                <form method="post">
                    
                    <!--  ADD City ID !-->
                    <?php $form->renderDecorated('cityid'); ?> 

                    <!--  ADD Address !-->
                    <?php $form->renderDecorated('address'); ?> 

                    <!--  ADD Phone !-->
                    <?php $form->renderDecorated('phone'); ?> 

                    <!--  ADD Moshaver Type !-->
                    <?php $form->renderDecorated('moshavertypeid'); ?> 

                    <!--  ADD Degree Type !-->
                    <?php $form->renderDecorated('degreetypeid'); ?> 

                    <!--  ADD Info !-->
                    <?php $form->renderDecorated('info'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>
                    
                </form>
            </div>
        </div>

    </div>

    <div class='col-md-3'>
    </div>
</div>