<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<div class='row'>
    <div class='col-md-8 col-md-push-2 moshaver-register-form'>
        <form method="post">

            <h3 style="margin-top: 10px;">اطلاعات مشاور</h3>
            <hr/>
            <div class='row'>
                <div class='col-md-6'>
                    <!--  ADD Moshaver Type !-->
                    <?php $form->renderDecorated('moshavertypeid'); ?> 
                </div>
                <div class='col-md-6'>
                    <!--  ADD Degree Type !-->
                    <?php $form->renderDecorated('degreetypeid'); ?> 
                </div>
            </div>

            <h3>موقعیت مشاور</h3>
            <hr/>

            <!--  ADD City ID !-->
            <?php $form->renderDecorated('cityid'); ?> 

            <!--  ADD Address !-->
            <?php $form->renderDecorated('address'); ?> 

            <h3>اطلاعات تماس</h3>
            <hr/>
            <!--  ADD Phone !-->
            <?php $form->renderDecorated('phone'); ?> 

            <h3>اطلاعات عمومی</h3>
            <hr/>
            <!--  ADD Info !-->
            <?php $form->renderDecorated('info'); ?> 


            <!-- Submit Button !-->
            <br/>
            <?php $form->renderDecorated('submit'); ?>

        </form>
    </div>
</div>