<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <ul class="list-unstyled moshaver-list">
            <?php foreach ($list->items as $moshaver) : ?>
                <li>
                    <div class="media moshaver-list-item">
                        <img src="<?php echo $moshaver->getUser()->getImageLink(); ?>" class="media-object pull-right img-rounded moshaver-image">
                        <div class="media-body pull-right">
                            <h3 class="media-heading name"><?php echo $moshaver->getUser()->getFullName(); ?></h3>
                            <p class="degree"><?php echo $moshaver->getDegreeName(); ?> <?php echo $moshaver->getTypeName(); ?></p>
                            <p class="address"><?php echo $moshaver->address; ?></p>
                        </div>
                        <div class="pull-left">
                            <a class="btn btn-primary view-btn" href="<?php echo $this->url->get("moshaver/view/$moshaver->id"); ?>">مشاهده پروفایل</a>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
        </ul>

        <!-- Pagination !-->
        <?php echo $list->footer; ?>
    </div>
</div>