<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<div class='row'>
    <div class='col-md-12'>
        <form method="post">

            <h2>اطلاعات مشاور</h2>
            <hr/>
            <div class='row'>
                <div class='col-md-6'>
                    <!--  ADD Moshaver Type !-->
                    <?php $form->renderDecorated('moshavertypeid'); ?> 
                </div>
                <div class='col-md-6'>
                    <!--  ADD Degree Type !-->
                    <?php $form->renderDecorated('degreetypeid'); ?> 
                </div>
            </div>

            <!--  ADD Info !-->
            <?php $form->renderDecorated('info'); ?> 


            <h2>اطلاعات تماس</h2>
            <hr/>
            <!--  ADD Phone !-->
            <?php $form->renderDecorated('phone'); ?> 



            <!--  ADD Address !-->
            <h2>موقعیت</h2>
            <hr/>
            <div class='row'>
                <div class='col-md-6'>
                    <!--  ADD State ID !-->
                    <?php $form->renderDecorated('stateid'); ?> 
                </div>
                <div class='col-md-6'>
                    <!--  ADD City ID !-->
                    <?php $form->renderDecorated('cityid'); ?> 
                </div>
            </div>
            <?php $form->renderDecorated('address'); ?> 

            <!--  ADD Map !-->
            <?php $form->renderDecorated('map'); ?> 

            <!-- Submit Button !-->
            <br/>
            <?php $form->renderDecorated('submit'); ?>
    </div>
</div>


<script>

    var citiesid = [];
    var cities = [];
<?php
foreach ($cities as $city) {
    echo "citiesid[$city->id] = \"$city->name\";\n";
    $ci = $city->getStateCitiesIDWithComma();
    echo "cities[$city->stateid] = \"$ci\";\n";
}
?>


    function onstatechange(selectedstate)
    {
        var ids = cities[selectedstate];
        var cityids = ids.split(",");
        // remove old cities
        var citylisteleemnt = $('#cityid');
        citylisteleemnt.find('option').remove().end();
        $.each(cityids, function(index, id) {
            if (index == 0)
            {
                oncitychange(citiesid[id]);
            }
            citylisteleemnt.append('<option value="' + id + '">' + citiesid[id] + '</option>');
        });
    }

    function locatteToAddress(address)
    {
        geocoder.geocode({'address': address}, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {
                $("#map_latitude").val(results[0].geometry.location.lat().toFixed(6)).trigger("change");
                $("#map_longitude").val(results[0].geometry.location.lng().toFixed(6)).trigger("change");
            } else {
                alert("Lat and long cannot be found.");
            }
        });
    }

    function oncitychange(city)
    {
        var state = $("#stateid").find("option:selected").text();
        var address = "ایران، " + city;
        console.log(address);
        locatteToAddress(address);
    }

    $("#stateid").change(function() {
        onstatechange(this.value);
    });
    var addressChangeTimeOut = 0;
    $("#address").change(function() {

        clearTimeout(addressChangeTimeOut);
        addressChangeTimeOut = setTimeout(function() {
            var city = $("#cityid").find("option:selected").text();
            var address = $("#address").val();
            var address = "ایران، " + city + "،" + address;
            console.log(address);
            locatteToAddress(address);
        }, 150);
    });
    var geocoder = new google.maps.Geocoder();
    $("#cityid").change(function() {
        var city = citiesid[$(this).val()];
        oncitychange(city);
    });


</script>

