<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<div class='row'>
    <div class='col-md-12'>
        <!-- Head !-->
        <div class="media moshaver-profile-item">
            <img src="<?php echo $moshaver->getUser()->getImageLink(); ?>" class="media-object pull-right img-rounded moshaver-image">
            <div class="media-body pull-right">
                <h1 class="media-heading name"><?php echo $moshaver->getUser()->getFullName(); ?></h1>
                <p class="degree"><?php echo $moshaver->getDegreeName(); ?> <?php echo $moshaver->getTypeName(); ?></p>
                <p class="address"><?php echo $moshaver->address; ?></p>
            </div>
            <div class="pull-left">
                <p class="phone"><?php echo $moshaver->phone; ?> <span class="fa fa-phone"></span></p>
                <p class="mobile"><?php echo $moshaver->phone; ?> <span class="fa fa-mobile-phone"></span></p>
            </div>
        </div>
        <hr/>
        <!-- Info !-->
        <h3>اطلاعات عمومی</h3>
        <p><?php echo $moshaver->info; ?></p>
        <hr/>
        <!-- Address !-->
        <h3>موقعیت</h3>
        <?php $form->renderDecorated('map'); ?> 
    </div>
</div>