<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>Edit Device</h2>
                                                <p class='panel-subtitle'Use this form to edit your Device</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD Company !-->
                                <?php $form->renderDecorated('company'); ?> 

                                <!--  ADD Category ID !-->
                                <?php $form->renderDecorated('categoryid'); ?> 

                                <!--  ADD Name !-->
                                <?php $form->renderDecorated('name'); ?> 

                                <!--  ADD Dimensions !-->
                                <?php $form->renderDecorated('dimensions'); ?> 

                                <!--  ADD Weight !-->
                                <?php $form->renderDecorated('weight'); ?> 

                                <!--  ADD Simcount !-->
                                <?php $form->renderDecorated('simcount'); ?> 

                                <!--  ADD Display !-->
                                <?php $form->renderDecorated('display'); ?> 

                                <!--  ADD Resolution !-->
                                <?php $form->renderDecorated('resolution'); ?> 

                                <!--  ADD SD Cart Support !-->
                                <?php $form->renderDecorated('sdsupport'); ?> 

                                <!--  ADD OS !-->
                                <?php $form->renderDecorated('os'); ?> 

                                <!--  ADD CPU !-->
                                <?php $form->renderDecorated('cpu'); ?> 

                                <!--  ADD GPU !-->
                                <?php $form->renderDecorated('gpu'); ?> 

                                <!--  ADD Internal_memory !-->
                                <?php $form->renderDecorated('internal_memory'); ?> 

                                <!--  ADD Camera !-->
                                <?php $form->renderDecorated('camera'); ?> 

                                <!--  ADD More Info !-->
                                <?php $form->renderDecorated('moreinfo'); ?> 


                                <!-- Submit Button !-->
                                <br/>
                                <?php $form->renderDecorated('submit'); ?>

</div>
            </section>
        </div>
    </div>
</form>


