<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>

                    <h2 class='panel-title'>افزودن مشخه جدید محصول</h2>
                </header>
                <div class='panel-body'>



                    <!--  ADD Product ID !-->
                    <?php $form->renderDecorated('productid'); ?> 

                    <!--  ADD Title !-->
                    <?php $form->renderDecorated('title'); ?> 

                    <!--  ADD Value !-->
                    <?php $form->renderDecorated('value'); ?> 

                    <!--  ADD Order ID !-->
                    <div class="hidden">
                        <?php $form->renderDecorated('orderid'); ?> 
                    </div>


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


