<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>Edit Charge</h2>
                                                <p class='panel-subtitle'Use this form to edit your Charge</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD User ID !-->
                                <?php $form->renderDecorated('userid'); ?> 

                                <!--  ADD Type !-->
                                <?php $form->renderDecorated('type'); ?> 

                                <!--  ADD Value !-->
                                <?php $form->renderDecorated('value'); ?> 

                                <!--  ADD Phone Number !-->
                                <?php $form->renderDecorated('phonenumber'); ?> 

                                <!--  ADD Target Phone Number !-->
                                <?php $form->renderDecorated('targetphonenumber'); ?> 

                                <!--  ADD Offline Mode !-->
                                <?php $form->renderDecorated('offlinemode'); ?> 

                                <!--  ADD Order ID !-->
                                <?php $form->renderDecorated('orderid'); ?> 

                                <!--  ADD Credit ID !-->
                                <?php $form->renderDecorated('creditid'); ?> 

                                <!--  ADD Elka Trans ID !-->
                                <?php $form->renderDecorated('elkatransid'); ?> 

                                <!--  ADD Cart ID !-->
                                <?php $form->renderDecorated('cartid'); ?> 

                                <!--  ADD Status !-->
                                <?php $form->renderDecorated('status'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderDecorated('date'); ?> 


                                <!-- Submit Button !-->
                                <br/>
                                <?php $form->renderDecorated('submit'); ?>

</div>
            </section>
        </div>
    </div>
</form>


