<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel panel-primary'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>View Charge</h2>
                                                <p class='panel-subtitle'Use this form to edit your Charge</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD ID !-->
                                <?php $form->renderInfo('id'); ?> 

                                <!--  ADD User ID !-->
                                <?php $form->renderInfo('userid'); ?> 

                                <!--  ADD Type !-->
                                <?php $form->renderInfo('type'); ?> 

                                <!--  ADD Value !-->
                                <?php $form->renderInfo('value'); ?> 

                                <!--  ADD Phone Number !-->
                                <?php $form->renderInfo('phonenumber'); ?> 

                                <!--  ADD Target Phone Number !-->
                                <?php $form->renderInfo('targetphonenumber'); ?> 

                                <!--  ADD Offline Mode !-->
                                <?php $form->renderInfo('offlinemode'); ?> 

                                <!--  ADD Order ID !-->
                                <?php $form->renderInfo('orderid'); ?> 

                                <!--  ADD Credit ID !-->
                                <?php $form->renderInfo('creditid'); ?> 

                                <!--  ADD Elka Trans ID !-->
                                <?php $form->renderInfo('elkatransid'); ?> 

                                <!--  ADD Cart ID !-->
                                <?php $form->renderInfo('cartid'); ?> 

                                <!--  ADD Status !-->
                                <?php $form->renderInfo('status'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderInfo('date'); ?> 


</div>
            </section>
        </div>
    </div>
</form>


