<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>View Image</h2>
                    <p class='panel-subtitle'Use this form to edit your Image</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD ID !-->
                    <?php $form->renderInfo('id'); ?> 

                    <!--  ADD Path !-->
                    <?php $form->renderInfo('path'); ?> 

                    <!--  ADD Date !-->
                    <?php $form->renderInfo('date'); ?> 

                    <!--  ADD Mime Type !-->
                    <?php $form->renderInfo('mimetype'); ?> 

                    <!--  ADD File Size !-->
                    <?php $form->renderInfo('filesize'); ?> 


                </div>
            </section>
        </div>
    </div>
</form>


