<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>

                    <h2 class='panel-title'>Add UserPost</h2>
                </header>
                <div class='panel-body'>

                    <div class='row'>
                        <div class='col-md-6'>
                            <!--  ADD Post ID !-->
                            <?php $form->renderDecorated('postid'); ?> 
                        </div>
                        <div class='col-md-6'>
                            <?php $form->renderDecorated('phonenumber'); ?> 
                        </div>
                    </div>
                    
                    <!--  ADD Code !-->
                    <?php $form->renderDecorated('code'); ?> 

                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


