<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel panel-default'>
                <header class='panel-heading'>
                    <h2 class='panel-title'>افزودن سمت کاربر</h2>
                </header>
                <div class='panel-body'>

                    <div class='row'>
                        <div class='col-md-6'>
                            <!--  ADD Post ID !-->
                            <?php $form->renderDecorated('postid'); ?> 
                        </div>
                        <div class='col-md-6'>
                            <?php $form->renderDecorated('phonenumber'); ?> 
                        </div>
                    </div>
                    
                    <!--  ADD Code !-->
                    <?php $form->renderDecorated('code'); ?> 

                    <hr>
                    <!-- Submit Button !-->
                    <div class="row">
                        <div class="col-sm-4"><?php $form->renderDecorated('submit'); ?></div>
                        <div class="col-sm-4"></div>
                        <div class="col-sm-4">
                            <a href="<?php echo $this->url->get("organ/$organId/users/") ?>" class="btn btn-info pull-left">بازگشت</a>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</form>


