<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<section class='panel panel-danger'>
    <header class='panel-heading'>
        <h2 class='panel-title'>حذف کاربر</h2>
    </header>
    <div class='panel-body'>
        <p>آیا از حذف کاربر اطمینان دارید؟</p>
        <form method='post'>
            <hr>
            <!-- Submit Button !-->
            <div class="row">
                <div class="col-sm-4"><input class='btn btn-danger' type='submit' name='delete' value='بله' /></div>
                <div class="col-sm-4"></div>
                <div class="col-sm-4">
                    <a href="<?php echo $this->url->get("organ/$organId/users/") ?>" class="btn btn-info pull-left">خیر</a>
                    <div class="clearfix"></div>
                </div>
            </div>
        </form>
    </div>
</section>