<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel panel-primary'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>View MelkSubscribeItem</h2>
                                                <p class='panel-subtitle'Use this form to edit your MelkSubscribeItem</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD ID !-->
                                <?php $form->renderInfo('id'); ?> 

                                <!--  ADD Name !-->
                                <?php $form->renderInfo('name'); ?> 

                                <!--  ADD Description !-->
                                <?php $form->renderInfo('description'); ?> 

                                <!--  ADD Melk Can Add !-->
                                <?php $form->renderInfo('melkscanadd'); ?> 

                                <!--  ADD Price !-->
                                <?php $form->renderInfo('price'); ?> 

                                <!--  ADD Valid Date !-->
                                <?php $form->renderInfo('validdate'); ?> 

                                <!--  ADD Send SMS to Users !-->
                                <?php $form->renderInfo('sendmessagetousers'); ?> 

                                <!--  ADD Featured !-->
                                <?php $form->renderInfo('featured'); ?> 

                                <!--  ADD Enable !-->
                                <?php $form->renderInfo('enable'); ?> 


</div>
            </section>
        </div>
    </div>
</form>


