<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel panel-primary'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>View BongahAmlakKeshvar</h2>
                                                <p class='panel-subtitle'Use this form to edit your BongahAmlakKeshvar</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD ID !-->
                                <?php $form->renderInfo('id'); ?> 

                                <!--  ADD State !-->
                                <?php $form->renderInfo('state'); ?> 

                                <!--  ADD City !-->
                                <?php $form->renderInfo('city'); ?> 

                                <!--  ADD Name !-->
                                <?php $form->renderInfo('name'); ?> 

                                <!--  ADD Code !-->
                                <?php $form->renderInfo('code'); ?> 

                                <!--  ADD Phone !-->
                                <?php $form->renderInfo('phone'); ?> 

                                <!--  ADD Mobile !-->
                                <?php $form->renderInfo('mobile'); ?> 

                                <!--  ADD Address !-->
                                <?php $form->renderInfo('address'); ?> 

                                <!--  ADD City ID !-->
                                <?php $form->renderInfo('cityid'); ?> 

                                <!--  ADD State ID !-->
                                <?php $form->renderInfo('stateid'); ?> 


</div>
            </section>
        </div>
    </div>
</form>


