<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>Edit Sentsms</h2>
                    <p class='panel-subtitle'Use this form to edit your Sentsms</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD Phone !-->
                    <?php $form->renderDecorated('phone'); ?> 

                    <!--  ADD Message !-->
                    <?php $form->renderDecorated('message'); ?> 

                    <!--  ADD From Number !-->
                    <?php $form->renderDecorated('fromnumber'); ?> 

                    <!--  ADD IP !-->
                    <?php $form->renderDecorated('ip'); ?> 

                    <!--  ADD Provider !-->
                    <?php $form->renderDecorated('provider'); ?> 

                    <!--  ADD Date !-->
                    <?php $form->renderDecorated('date'); ?> 

                    <!--  ADD Result !-->
                    <?php $form->renderDecorated('result'); ?> 

                    <!--  ADD Reference Code !-->
                    <?php $form->renderDecorated('refcode'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


