<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel panel-primary'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>View Sentsms</h2>
                    <p class='panel-subtitle'Use this form to edit your Sentsms</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD ID !-->
                    <?php $form->renderInfo('id'); ?> 

                    <!--  ADD Phone !-->
                    <?php $form->renderInfo('phone'); ?> 

                    <!--  ADD Message !-->
                    <?php $form->renderInfo('message'); ?> 

                    <!--  ADD From Number !-->
                    <?php $form->renderInfo('fromnumber'); ?> 

                    <!--  ADD IP !-->
                    <?php $form->renderInfo('ip'); ?> 

                    <!--  ADD Provider !-->
                    <?php $form->renderInfo('provider'); ?> 

                    <!--  ADD Date !-->
                    <?php $form->renderInfo('date'); ?> 

                    <!--  ADD Result !-->
                    <?php $form->renderInfo('result'); ?> 

                    <!--  ADD Reference Code !-->
                    <?php $form->renderInfo('refcode'); ?> 


                </div>
            </section>
        </div>
    </div>
</form>


