<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>Edit UserNotification</h2>
                    <p class='panel-subtitle'Use this form to edit your UserNotification</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD User ID !-->
                    <?php $form->renderDecorated('userid'); ?> 

                    <!--  ADD Title !-->
                    <?php $form->renderDecorated('title'); ?> 

                    <!--  ADD Message !-->
                    <?php $form->renderDecorated('message'); ?> 

                    <!--  ADD Link !-->
                    <?php $form->renderDecorated('link'); ?> 

                    <!--  ADD Link Text !-->
                    <?php $form->renderDecorated('linktext'); ?> 

                    <!--  ADD Date !-->
                    <?php $form->renderDecorated('date'); ?> 

                    <!--  ADD Release Date !-->
                    <?php $form->renderDecorated('releasedate'); ?> 

                    <!--  ADD Enable !-->
                    <?php $form->renderDecorated('enable'); ?> 

                    <!--  ADD By IP !-->
                    <?php $form->renderDecorated('byip'); ?> 

                    <!--  ADD Visited !-->
                    <?php $form->renderDecorated('visited'); ?> 

                    <!--  ADD Visit IP !-->
                    <?php $form->renderDecorated('visitip'); ?> 

                    <!--  ADD Visit Date !-->
                    <?php $form->renderDecorated('visitdate'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


