<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>

                    <h2 class='panel-title'>افزودن تخفیف جدید</h2>
                </header>
                <div class='panel-body'>

                    <h3>موضوع تخفیف</h3>
                    <p>در زیر شما می توانید موضوع تخفیف خود را مشخص نمایید، موضوع تخفیف به شما کمک می کنید که در میان تخفیفات در حال اجرا سریعتر جستجو نمایید</p>

                    <div class="row">
                        <div class="col-md-6 col-md-offset-6">
                            <!--  ADD Title !-->
                            <?php $form->renderDecorated('title'); ?> 
                        </div>
                    </div>

                    <h3>محدودیت سفارش</h3>
                    <p>در صورتی که قصد دارید محصولات این تخفیف دارای محدودیت زمانی خاصی باشند، فیلد مدت زمان را مشخص نمایید. در صورتی که قصد دارید تعداد خاصی از محصولات بفروش رسد، فیلد تعداد را پر نمایید.</p>
                    <div class="row">
                        <div class="col-md-6">
                            <!--  ADD End Date !-->
                            <?php $form->renderDecorated('end_date'); ?> 
                        </div>
                        <div class="col-md-6">
                            <!--  ADD Total !-->
                            <?php $form->renderDecorated('total'); ?> 
                        </div>
                    </div>

                    <h3>تخفیفات پیش فرض</h3>
                    <p>در کادر های زیر یکی از فیلد های درصد یا میزان تخفیف را پر نمایید.</p>
                    <blockquote>توجه داشته باشید که مقدار زیر تنها در هنگام افزودن محصول جدید در لیست تخفیفات اعمال خواهد شد و هیچ تاییزی برقیمت نهایی محصولات ندارند</blockquote>

                    <div class="row">
                        <div class="col-md-6">

                            <!--  ADD Default Percent !-->
                            <?php $form->renderDecorated('default_percent'); ?> 
                        </div>
                        <div class="col-md-6">
                            <!--  ADD Default Fee !-->
                            <?php $form->renderDecorated('default_fee'); ?> 
                        </div>
                    </div>

                    <h3>وضعیت تخفیف را در زیر مشخص نمایید</h3>

                    <!--  ADD Status !-->
                    <?php $form->renderDecorated('status'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


