<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel panel-primary'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>View BongahSentMessage</h2>
                                                <p class='panel-subtitle'Use this form to edit your BongahSentMessage</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD ID !-->
                                <?php $form->renderInfo('id'); ?> 

                                <!--  ADD Bongah ID !-->
                                <?php $form->renderInfo('bongahid'); ?> 

                                <!--  ADD Bongah Title !-->
                                <?php $form->renderInfo('bongahtitle'); ?> 

                                <!--  ADD To Phone !-->
                                <?php $form->renderInfo('tophone'); ?> 

                                <!--  ADD Message !-->
                                <?php $form->renderInfo('message'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderInfo('date'); ?> 

                                <!--  ADD SMS Message ID !-->
                                <?php $form->renderInfo('smsmessageid'); ?> 

                                <!--  ADD Received !-->
                                <?php $form->renderInfo('received'); ?> 

                                <!--  ADD Bongah Phone !-->
                                <?php $form->renderInfo('bongahphone'); ?> 

                                <!--  ADD Distance !-->
                                <?php $form->renderInfo('distance'); ?> 

                                <!--  ADD Type !-->
                                <?php $form->renderInfo('type'); ?> 


</div>
            </section>
        </div>
    </div>
</form>


