<div class='row'>
    <div class='col-md-6'>
        <h1>Add Your Opinion</h1>
        <hr/>
        <?php echo $this->getContent(); ?>
        <form method="post">
            <!-- Name !-->
            <?php echo $form->renderDecorated('name'); ?>

            <!-- Email !-->
            <?php echo $form->renderDecorated('email'); ?>

            <!-- Rate !-->
            <?php echo $form->renderDecorated('rate'); ?>

            <!-- Message !-->
            <?php echo $form->renderDecorated('message'); ?>

            <!-- Submit !-->
            <?php echo $form->renderDecorated('submit'); ?>
        </form>
    </div>
    <div class='col-md-6'>
        <h1>People Opinions</h1>
        <hr/>
        <?php foreach ($opinions as $opinion): ?>
            <div class='_opinion-item'>
                <h3 class='_name'><?= $opinion->name; ?></h3>
                <p class='_message'><?= $opinion->message; ?></p>
                <p class='_date'><?= $opinion->getDate(); ?></p>
            </div>
        <?php endforeach; ?>
    </div>
</div>