<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post' enctype="multipart/form-data">
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>

                    <h2 class='panel-title'>افزودن</h2>
                </header>
                <div class='panel-body'>

                    <h3>اطلاعات کلی</h3>

                    <!--  ADD نام !-->
                    <?php $form->renderDecorated('name'); ?> 

                    <!--  ADD توضیحات !-->
                    <?php $form->renderDecorated('description'); ?> 

                    <hr/>

                    <p>آیا اعتبار کاربر با این مورد افزایش می یابدp>

                    <!--  ADD افزایشی !-->
                    <?php $form->renderDecorated('increase'); ?> 

                    <p>آیا اعتبار کاربر با این مورد افزایش می یابد؟</p>

                    <!--  ADD هدیه می باشد !-->
                    <?php $form->renderDecorated('isgift'); ?> 

                    <hr/>
                    <h3>تصویر</h3>
                    <p>در صورتی که برای کاربر تصویری می بایست نمایش داده شود این مورد را مشخص نمایید</p>
                    
                    <!--  ADD تصویر !-->
                    <?php $form->renderDecorated('imageid'); ?> 
                    
                    
                     <!--  ADD تصویر !-->
                    <?php $form->renderDecorated('amount'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


