<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel panel-primary'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>View Page</h2>
                                                <p class='panel-subtitle'Use this form to edit your Page</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD ID !-->
                                <?php $form->renderInfo('id'); ?> 

                                <!--  ADD Key !-->
                                <?php $form->renderInfo('key'); ?> 

                                <!--  ADD Title !-->
                                <?php $form->renderInfo('title'); ?> 

                                <!--  ADD Text !-->
                                <?php $form->renderInfo('text'); ?> 

                                <!--  ADD Metadata Tags !-->
                                <?php $form->renderInfo('metakey'); ?> 

                                <!--  ADD Metadata Description !-->
                                <?php $form->renderInfo('metadata'); ?> 

                                <!--  ADD Show In Header !-->
                                <?php $form->renderInfo('showinhead'); ?> 

                                <!--  ADD Footer Text !-->
                                <?php $form->renderInfo('footer'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderInfo('date'); ?> 


</div>
            </section>
        </div>
    </div>
</form>


