<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel panel-primary'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>View Advertise</h2>
                                                <p class='panel-subtitle'Use this form to edit your Advertise</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD ID !-->
                                <?php $form->renderInfo('id'); ?> 

                                <!--  ADD User ID !-->
                                <?php $form->renderInfo('userid'); ?> 

                                <!--  ADD IP !-->
                                <?php $form->renderInfo('ip'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderInfo('date'); ?> 

                                <!--  ADD Device ID !-->
                                <?php $form->renderInfo('deviceid'); ?> 

                                <!--  ADD Current View !-->
                                <?php $form->renderInfo('currentview'); ?> 

                                <!--  ADD Repaired !-->
                                <?php $form->renderInfo('repaired'); ?> 

                                <!--  ADD Haveholder !-->
                                <?php $form->renderInfo('haveholder'); ?> 

                                <!--  ADD Price !-->
                                <?php $form->renderInfo('price'); ?> 

                                <!--  ADD Garantee !-->
                                <?php $form->renderInfo('garantee'); ?> 

                                <!--  ADD More Accecories !-->
                                <?php $form->renderInfo('moreacc'); ?> 

                                <!--  ADD Visit Time !-->
                                <?php $form->renderInfo('visittime'); ?> 

                                <!--  ADD Image ID !-->
                                <?php $form->renderInfo('imageid'); ?> 


</div>
            </section>
        </div>
    </div>
</form>


