<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>

<!-- User Charts !-->
<!--<div class="row">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <a href="#" class="fa fa-caret-down"></a>
                    <a href="#" class="fa fa-times"></a>
                </div>

                <h2 class="panel-title">ثبت نام در برنامه</h2>
                <p class="panel-subtitle">تعداد ثبت نام در برنامه</p>
            </header>
            <div class="panel-body">
<?php $form->renderDecorated('registerchart'); ?> 
            </div>
        </section>
    </div>

</div>-->

<div class="row">
    <!-- Total Users !-->
    <div class="col-md-12 col-lg-6 col-xl-6">
        <section class="panel panel-featured-left panel-featured-quartenary">
            <div class="panel-body">
                <div class="widget-summary">
                    <div class="widget-summary-col widget-summary-col-icon">
                        <div class="summary-icon bg-quartenary">
                            <i class="fa fa-user"></i>
                        </div>
                    </div>
                    <div class="widget-summary-col">
                        <div class="summary">
                            <h4 class="title">تعداد کاربران</h4>
                            <div class="info">
                                <strong class="amount"><?php echo $totalUsers ?></strong>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>


    <div class="col-md-12 col-lg-6 col-xl-6">
        <section class="panel panel-featured-left panel-featured-quartenary">
            <div class="panel-body">
                <div class="widget-summary">
                    <div class="widget-summary-col widget-summary-col-icon">
                        <div class="summary-icon bg-success">
                            <i class="fa fa-inbox"></i>
                        </div>
                    </div>
                    <div class="widget-summary-col">
                        <div class="summary">
                            <h4 class="title">تعداد اگهی ها</h4>
                            <div class="info">
                                <strong class="amount"><?php echo $totalads ?></strong>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>


    <div class="col-md-12 col-lg-6 col-xl-6">
        <section class="panel panel-featured-left panel-featured-quartenary">
            <div class="panel-body">
                <div class="widget-summary">
                    <div class="widget-summary-col widget-summary-col-icon">
                        <div class="summary-icon bg-primary">
                            <i class="fa fa-image"></i>
                        </div>
                    </div>
                    <div class="widget-summary-col">
                        <div class="summary">
                            <h4 class="title">آگهی های در انتظار تایید</h4>
                            <div class="info">
                                <strong class="amount"><?php echo $totalwairingads ?></strong>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <div class="col-md-12 col-lg-6 col-xl-6">
        <section class="panel panel-featured-left panel-featured-quartenary">
            <div class="panel-body">
                <div class="widget-summary">
                    <div class="widget-summary-col widget-summary-col-icon">
                        <div class="summary-icon bg-quartenary">
                            <i class="fa fa-mobile"></i>
                        </div>
                    </div>
                    <div class="widget-summary-col">
                        <div class="summary">
                            <h4 class="title">تعداد دستگاه ها</h4>
                            <div class="info">
                                <strong class="amount"><?php echo $totaldevice ?></strong>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Total Contacts !-->
    <!--    <div class="col-md-12 col-lg-6 col-xl-6">
            <section class="panel panel-featured-left panel-featured-primary">
                <div class="panel-body">
                    <div class="widget-summary">
                        <div class="widget-summary-col widget-summary-col-icon">
                            <div class="summary-icon bg-primary">
                                <i class="fa fa-life-ring"></i>
                            </div>
                        </div>
                        <div class="widget-summary-col">
                            <div class="summary">
                                <h4 class="title">Support Questions</h4>
                                <div class="info">
                                    <strong class="amount"><?php echo $totalContacts; ?></strong>
                                    <span class="text-primary">(<?php echo $totalContactsUnanswered; ?> unanswered)</span>
                                </div>
                            </div>
                            <div class="summary-footer">
                                <a class="text-muted text-uppercase">(view all)</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>-->

    <!-- Total Opinions !-->
    <!--    <div class="col-md-12 col-lg-6 col-xl-6">
            <section class="panel panel-featured-left panel-featured-primary">
                <div class="panel-body">
                    <div class="widget-summary">
                        <div class="widget-summary-col widget-summary-col-icon">
                            <div class="summary-icon bg-success">
                                <i class="fa fa-comment"></i>
                            </div>
                        </div>
                        <div class="widget-summary-col">
                            <div class="summary">
                                <h4 class="title">Opinions</h4>
                                <div class="info">
                                    <strong class="amount"><?php echo $totalOpinions; ?></strong>
                                </div>
                            </div>
                            <div class="summary-footer">
                                <a class="text-muted text-uppercase">(view all)</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>-->

    <!-- Total Sales !-->
    <!--    <div class="col-md-12 col-lg-6 col-xl-6">
            <section class="panel panel-featured-left panel-featured-primary">
                <div class="panel-body">
                    <div class="widget-summary">
                        <div class="widget-summary-col widget-summary-col-icon">
                            <div class="summary-icon bg-warning">
                                <i class="fa fa-dollar"></i>
                            </div>
                        </div>
                        <div class="widget-summary-col">
                            <div class="summary">
                                <h4 class="title">Total Orders</h4>
                                <div class="info">
                                    <strong class="amount"><?php echo $totalProdcutSale; ?> Orders</strong>
                                </div>
                            </div>
                            <div class="summary-footer">
                                <a class="text-muted text-uppercase">(view all)</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>-->


    <!-- Remaining SMS !-->
    <?php if (false && isset($smsProvidersCredit)) : ?>
        <div class='row'>
            <div class='col-md-12'>
                <hr/>
            </div>
        </div>
        <?php foreach ($smsProvidersCredit as $name => $providerCredit) : ?>
            <div class="col-md-12 col-lg-6 col-xl-6">
                <section class="panel panel-featured-left panel-featured-primary">
                    <div class="panel-body">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-info">
                                    <i class="fa fa-envelope"></i>
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    <h4 class="title">SMS Credit <small>(<?php echo $name ?>)</small></h4>
                                    <div class="info">
                                        <strong class="amount"><?php echo $providerCredit; ?></strong>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
