<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<!-- Specific Page Vendor CSS -->
<link rel="stylesheet" href="<?php echo $pfurl; ?>adminfiles/assets/vendor/morris/morris.css" />
<!-- Specific Page Vendor -->
<script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/jquery-appear/jquery.appear.js"></script>
<script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/jquery-easypiechart/jquery.easypiechart.js"></script>
<script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/flot/jquery.flot.js"></script>
<script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/flot-tooltip/jquery.flot.tooltip.js"></script>
<script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/flot/jquery.flot.pie.js"></script>
<script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/flot/jquery.flot.categories.js"></script>
<script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/flot/jquery.flot.resize.js"></script>
<script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/jquery-sparkline/jquery.sparkline.js"></script>
<script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/raphael/raphael.js"></script>
<script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/morris/morris.js"></script>
<script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/gauge/gauge.js"></script>
<script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/snap-svg/snap.svg.js"></script>
<script src="<?php echo $pfurl; ?>adminfiles/assets/vendor/liquid-meter/liquid.meter.js"></script>



<!-- User Charts !-->
<div class="row">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <a href="#" class="fa fa-caret-down"></a>
                    <a href="#" class="fa fa-times"></a>
                </div>

                <h2 class="panel-title">User Register Chart</h2>
                <p class="panel-subtitle">Here you can see join count at each day to the site</p>
            </header>
            <div class="panel-body">
                <!-- Morris: Line -->
                <div class="chart chart-md" id="morrisLine"></div>
                <script type="text/javascript">

                    Morris.Line({
                        element: 'morrisLine',
                        data: [
<?php
foreach ($registerChart as $visit) {
    echo "{y: '$visit->year', m: '$visit->month', d: '$visit->day', b: $visit->total},";
}
?>
                        ],
                        xkey: 'd',
                        ykeys: ['b'],
                        labels: ['Visit Per Day']
                    });
                </script>
            </div>
        </section>
    </div>

</div>

<div class="row">
    <!-- Total Users !-->
    <div class="col-md-12 col-lg-6 col-xl-6">
        <section class="panel panel-featured-left panel-featured-quartenary">
            <div class="panel-body">
                <div class="widget-summary">
                    <div class="widget-summary-col widget-summary-col-icon">
                        <div class="summary-icon bg-quartenary">
                            <i class="fa fa-user"></i>
                        </div>
                    </div>
                    <div class="widget-summary-col">
                        <div class="summary">
                            <h4 class="title">Total Users</h4>
                            <div class="info">
                                <strong class="amount"><?php echo $totalUsers ?></strong>
                            </div>
                        </div>
                        <div class="summary-footer">
                            <a class="text-muted text-uppercase">(View All)</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Total Contacts !-->
    <div class="col-md-12 col-lg-6 col-xl-6">
        <section class="panel panel-featured-left panel-featured-primary">
            <div class="panel-body">
                <div class="widget-summary">
                    <div class="widget-summary-col widget-summary-col-icon">
                        <div class="summary-icon bg-primary">
                            <i class="fa fa-life-ring"></i>
                        </div>
                    </div>
                    <div class="widget-summary-col">
                        <div class="summary">
                            <h4 class="title">Support Questions</h4>
                            <div class="info">
                                <strong class="amount"><?php echo $totalContacts; ?></strong>
                                <span class="text-primary">(<?php echo $totalContactsUnanswered; ?> unanswered)</span>
                            </div>
                        </div>
                        <div class="summary-footer">
                            <a class="text-muted text-uppercase">(view all)</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Total Opinions !-->
    <div class="col-md-12 col-lg-6 col-xl-6">
        <section class="panel panel-featured-left panel-featured-primary">
            <div class="panel-body">
                <div class="widget-summary">
                    <div class="widget-summary-col widget-summary-col-icon">
                        <div class="summary-icon bg-success">
                            <i class="fa fa-comment"></i>
                        </div>
                    </div>
                    <div class="widget-summary-col">
                        <div class="summary">
                            <h4 class="title">Opinions</h4>
                            <div class="info">
                                <strong class="amount"><?php echo $totalOpinions; ?></strong>
                            </div>
                        </div>
                        <div class="summary-footer">
                            <a class="text-muted text-uppercase">(view all)</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    
    <!-- Total Sales !-->
    <div class="col-md-12 col-lg-6 col-xl-6">
        <section class="panel panel-featured-left panel-featured-primary">
            <div class="panel-body">
                <div class="widget-summary">
                    <div class="widget-summary-col widget-summary-col-icon">
                        <div class="summary-icon bg-warning">
                            <i class="fa fa-dollar"></i>
                        </div>
                    </div>
                    <div class="widget-summary-col">
                        <div class="summary">
                            <h4 class="title">Total Orders</h4>
                            <div class="info">
                                <strong class="amount"><?php echo $totalProdcutSale; ?> Orders</strong>
                            </div>
                        </div>
                        <div class="summary-footer">
                            <a class="text-muted text-uppercase">(view all)</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
