<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>

<!-- User Charts !-->
<div class="row">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <a href="#" class="fa fa-caret-down"></a>
                    <a href="#" class="fa fa-times"></a>
                </div>

                <h2 class="panel-title">User Register Chart</h2>
                <p class="panel-subtitle">Here you can see join count at each day to the site</p>
            </header>
            <div class="panel-body">
                <?php $form->renderDecorated('registerchart'); ?> 
            </div>
        </section>
    </div>

</div>

<div class="row">
    <div class="col-md-12">



        <div class='row'>
            <!-- Total Bongahs !-->
            <div class="col-md-12 col-lg-4 col-xl-3">
                <section class="panel panel-featured-left panel-featured-tertiary">
                    <div class="panel-body">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-tertiary">
                                    <i class="fa fa-building"></i>
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    <h4 class="title">بنگاه</h4>
                                    <div class="info">
                                        <strong class="amount"><?php echo $totalBongahs ?></strong>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                    <a href="<?php echo $this->url->get("bongah/list"); ?>" class="text-muted text-uppercase">(مشاهده همه)</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>

            <!-- Total Melks !-->
            <div class="col-md-12 col-lg-4 col-xl-3">
                <section class="panel panel-featured-left panel-featured-warning">
                    <div class="panel-body">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-warning">
                                    <i class="fa fa-home"></i>
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    <h4 class="title">ملک</h4>
                                    <div class="info">
                                        <strong class="amount"><?php echo $totalMelks ?></strong>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                    <a href="<?php echo $this->url->get("melk/list"); ?>" class="text-muted text-uppercase">(مشاهده همه)</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>

            <!-- Total Phone Listners !-->
            <div class="col-md-12 col-lg-4 col-xl-3">
                <section class="panel panel-featured-left panel-featured-success">
                    <div class="panel-body">
                        <div class="widget-summary">
                            <div class="widget-summary-col widget-summary-col-icon">
                                <div class="summary-icon bg-success">
                                    <i class="fa fa-phone"></i>
                                </div>
                            </div>
                            <div class="widget-summary-col">
                                <div class="summary">
                                    <h4 class="title">املاک درخواستی</h4>
                                    <div class="info">
                                        <strong class="amount"><?php echo $totalPhoneListners ?></strong>
                                    </div>
                                </div>
                                <div class="summary-footer">
                                    <a href="<?php echo $this->url->get("melkphonelistner/list"); ?>" class="text-muted text-uppercase">(مشاهده همه)</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
    <div class='row'>
        <div class='col-md-12'>
            <hr/>
        </div>
    </div>
    <!-- Total Users !-->
    <div class="col-md-12 col-lg-6 col-xl-6">
        <section class="panel panel-featured-left panel-featured-quartenary">
            <div class="panel-body">
                <div class="widget-summary">
                    <div class="widget-summary-col widget-summary-col-icon">
                        <div class="summary-icon bg-quartenary">
                            <i class="fa fa-user"></i>
                        </div>
                    </div>
                    <div class="widget-summary-col">
                        <div class="summary">
                            <h4 class="title">Total Users</h4>
                            <div class="info">
                                <strong class="amount"><?php echo $totalUsers ?></strong>
                            </div>
                        </div>
                        <div class="summary-footer">
                            <a href="<?php echo $this->url->get("user/list"); ?>" class="text-muted text-uppercase">(View All)</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Total Contacts !-->
    <div class="col-md-12 col-lg-6 col-xl-6">
        <section class="panel panel-featured-left panel-featured-primary">
            <div class="panel-body">
                <div class="widget-summary">
                    <div class="widget-summary-col widget-summary-col-icon">
                        <div class="summary-icon bg-primary">
                            <i class="fa fa-life-ring"></i>
                        </div>
                    </div>
                    <div class="widget-summary-col">
                        <div class="summary">
                            <h4 class="title">Support Questions</h4>
                            <div class="info">
                                <strong class="amount"><?php echo $totalContacts; ?></strong>
                                <span class="text-primary">(<?php echo $totalContactsUnanswered; ?> unanswered)</span>
                            </div>
                        </div>
                        <div class="summary-footer">
                            <a class="text-muted text-uppercase">(view all)</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Total Opinions !-->
    <div class="col-md-12 col-lg-6 col-xl-6">
        <section class="panel panel-featured-left panel-featured-primary">
            <div class="panel-body">
                <div class="widget-summary">
                    <div class="widget-summary-col widget-summary-col-icon">
                        <div class="summary-icon bg-success">
                            <i class="fa fa-comment"></i>
                        </div>
                    </div>
                    <div class="widget-summary-col">
                        <div class="summary">
                            <h4 class="title">Opinions</h4>
                            <div class="info">
                                <strong class="amount"><?php echo $totalOpinions; ?></strong>
                            </div>
                        </div>
                        <div class="summary-footer">
                            <a class="text-muted text-uppercase">(view all)</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

    <!-- Total Sales !-->
    <div class="col-md-12 col-lg-6 col-xl-6">
        <section class="panel panel-featured-left panel-featured-primary">
            <div class="panel-body">
                <div class="widget-summary">
                    <div class="widget-summary-col widget-summary-col-icon">
                        <div class="summary-icon bg-warning">
                            <i class="fa fa-dollar"></i>
                        </div>
                    </div>
                    <div class="widget-summary-col">
                        <div class="summary">
                            <h4 class="title">Total Orders</h4>
                            <div class="info">
                                <strong class="amount"><?php echo $totalProdcutSale; ?> Orders</strong>
                            </div>
                        </div>
                        <div class="summary-footer">
                            <a class="text-muted text-uppercase">(view all)</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>


    <!-- Remaining SMS !-->
    <?php if (isset($remainingSMSCredit)) : ?>
        <div class="col-md-12 col-lg-6 col-xl-6">
            <section class="panel panel-featured-left panel-featured-primary">
                <div class="panel-body">
                    <div class="widget-summary">
                        <div class="widget-summary-col widget-summary-col-icon">
                            <div class="summary-icon bg-info">
                                <i class="fa fa-envelope"></i>
                            </div>
                        </div>
                        <div class="widget-summary-col">
                            <div class="summary">
                                <h4 class="title">SMS Credit</h4>
                                <div class="info">
                                    <strong class="amount"><?php echo $remainingSMSCredit; ?></strong>
                                </div>
                            </div>
                            <div class="summary-footer">
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    <?php endif; ?>
</div>
