<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel panel-success'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>

                    <h2 class='panel-title'>Send SMS</h2>
                </header>
                <div class='panel-body'>


                    <!--  ADD From Number !-->
                    <?php $form->renderDecorated('fromnumber'); ?> 

                    <!--  ADD Phones !-->
                    <?php $form->renderDecorated('phones'); ?> 

                    <!--  ADD Message !-->
                    <?php $form->renderDecorated('message'); ?> 

                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


