<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>ویرایش</h2>
                    <p class='panel-subtitle'Use this form to edit your StockChange</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD Stock ID !-->
                    <?php $form->renderDecorated('stockid'); ?> 

                    <!--  ADD User ID !-->
                    <?php $form->renderDecorated('userid'); ?> 

                    <!--  ADD Worker ID !-->
                    <?php $form->renderDecorated('workerid'); ?> 

                    <!--  ADD Count !-->
                    <?php $form->renderDecorated('count'); ?> 

                    <!--  ADD Date !-->
                    <?php $form->renderDecorated('date'); ?> 

                    <!--  ADD Reason Code !-->
                    <?php $form->renderDecorated('reasoncode'); ?> 

                    <!--  ADD Reason !-->
                    <?php $form->renderDecorated('reason'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


