<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel panel-primary'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>مشاهده تغییرات</h2>
                    <p class='panel-subtitle'Use this form to edit your StockChange</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD ID !-->
                    <?php $form->renderInfo('id'); ?> 

                    <!--  ADD Stock ID !-->
                    <?php $form->renderInfo('stockid'); ?> 

                    <!--  ADD User ID !-->
                    <?php $form->renderInfo('userid'); ?> 

                    <!--  ADD Worker ID !-->
                    <?php $form->renderInfo('workerid'); ?> 

                    <!--  ADD Count !-->
                    <?php $form->renderInfo('count'); ?> 

                    <!--  ADD Date !-->
                    <?php $form->renderInfo('date'); ?> 

                    <!--  ADD Reason Code !-->
                    <?php $form->renderInfo('reasoncode'); ?> 

                    <!--  ADD Reason !-->
                    <?php $form->renderInfo('reason'); ?> 


                </div>
            </section>
        </div>
    </div>
</form>


