<?php
// fetch action name
$this->di
?>

<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<section class='panel'>
    <header class='panel-heading'>
        <div class='panel-actions'>
            <a href='#' class='fa fa-caret-down'></a>
            <a href='#' class='fa fa-times'></a>
        </div>
        <h2 class='panel-title'>Search Statics</h2>
    </header>
    <div class='panel-body'>
        <div class='row'>
            <div class='col-md-12'>
                <?php $form->renderDecorated('chart'); ?> 
            </div>
        </div>
        <div class='well well-sm'>
            <div class='row'>
                <div class='col-md-8'>
                    <form class='form-inline'> 
                        <div class='form-group'>
                            <h5>Fetch Top Queries</h5>
                        </div>
                    </form>
                </div>
                <div class='col-md-4' style="text-align: right;">
                    <form class='form-inline'> 
                        <div class='form-group'>
                            <select class='form-control' id='selectedday'>
                                <option value='1' <?php if ($day == 1) echo "selected" ?>>Past One Day</option>
                                <option value='7' <?php if ($day == 7) echo "selected" ?>>Past Seven Day</option>
                                <option value='30' <?php if ($day == 30) echo "selected" ?>>Past Month</option>
                                <option value='60' <?php if ($day == 60) echo "selected" ?>>Past Two Month</option>
                                <option value='180' <?php if ($day == 180) echo "selected" ?>>Past Six Month</option>
                            </select>
                        </div>
                        <div class='form-group'>
                            <input type='button' class='btn btn-primary' value='Go' name='go' id='gotodate' />
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <?php
        echo $list->header;
        echo $list->table;
        echo $list->footer;
        ?>
    </div>
</section>
<script>

    $("#gotodate").click(function () {
        var day = $("#selectedday").val();
        document.location.href = '<?php echo $this->url->get("searchhistory/most/1/") ?>' + day;
    });
</script>