<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>ویرایش بسته</h2>
                    <p class='panel-subtitle'Use this form to edit your Account</p>
                </header>
                <div class='panel-body'>

                      <!--  ADD Title !-->
                    <?php $form->renderDecorated('title'); ?> 

                    <!--  ADD Price !-->
                    <?php $form->renderDecorated('price'); ?> 

                    <!--  ADD Credit !-->
                    <?php $form->renderDecorated('credit'); ?> 

                    <!--  ADD Date !-->
                    <?php $form->renderDecorated('date'); ?> 

                    <!--  ADD Enable !-->
                    <?php $form->renderDecorated('enable'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


