<div role="tabpanel" class="custom-website">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs custom-website-nav" role="tablist">
        <li role="presentation" class="active"><a href="#info" aria-controls="home" role="tab" data-toggle="tab">معرفی سامانه</a></li>
        <li role="presentation"><a href="#demo" aria-controls="messages" role="tab" data-toggle="tab">دموی سامانه</a></li>
        <li role="presentation"><a href="#android" aria-controls="messages" role="tab" data-toggle="tab">برنامه اختصاصی اندروید</a></li>
        <li role="presentation"><a href="#order" aria-controls="settings" role="tab" data-toggle="tab">سفارش</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">


        <!-- Page !-->
        <div role="tabpanel" class="tab-pane active" id="info">
            <div class="jumbotron" style="padding-top: 20px;">
                <div class="container">
                    <div class="row">
                        <div class="col-md-7">
                            <h2>
                                سامانه اختصاصی املاک گستر چیست؟
                            </h2>
                            <p class="_description" style="padding-left: 70px;">
                                املاک گستر سامانه ای است که به صاحبان آژانس املاک این امکان را میدهد تا املاک درون بنگاه خود را برای کاربران به نمایش بگذارند، همچنین میتوان از این سامانه برای مدیریت املاک استفاده نمود
                            </p>
                        </div>
                        <div class="col-md-5">
                            <img src="<?php echo $this->url->get(""); ?>img/screenshots/home_gridview.jpg" class="img-rounded width_100">
                        </div>
                    </div>
                </div>
            </div>

            <div class="jumbotron">
                <div class="container">
                    <div class="row">
                        <div class="col-md-5">
                            <img src="<?php echo $this->url->get(""); ?>img/screenshots/home_map.jpg" class="img-rounded" style="width: 100%;">
                        </div>
                        <div class="col-md-7">
                            <h2 style="padding-right: 70px;">
                                نمایش املاک بر روی نقشه
                            </h2>
                            <p class="_description" style="padding-right: 70px;">
                                صاحبان بنگاه میتوانند املاک خود را بر روی نقشه نمایش دهند. کاربران با استفاده از نقشه منطقه خود تمامی املاک را میتوانند مشاهده نمایند
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="jumbotron">
                <div class="container">
                    <div class="row">
                        <div class="col-md-7">
                            <h2>
                                قابلیت جستجوی پیشرفته برای کاربران
                            </h2>
                            <p class="_description" style="padding-left: 70px;">
                                چنانچه شخصی به دنبال ملکی خاصی باشد، به راحتی میتواند با استفاده از جستجوی پیشرفته تعبیه شده در سامانه، ملک مورد نظر خود را پیدا نماید
                            </p>
                        </div>
                        <div class="col-md-5">
                            <img src="<?php echo $this->url->get(""); ?>img/screenshots/advanced_search_showonlist.jpg" class="img-rounded width_100">
                        </div>
                    </div>
                </div>
            </div>


            <div class="jumbotron">
                <div class="container">
                    <div class="row">
                        <div class="col-md-5">
                            <img src="<?php echo $this->url->get(""); ?>img/screenshots/newhomeuser.jpg" class="img-rounded" style="width: 100%;">
                        </div>
                        <div class="col-md-7">
                            <h2 style="padding-right: 70px;">
                                قابلیت اضافه کردن ملک توسط کاربران سایت
                            </h2>
                            <p class="_description" style="padding-right: 70px;">
                                کاربران سایت میتوانند املاک خود را به راحتی بعد از عضویت در سایت به سامانه اضافه نمایند. مدیران سامانه میتوانند املاک اضافه شده را بررسی، تایید و یا حذف نمایند
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="jumbotron">
                <div class="container">
                    <div class="row">
                        <div class="col-md-7">
                            <h2>
                                سیستم مدیریت پیشرفته
                            </h2>
                            <p class="_description" style="padding-left: 70px;">
                                از مهمترین قسمت های سامانه میتوان به مدریت بسیار قوی و کاربردی آن اشاره نمود، با استفاده از پنل مدریت سامانه میتوانید املاک خود را اضافه نمایید، اعضا را کنترل نمایید، وبسایت را کنترل نموده و بسیاری امکانات دیگر، برای مشاهده کامل پنل مدریت به قسمت <a href="http://demo.amlakgostar.ir/">دمو</a> سامانه بروید
                            </p>
                        </div>
                        <div class="col-md-5">
                            <img src="<?php echo $this->url->get(""); ?>img/screenshots/admin-homes-search.jpg" class="img-rounded width_100">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Demo !-->
        <div role="tabpanel" class="tab-pane" id="demo">
            <div class="row">
                <div class="col-md-12">
                    <h3 style="margin-top: 0px;">صفحه کاربری</h3>
                    <p>با کلیک بر روی کلید دموی سامانه، میتوانید تمامی امکانات سامانه را مشاهده و بررسی نمایید</p>
                    <a target="_blank" href="http://demo.amlakgostar.ir" class="btn btn-primary">دموی سامانه</a>
                    <hr/>

                    <h3 style="margin-top: 20px;">پنل مدیریت</h3>
                    <p>با استفاده از اطلاعات زیر میتوانید به پنل مدریت سایت وارد شده و بخش مدیریت را مشاهده نمایید</p>
                    <a target="_blank" class="btn btn-primary" href="http://demo.amlakgostar.ir/index.php/en/admin">پنل مدیریت</a><br/>
                    <br/>
                    <b>نام کاربری :</b>&nbsp;&nbsp;&nbsp;     admin<br/>
                    <b>رمز عبور&nbsp;&nbsp;&nbsp; :</b>&nbsp;&nbsp;&nbsp;       test123456
                </div>
            </div>
        </div>

        <!-- Price !-->
        <div role="tabpanel" class="tab-pane" id="android">
            <div class="row">
                <div class="col-md-12">
                    <div class="jumbotron" style="padding-top: 20px;">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-7">
                                    <h2>
                                        جستجو در املاک
                                    </h2>
                                    <p class="_description" style="padding-left: 70px;">
                                        توسط نسخه اندروید املاک گستر، تمامی بنگاه داران خواهند توانست به صورت آنلاین و یا حتی آفلاین در میان املاک جستجو نمایند
                                    </p>
                                </div>
                                <div class="col-md-5">
                                    <img src="<?php echo $this->url->get(""); ?>img/screenshots/search.png" class="img-rounded width_100">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="jumbotron">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-5">
                                    <img src="<?php echo $this->url->get(""); ?>img/screenshots/melks.png" class="img-rounded" style="width: 100%;">
                                </div>
                                <div class="col-md-7">
                                    <h2 style="padding-right: 70px;">
                                        قابلیت ارسال مشخصات عمومی ملک برای مشتریان
                                    </h2>
                                    <p class="_description" style="padding-right: 70px;">
                                        یکی از ویژگی های متفاوت برنامه املاک گستر، ارسال مشخصات عمومی ملک برای مشتریان از طریق پیامک میباشد
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>


        <!-- Order !-->
        <div role="tabpanel" class="tab-pane" id="order">
            <h3 style="margin-top: 0px;">قیمت</h3>
            <p>هزینه دریافت وبسایت اختصاصی املاک گستر به همراه برنامه اندروید اختصاصی و یک خط ویژه پیامکی تنها یک میلیون تومان میباشد</p>

            <h3 >نحوه سفارش</h3>
            <p>سفارش سامانه در هر شهر محدود میباشد، لذا برای سفارش سامانه با شماره <?php echo $websiteSettings->contactphone; ?> تماس حاصل فرمایید</p>

            <h3>مدت زمان آماده سازی</h3>
            <p>مدت زمان آماده سازی، یک روز کاری میباشد</p>

            <h3>شخصی سازی سایت</h3>
            <p>در صورت نیاز شما میتوانید وبسایت خود را شخصی سازی نموده تا طراحی سایت متناسب با نیاز شما باشد، در صورت نیاز درخواست خود را در هنگام سفارش بیان نمایید</p>
        </div>
    </div>

</div>