<?php

use Phalcon\Tag; ?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel='shortcut icon' type='image/x-icon' href='/favicon.ico' />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php if (!$websiteSettings->rtl) : ?>
            <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,700' rel='stylesheet' type='text/css'>
        <?php endif; ?>
        <?php $this->assets->outputCss('header') ?>
        <?php $this->assets->outputJs('footer') ?>

        <?php $this->assets->outputJs('externalscripts') ?>
        <?php $this->assets->outputJs('elementscripts') ?>
        <?php $this->assets->outputCss('elementscss') ?>
        <?php echo Tag::getTitle() ?>
        <script>
            !function(a) {
                function f(a, b) {
                    if (!(a.originalEvent.touches.length > 1)) {
                        a.preventDefault();
                        var c = a.originalEvent.changedTouches[0], d = document.createEvent("MouseEvents");
                        d.initMouseEvent(b, !0, !0, window, 1, c.screenX, c.screenY, c.clientX, c.clientY, !1, !1, !1, !1, 0, null), a.target.dispatchEvent(d)
                    }
                }
                if (a.support.touch = "ontouchend"in document, a.support.touch) {
                    var e, b = a.ui.mouse.prototype, c = b._mouseInit, d = b._mouseDestroy;
                    b._touchStart = function(a) {
                        var b = this;
                        !e && b._mouseCapture(a.originalEvent.changedTouches[0]) && (e = !0, b._touchMoved = !1, f(a, "mouseover"), f(a, "mousemove"), f(a, "mousedown"))
                    }, b._touchMove = function(a) {
                        e && (this._touchMoved = !0, f(a, "mousemove"))
                    }, b._touchEnd = function(a) {
                        e && (f(a, "mouseup"), f(a, "mouseout"), this._touchMoved || f(a, "click"), e = !1)
                    }, b._mouseInit = function() {
                        var b = this;
                        b.element.bind({touchstart: a.proxy(b, "_touchStart"), touchmove: a.proxy(b, "_touchMove"), touchend: a.proxy(b, "_touchEnd")}), c.call(b)
                    }, b._mouseDestroy = function() {
                        var b = this;
                        b.element.unbind({touchstart: a.proxy(b, "_touchStart"), touchmove: a.proxy(b, "_touchMove"), touchend: a.proxy(b, "_touchEnd")}), d.call(b)
                    }
                }
            }(jQuery);
            function getIranianPrice(value)
            {
                var cost = 0;
                if (value == 0)
                {
                    return "رایگان";
                } else if (value < 1)
                {
                    cost = value / 1000;
                    cost = cost + " هزار تومان";
                } else if (value < 1000) {
                    cost = value + " میلون تومان";
                } else if (value >= 1000) {
                    cost = (value / 1000) + " میلیارد تومان";
                }
                return cost;
            }
        </script>

        <!-- Meta Keywords and Meta Description !-->
        <?php if (!(isset($metaDescription) && strlen($metaDescription) > 0) && isset($websiteSettings->metadata) && strlen($websiteSettings->metadata) > 0) : ?>
            <meta name="description" content="<?php echo $websiteSettings->metadata; ?>">
        <?php endif; ?>
        <?php if (!(isset($metaKeywords) && strlen($metaKeywords) > 0) && isset($websiteSettings->keywords) && strlen($websiteSettings->keywords) > 0) : ?>
            <meta name="keywords" content="<?php echo $websiteSettings->keywords; ?>">
        <?php endif; ?>
        <!-- Check For Custom Pages !-->
        <?php if (isset($metaDescription) && strlen($metaDescription) > 0) : ?>
            <meta name="description" content="<?php echo $metaDescription; ?>">
        <?php endif; ?>
        <?php if (isset($metaKeywords) && strlen($metaKeywords) > 0) : ?>
            <meta name="keywords" content="<?php echo $metaKeywords; ?>">
        <?php endif; ?>
    </head>
    <!-- Load The Header !-->
    <?php $this->partial("layouts/header") ?>
    <body>
        <div id='page-container'>
            <div id='page-container-body'>
                <!-- Check For Global Message !-->
                <?php if (isset($websiteSettings->globalmessage) && strlen($websiteSettings->globalmessage) > 0) : ?>
                    <div class="container">
                        <div class="col-md-12"> 
                            <div class='alert alert-info _global-message'>
                                <h4 style="margin-top: 0px;"><?= _("Public Message"); ?></h4>
                                <?php echo $websiteSettings->globalmessage; ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>

                <!-- Check For Verified Phone -->
                <?php if (intval($websiteSettings->requestverifiedphone) == 1 && isset($user) && !$user->hasVerifiedPhone()) : ?>
                    <div class="container">
                        <div class="col-md-12"> 
                            <div class='alert alert-danger'>
                                <h4 style="margin-top: 0px;"><?= _("Need Verified Phone"); ?></h4>
                                <p><?= _("You have not verified phone, Please add and verify your phone"); ?></p>
                                <br/>
                                <a href='<?php echo $this->url->get("user/phones/"); ?>' class='btn btn-default btn-sm'><?= _("View My Phones"); ?></a>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>

                <!-- Page Content !-->
                <div class="container">
                    <?php echo $this->getContent(); ?>
                </div>
            </div>
            <!-- Footer !-->
            <?php $this->partial("layouts/footer") ?>
            <!-- Analytics Codes !-->
            <?php
            if (isset($websiteSettings->googleanalytics) && strlen($websiteSettings->googleanalytics) > 0) {
                echo $websiteSettings->googleanalytics;
            }

            if (isset($websiteSettings->clickyanalitics) && strlen($websiteSettings->clickyanalitics) > 0) {
                echo $websiteSettings->clickyanalitics;
            }
            ?>

        </div>
    </body>
</html>
