<?php

use Phalcon\Tag; ?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,700' rel='stylesheet' type='text/css'>
        <?php $this->assets->outputCss('header') ?>
        <?php $this->assets->outputJs('footer') ?>

        <?php $this->assets->outputJs('externalscripts') ?>
        <?php $this->assets->outputJs('elementscripts') ?>
        <?php echo Tag::getTitle() ?>
    </head>
    <!-- Load The Header !-->
    <?php $this->partial("layouts/header") ?>
    <body>
        <div class="container-fluid">
            <div class="col-md-12" style="text-align: left;">
                <?php echo $this->getContent(); ?>
            </div>
        </div>
        <?php $this->partial("layouts/footer") ?>
        <?php
        if (isset($websiteSettings->googleanalytics) && strlen($websiteSettings->googleanalytics) > 0) {
            echo $websiteSettings->googleanalytics;
        }

        if (isset($websiteSettings->clickyanalitics) && strlen($websiteSettings->clickyanalitics) > 0) {
            echo $websiteSettings->googleanalytics;
        }
        ?>
    </body>
</html>
