<?php

use Phalcon\Tag; ?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <?php if (!$websiteSettings->rtl) : ?>
            <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,700' rel='stylesheet' type='text/css'>
        <?php endif; ?>
        <?php $this->assets->outputCss('header') ?>
        <?php $this->assets->outputJs('footer') ?>

        <?php $this->assets->outputJs('externalscripts') ?>
        <?php $this->assets->outputJs('elementscripts') ?>
        <?php $this->assets->outputCss('elementscss') ?>
        <?php echo Tag::getTitle() ?>

        <!-- Meta Keywords and Meta Description !-->
        <?php if (!(isset($metaDescription) && strlen($metaDescription) > 0) && isset($websiteSettings->metadata) && strlen($websiteSettings->metadata) > 0) : ?>
            <meta name="description" content="<?php echo $websiteSettings->metadata; ?>">
        <?php endif; ?>
        <?php if (!(isset($metaKeywords) && strlen($metaKeywords) > 0) && isset($websiteSettings->keywords) && strlen($websiteSettings->keywords) > 0) : ?>
            <meta name="keywords" content="<?php echo $websiteSettings->keywords; ?>">
        <?php endif; ?>
        <!-- Check For Custom Pages !-->
        <?php if (isset($metaDescription) && strlen($metaDescription) > 0) : ?>
            <meta name="description" content="<?php echo $metaDescription; ?>">
        <?php endif; ?>
        <?php if (isset($metaKeywords) && strlen($metaKeywords) > 0) : ?>
            <meta name="keywords" content="<?php echo $metaKeywords; ?>">
        <?php endif; ?>
    </head>
    <!-- Load The Header !-->
    <?php $this->partial("layouts/header") ?>
    <body>
        <div id='page-container'>
            <div id='page-container-body'>
                <!-- Check For Global Message !-->
                <?php if (isset($websiteSettings->globalmessage) && strlen($websiteSettings->globalmessage) > 0) : ?>
                    <div class="container-fluid">
                        <div class="col-md-12"> 
                            <div class='alert alert-info _global-message'>
                                <h4 style="margin-top: 0px;"><?= _("Public Message"); ?></h4>
                                <?php echo $websiteSettings->globalmessage; ?>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>

                <!-- Check For Verified Phone -->
                <?php if (isset($websiteSettings->requestverifiedphone) && isset($user) && !$user->hasVerifiedPhone()) : ?>
                    <div class="container-fluid">
                        <div class="col-md-12"> 
                            <div class='alert alert-danger'>
                                <h4 style="margin-top: 0px;"><?= _("Need Verified Phone"); ?></h4>
                                <p><?= _("You have not verified phone, Please add and verify your phone"); ?></p>
                                <br/>
                                <a href='<?php echo $this->url->get("user/phones/"); ?>' class='btn btn-default btn-sm'><?= _("View My Phones"); ?></a>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>

                <!-- Page Content !-->
                <div class="container-fluid">
                    <div class="col-md-12">
                        <?php echo $this->getContent(); ?>
                    </div>
                </div>
            </div>
            <!-- Footer !-->
            <?php $this->partial("layouts/footer") ?>
            <!-- Analytics Codes !-->
            <?php
            if (isset($websiteSettings->googleanalytics) && strlen($websiteSettings->googleanalytics) > 0) {
                echo $websiteSettings->googleanalytics;
            }

            if (isset($websiteSettings->clickyanalitics) && strlen($websiteSettings->clickyanalitics) > 0) {
                echo $websiteSettings->googleanalytics;
            }
            ?>
        </div>
    </body>
</html>
