<header class="header">
    <div class="logo-container">
        <a href="<?php echo $this->url->get(""); ?>" class="logo">
            <?php echo $websiteSettings->websitename; ?> Administration 
        </a>
        <div class="visible-xs toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
            <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
        </div>
    </div>

    <!-- start: search & user box --> 
    <div class="header-right">

        <div class="search nav-form">
            <div class="input-group input-search">
                <input type="text" class="form-control" name="q" id="headersearchquery" placeholder="Search...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                </span>
            </div>
        </div>

        <ul class="notifications">
            <!--            <li>
                            <a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
                                <i class="fa fa-tasks"></i>
                                <span class="badge">3</span>
                            </a>
            
                            <div class="dropdown-menu notification-menu large">
                                <div class="notification-title">
                                    <span class="pull-right label label-default">3</span>
                                    Tasks
                                </div>
            
                                <div class="content">
                                    <ul>
                                        <li>
                                            <p class="clearfix mb-xs">
                                                <span class="message pull-left">Generating Sales Report</span>
                                                <span class="message pull-right text-dark">60%</span>
                                            </p>
                                            <div class="progress progress-xs light">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;"></div>
                                            </div>
                                        </li>
            
                                        <li>
                                            <p class="clearfix mb-xs">
                                                <span class="message pull-left">Importing Contacts</span>
                                                <span class="message pull-right text-dark">98%</span>
                                            </p>
                                            <div class="progress progress-xs light">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="98" aria-valuemin="0" aria-valuemax="100" style="width: 98%;"></div>
                                            </div>
                                        </li>
            
                                        <li>
                                            <p class="clearfix mb-xs">
                                                <span class="message pull-left">Uploading something big</span>
                                                <span class="message pull-right text-dark">33%</span>
                                            </p>
                                            <div class="progress progress-xs light mb-xs">
                                                <div class="progress-bar" role="progressbar" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100" style="width: 33%;"></div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </li>-->
            <li>
                <a href="<?php echo $pfurl; ?>" class="dropdown-toggle notification-icon">
                    <i class="fa fa-arrow-circle-right"></i>
                </a>

                <div class="dropdown-menu notification-menu">
                    <div class="notification-title">
                        <span class="pull-right label label-default">230</span>
                        Messages
                    </div>

                    <div class="content">
                        <ul>
                            <?php foreach ($lastMessages as $message): ?>
                                <li>
                                    <a href="#" class="clearfix">
                                        <!--<figure class="image">
                                            <img src="<?php echo $pfurl; ?>adminfiles/assets/images/!sample-user.jpg" alt="Joseph Doe Junior" class="img-circle" />
                                        </figure>-->
                                        <span class="title"><?php echo $message->name ?></span>
                                        <span class="message"><?php echo $message->message ?></span>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>

                        <hr />

                        <div class="text-right">
                            <a href="#" class="view-more">View All</a>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
                    <i class="fa fa-envelope"></i>
                    <?php if ($newMessageCount > 0) : ?>
                        <span class="badge"><?php echo $newMessageCount; ?></span>
                    <?php endif; ?>
                </a>

                <div class="dropdown-menu notification-menu">
                    <div class="notification-title">
                        <span class="pull-right label label-default">230</span>
                        Messages
                    </div>

                    <div class="content">
                        <ul>
                            <?php foreach ($lastMessages as $message): ?>
                                <li>
                                    <a href="#" class="clearfix">
                                        <!--<figure class="image">
                                            <img src="<?php echo $pfurl; ?>adminfiles/assets/images/!sample-user.jpg" alt="Joseph Doe Junior" class="img-circle" />
                                        </figure>-->
                                        <span class="title"><?php echo $message->name ?></span>
                                        <span class="message"><?php echo $message->message ?></span>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>

                        <hr />

                        <div class="text-right">
                            <a href="#" class="view-more">View All</a>
                        </div>
                    </div>
                </div>
            </li>
            <li>
                <a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
                    <i class="fa fa-home"></i>
                    <?php if ($estateWaitForApproveCount > 0) : ?>
                        <span class="badge"><?php echo $estateWaitForApproveCount; ?></span>
                    <?php endif; ?>
                </a>

                <div class="dropdown-menu notification-menu">
                    <div class="notification-title">
                        <span class="pull-right label label-default"><?php echo $estateWaitForApproveCount; ?></span>
                        Wait For Approve
                    </div>

                    <div class="content">
                        <ul>
                            <?php foreach ($amlaksWaitForApprove as $melk) : ?>
                                <li>
                                    <a href="#" class="clearfix">
                                        <div class="image">
                                            <i class="fa fa-home bg-success"></i>
                                        </div>
                                        <span class="title"><?php echo $melk->getQuickInfo(); ?></span>
                                        <span class="message"><?php echo $melk->getCityName(); ?></span>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                        <hr />
                        <div class="text-right">
                            <a href="<?php echo $this->url->get("melk/list"); ?>" class="view-more">View All</a>
                        </div>
                    </div>
                </div>
            </li>

            <!-- Bongahs !-->
            <li>
                <a href="#" class="dropdown-toggle notification-icon" data-toggle="dropdown">
                    <i class="fa fa-building"></i>
                    <?php if ($bongahWaitForApproveCount > 0) : ?>
                        <span class="badge"><?php echo $bongahWaitForApproveCount; ?></span>
                    <?php endif; ?>
                </a>

                <div class="dropdown-menu notification-menu">
                    <div class="notification-title">
                        <span class="pull-right label label-default"><?php echo $bongahWaitForApproveCount; ?></span>
                        Wait For Approve
                    </div>

                    <div class="content">
                        <ul>
                            <?php foreach ($bongahsWaitForApprove as $bongah) : ?>
                                <li>
                                    <a href="<?php echo $this->url->get("bongah/view/$bongah->id"); ?>" class="clearfix">
                                        <div class="image">
                                            <i class="fa fa-building bg-success"></i>
                                        </div>
                                        <span class="title"><?php echo $bongah->title; ?></span>
                                        <span class="message"><?php echo $bongah->getCityName(); ?>،<?php echo $bongah->address; ?></span>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                        <hr />
                        <div class="text-right">
                            <a href="<?php echo $this->url->get("bongah/list"); ?>" class="view-more">View All</a>
                        </div>
                    </div>
                </div>
            </li>
        </ul>

        <span class="separator"></span>

        <div id="userbox" class="userbox">
            <a href="#" data-toggle="dropdown">
                <figure class="profile-picture">
                    <img src="<?php echo $loggedInUser->getImageLink(); ?>" class="img-circle" data-lock-picture="<?php echo $pfurl; ?>adminfiles/assets/images/!logged-user.jpg" />
                </figure>
                <div class="profile-info" data-lock-name="John Doe" data-lock-email="johndoe@okler.com">
                    <span class="name"><?php echo $this->session->get("fname"); ?></span>
                    <span class="role">Super Administrator</span>
                </div>

                <i class="fa custom-caret"></i>
            </a>

            <div class="dropdown-menu">
                <ul class="list-unstyled">
                    <li class="divider"></li>
                    <li>
                        <a role="menuitem" tabindex="-1" href="<?php echo $this->url->get("user/view/" . $loggedInUser->userid); ?>"><i class="fa fa-user"></i> My Profile</a>
                    </li>
                    <li>
                        <a role="menuitem" tabindex="-1" href="#" data-lock-screen="true"><i class="fa fa-lock"></i> Lock Screen</a>
                    </li>
                    <li>
                        <a role="menuitem" tabindex="-1" href="pages-signin.html"><i class="fa fa-power-off"></i> Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- end: search & user box -->
</header>


<script>
    $(function() {
        $("#headersearchquery").autocomplete({
            minLength: 0,
            source: function(query, response) {
                var that = this;
                console.log(query.term);
                console.log("<?php echo $this->url->get("api/") ?>searchuser/" + query.term);
                $.ajax({
                    type: "post",
                    url: "<?php echo $this->url->get("api/") ?>searchuser/" + query.term,
                    success: function(output) {
                        response(JSON.parse(output));
                    }
                    ,
                    error: function(a, b, c)
                    {

                    }
                });

            },
            focus: function(event, ui) {
                $("#project").val(ui.item.label);
                return false;
            },
            select: function(event, ui) {
                $("#project").val(ui.item.label);
                $("#project-id").val(ui.item.value);
                $("#project-description").html(ui.item.desc);
                $("#project-icon").attr("src", "images/" + ui.item.icon);

                return false;
            }
        }).autocomplete("instance")._renderItem = function(ul, item) {
            console.log(item);
            var link = "<?php echo $this->url->get("user/view/") ?>" + item.userid;
            $item = $("<div class='media _header_search_item'><a href=''><img class='media-object pull-left _header_search_profileimage'><div class='media-body'><h5 class='media-heading' id='title'>title</h5><p id='info'>body</p></div></a></div>");
            $item.find("img").attr("src", item.imagelink);
            $item.find("#title").html(item.fullname);
            $item.find("#info").html("userid : " + item.userid);
            $item.find("a").attr("href", link);
            return $item.appendTo(ul);
        };
    });
</script>
<style>

    body{
        font-family: tahoma;
    }

    .elementlabel{
        white-space: nowrap;
        margin-bottom: 7px;
        font-size: 15px;
    }

    .elementinfo{
        font-size: 80%;
        white-space: nowrap;
        margin-bottom: 0px;
    }

    .elementholder{
        margin-bottom: 10px;
    }

    .nav > li > a {
        white-space: nowrap;
    }
</style>
