<header class="header">

    <!-- start: search & user box --> 
    <div class="header-right">

        <div class="logo-container">
            <a href="<?php echo $this->url->get(""); ?>" class="logo">
                <?php echo $websiteSettings->websitename; ?> 
            </a>
            <div class="visible-xs toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
                <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
            </div>
        </div>

    </div>
    <!-- end: search & user box -->
</header>


<script>
    $(function () {
        $("#headersearchquery").autocomplete({
            minLength: 0,
            source: function (query, response) {
                var that = this;
                console.log(query.term);
                console.log("<?php echo $this->url->get("api/") ?>searchuser/" + query.term);
                $.ajax({
                    type: "post",
                    url: "<?php echo $this->url->get("api/") ?>searchuser/" + query.term,
                    success: function (output) {
                        response(JSON.parse(output));
                    }
                    ,
                    error: function (a, b, c)
                    {

                    }
                });

            },
            focus: function (event, ui) {
                $("#project").val(ui.item.label);
                return false;
            },
            select: function (event, ui) {
                $("#project").val(ui.item.label);
                $("#project-id").val(ui.item.value);
                $("#project-description").html(ui.item.desc);
                $("#project-icon").attr("src", "images/" + ui.item.icon);

                return false;
            }
        }).autocomplete("instance")._renderItem = function (ul, item) {
            console.log(item);
            var link = "<?php echo $this->url->get("user/view/") ?>" + item.userid;
            $item = $("<div class='media _header_search_item'><a href=''><img class='media-object pull-left _header_search_profileimage'><div class='media-body'><h5 class='media-heading' id='title'>title</h5><p id='info'>body</p></div></a></div>");
            $item.find("img").attr("src", item.imagelink);
            $item.find("#title").html(item.fullname);
            $item.find("#info").html("userid : " + item.userid);
            $item.find("a").attr("href", link);
            return $item.appendTo(ul);
        };
    });
</script>
