<aside id="sidebar-left" class="sidebar-left">

    <div class="sidebar-header">
        <div class="sidebar-title">
            Navigation
        </div>
        <div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
            <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
        </div>
    </div>

    <div class="nano">
        <div class="nano-content">
            <nav id="menu" class="nav-main" role="navigation">
                <ul class="nav nav-main">
                    <li>
                        <a href="<?php echo $this->url->get(""); ?>">
                            <i class="fa fa-home" aria-hidden="true"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-archive" aria-hidden="true"></i>
                            <span>Logs</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("userlogs/list"); ?>">
                                    User Logs
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("systemlog/list"); ?>">
                                    System Logs
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                            <span>Contact</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("contact/list"); ?>">
                                    <span class="pull-right label label-primary"><?php echo $totalContactsUnanswered; ?></span>
                                    All
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("contact/unanswered"); ?>">
                                    Unanswered
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("contact/sent"); ?>">
                                    Sent
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("contact/sendbulk"); ?>">
                                    Send Bulk Email
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-eye" aria-hidden="true"></i>
                            <span>Track</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("track/visits"); ?>">
                                    Visits
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("track/login"); ?>">
                                    Logins
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-envelope-square" aria-hidden="true"></i>
                            <span>Email Template</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("emailtemplate/list"); ?>">
                                    List
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("emailtemplate/add"); ?>">
                                    Add
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-image" aria-hidden="true"></i>
                            <span>Images</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("image/list"); ?>">
                                    List
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("image/add"); ?>">
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("image/upload"); ?>">
                                    Upload
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-adjust" aria-hidden="true"></i>
                            <span>Site Info</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("siteinfo/info"); ?>">
                                    <span>Website Information</span>
                                </a>
                            </li>
                            <li>
                            <li>
                                <a href="<?php echo $this->url->get("siteinfo/footer"); ?>">
                                    <span>Footer</span>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("siteinfo/changestate"); ?>">
                                    <span>Enable\Disable Site</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-users" aria-hidden="true"></i>
                            <span>Users</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("user/list"); ?>">
                                    List Users
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("user/most"); ?>">
                                    Most Active
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-search" aria-hidden="true"></i>
                            <span>Search</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("searchhistory/list"); ?>">
                                    Search History
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("searchhistory/view"); ?>">
                                    Statistics
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("search/changestate"); ?>">
                                    Enable\Disable Search
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-question" aria-hidden="true"></i>
                            <span>FAQ'S</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("faq/add"); ?>">
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("faq/list"); ?>">
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <hr class="separator" />
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>Payment Payline's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('paymentpayline/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('paymentpayline/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>Orders</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('userorder/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('userorder/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>Transactions</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('usertransaction/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('usertransaction/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>PaymentType's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('paymenttype/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('paymenttype/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>ProductType's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('producttype/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('producttype/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>Transaction Type's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('transactiontype/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('transactiontype/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>UserCachChange's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('usercachchange/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('usercachchange/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>CachChangeReason's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('cachchangereason/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('cachchangereason/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <hr class="separator" />
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-comment" aria-hidden="true"></i>
                            <span>Opinion's</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("opinion/add"); ?>">
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("opinion/list"); ?>">
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-mobile' aria-hidden='true'></i>
                            <span>SMS Manager</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('index/sendsms'); ?>'>
                                    Send SMS
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('sentsms/list'); ?>'>
                                    View Sent History
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('smsnumber/add'); ?>'>
                                    Add SMS Number
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('smsprovider/add'); ?>'>
                                    Add SMS Provider
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('smsnumber/list'); ?>'>
                                    View SMS Numbers
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('smsprovider/list'); ?>'>
                                    View SMS Providers
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-dropbox" aria-hidden="true"></i>
                            <span>Backup</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                            <li>
                                <a href="<?php echo $this->url->get("backup/list"); ?>">
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>

            </nav>

            <!--            <hr class="separator" />
            
                        <div class="sidebar-widget widget-tasks">
                            <div class="widget-header">
                                <h6>Projects</h6>
                                <div class="widget-toggle">+</div>
                            </div>
                            <div class="widget-content">
                                <ul class="list-unstyled m-none">
                                    <li><a href="#">Porto HTML5 Template</a></li>
                                    <li><a href="#">Tucson Template</a></li>
                                    <li><a href="#">Porto Admin</a></li>
                                </ul>
                            </div>
                        </div>
            
                        <hr class="separator" />
            
                        <div class="sidebar-widget widget-stats">
                            <div class="widget-header">
                                <h6>Company Stats</h6>
                                <div class="widget-toggle">+</div>
                            </div>
                            <div class="widget-content">
                                <ul>
                                    <li>
                                        <span class="stats-title">Stat 1</span>
                                        <span class="stats-complete">85%</span>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-primary progress-without-number" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 85%;">
                                                <span class="sr-only">85% Complete</span>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <span class="stats-title">Stat 2</span>
                                        <span class="stats-complete">70%</span>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-primary progress-without-number" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%;">
                                                <span class="sr-only">70% Complete</span>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <span class="stats-title">Stat 3</span>
                                        <span class="stats-complete">2%</span>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-primary progress-without-number" role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="100" style="width: 2%;">
                                                <span class="sr-only">2% Complete</span>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>-->
        </div>

    </div>

</aside>