<aside id="sidebar-left" class="sidebar-left">

    <div class="sidebar-header">
        <div class="sidebar-title">
            Navigation
        </div>
        <div class="sidebar-toggle hidden-xs" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
            <i class="fa fa-bars" aria-label="Toggle sidebar"></i>
        </div>
    </div>

    <div class="nano">
        <div class="nano-content">
            <nav id="menu" class="nav-main" role="navigation">
                <ul class="nav nav-main">
                    <li>
                        <a href="<?php echo $this->url->get(""); ?>">
                            <i class="fa fa-bank" aria-hidden="true"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-building' aria-hidden='true'></i>
                            <span>مشاور املاک</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('bongah/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('bongah/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-home' aria-hidden='true'></i>
                            <span>املاک</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('melk/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('melk/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-building' aria-hidden='true'></i>
                            <span>املاک درخواستی</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('melkphonelistner/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('melkphonelistner/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-mobile-phone' aria-hidden='true'></i>
                            <span>شماره موبایل</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('userphone/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('userphone/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>دانلود برنامه</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('appdownload/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('appdownload/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>


                    <hr class="separator"/>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>MelkInfo's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('melkinfo/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('melkinfo/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>MelkArea's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('melkarea/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('melkarea/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>




                    <hr class="separator"/>

                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>BongahSubscribeItem's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('bongahsubscribeitem/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('bongahsubscribeitem/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>Bongah Image</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('bongahimage/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('bongahimage/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>BongahSubscriber's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('bongahsubscriber/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('bongahsubscriber/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>bongaharea's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('bongaharea/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('bongaharea/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>BongahSentMessage's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('bongahsentmessage/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('bongahsentmessage/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>Bongah Sent Melk's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('bongahsentmelk/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('bongahsentmelk/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>BongahAmlakKeshvar's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('bongahamlakkeshvar/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('bongahamlakkeshvar/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <hr class="separator"/>

                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>State's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('state/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('state/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>City's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('city/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('city/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>Area's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('area/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('area/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>MelkType's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('melktype/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('melktype/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>MelkPurpose's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('melkpurpose/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('melkpurpose/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>



                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>MelkCreatedBy's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('melkcreatedby/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('melkcreatedby/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>MelkFacilities's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('melkfacilities/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('melkfacilities/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>MelkCondition's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('melkcondition/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('melkcondition/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>MelkImage's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('melkimage/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('melkimage/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>Melk Subscribe Item</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('melksubscribeitem/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('melksubscribeitem/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>MelkSubscriber's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('melksubscriber/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('melksubscriber/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>


                    <hr class="separator"/>
                    <!-- ADMIN ARE !-->
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-archive" aria-hidden="true"></i>
                            <span>Logs</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("userlogs/list"); ?>">
                                    User Logs
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("systemlog/list"); ?>">
                                    System Logs
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                            <span>Contact</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("contact/list"); ?>">
                                    <span class="pull-right label label-primary"><?php echo $totalContactsUnanswered; ?></span>
                                    All
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("contact/unseen"); ?>">
                                    New Messages
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("contact/unanswered"); ?>">
                                    Unanswered
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("contact/sent"); ?>">
                                    Sent
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("contact/sendbulk"); ?>">
                                    Send Bulk Email
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-eye" aria-hidden="true"></i>
                            <span>Track</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("track/visits"); ?>">
                                    Visits
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("track/login"); ?>">
                                    Logins
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-envelope-square" aria-hidden="true"></i>
                            <span>Email Template</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("emailtemplate/list"); ?>">
                                    List
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("emailtemplate/add"); ?>">
                                    Add
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-image" aria-hidden="true"></i>
                            <span>Images</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("image/list"); ?>">
                                    List
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("image/add"); ?>">
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("image/upload"); ?>">
                                    Upload
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-adjust" aria-hidden="true"></i>
                            <span>Site Info</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("siteinfo/info"); ?>">
                                    <span>Website Information</span>
                                </a>
                            </li>
                            <li>
                            <li>
                                <a href="<?php echo $this->url->get("siteinfo/footer"); ?>">
                                    <span>Footer</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-users" aria-hidden="true"></i>
                            <span>Users</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("user/list"); ?>">
                                    List Users
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("user/most"); ?>">
                                    Most Active
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>User Phone's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('userphone/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('userphone/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>Session's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('session/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('session/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-search" aria-hidden="true"></i>
                            <span>Search</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("searchhistory/list"); ?>">
                                    Search History
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("searchhistory/most"); ?>">
                                    Statistics
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-question" aria-hidden="true"></i>
                            <span>FAQ'S</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("faq/add"); ?>">
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("faq/list"); ?>">
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <hr class="separator" />
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-money' aria-hidden='true'></i>
                            <span>Payment's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('paymentpayline/list'); ?>'>
                                    Payline
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-dollar' aria-hidden='true'></i>
                            <span>Orders</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('userorder/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-list' aria-hidden='true'></i>
                            <span>Transactions</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('usertransaction/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-bars' aria-hidden='true'></i>
                            <span>User Cach Change's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('usercachchange/add'); ?>'>
                                    Increase Decrease User Cach
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('usercachchange/list'); ?>'>
                                    View List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-gear' aria-hidden='true'></i>
                            <span>Payment Settings</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('paymenttype/add'); ?>'>
                                    Add Payment Type
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('paymenttype/list'); ?>'>
                                    View Payment Types
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('producttype/add'); ?>'>
                                    Add Product Type
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('producttype/list'); ?>'>
                                    View Product Types
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('transactiontype/add'); ?>'>
                                    Add Transaction Type
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('transactiontype/list'); ?>'>
                                    View Transaction Types
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('cachchangereason/add'); ?>'>
                                    Add Cach Change Reason
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('cachchangereason/list'); ?>'>
                                    View User Cach Change 
                                </a>
                            </li>
                        </ul>
                    </li>

                    <hr class="separator" />
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-comment" aria-hidden="true"></i>
                            <span>Opinion's</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                                <a href="<?php echo $this->url->get("opinion/add"); ?>">
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo $this->url->get("opinion/list"); ?>">
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>

                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-mobile' aria-hidden='true'></i>
                            <span>SMS Manager</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('index/sendsms'); ?>'>
                                    Send SMS
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('sentsms/list'); ?>'>
                                    View Sent History
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('smsnumber/add'); ?>'>
                                    Add SMS Number
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('smsprovider/add'); ?>'>
                                    Add SMS Provider
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('smsnumber/list'); ?>'>
                                    View SMS Numbers
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('smsprovider/list'); ?>'>
                                    View SMS Providers
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('receivedsms/list'); ?>'>
                                    Received SMSs
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>ValidProviderIP's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('validproviderip/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('validproviderip/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>SMSCredit's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('smscredit/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('smscredit/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>SMSCreditChange's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('smscreditchange/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('smscreditchange/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>SMSCreditCost's</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('smscreditcost/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('smscreditcost/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>Mobile Token</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('mobiletoken/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('mobiletoken/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a>
                            <i class="fa fa-dropbox" aria-hidden="true"></i>
                            <span>Backup</span>
                        </a>
                        <ul class="nav nav-children">
                            <li>
                            <li>
                                <a href="<?php echo $this->url->get("backup/list"); ?>">
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>Mobile Notification</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('mobilenotification/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('mobilenotification/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-pencil-square' aria-hidden='true'></i>
                            <span><?= _("Agreements"); ?></span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('agreement/add'); ?>'>
                                    <?= _("Add"); ?>
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('agreement/list'); ?>'>
                                    <?= _("List"); ?>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-paperclip' aria-hidden='true'></i>
                            <span><?= _("Pages"); ?></span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('page/add'); ?>'>
                                    <?= _("Add"); ?>
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('page/list'); ?>'>
                                    <?= _("List"); ?>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>On Time Tokens</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('ontimetoken/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('ontimetoken/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class='nav-parent'>
                        <a>
                            <i class='fa fa-question' aria-hidden='true'></i>
                            <span>Articles</span>
                        </a>
                        <ul class='nav nav-children'>
                            <li>
                                <a href='<?php echo $this->url->get('article/add'); ?>'>
                                    Add
                                </a>
                            </li>
                            <li>
                                <a href='<?php echo $this->url->get('article/list'); ?>'>
                                    List
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>

            </nav>

            <!--            <hr class="separator" />
            
                        <div class="sidebar-widget widget-tasks">
                            <div class="widget-header">
                                <h6>Projects</h6>
                                <div class="widget-toggle">+</div>
                            </div>
                            <div class="widget-content">
                                <ul class="list-unstyled m-none">
                                    <li><a href="#">Porto HTML5 Template</a></li>
                                    <li><a href="#">Tucson Template</a></li>
                                    <li><a href="#">Porto Admin</a></li>
                                </ul>
                            </div>
                        </div>
            
                        <hr class="separator" />
            
                        <div class="sidebar-widget widget-stats">
                            <div class="widget-header">
                                <h6>Company Stats</h6>
                                <div class="widget-toggle">+</div>
                            </div>
                            <div class="widget-content">
                                <ul>
                                    <li>
                                        <span class="stats-title">Stat 1</span>
                                        <span class="stats-complete">85%</span>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-primary progress-without-number" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 85%;">
                                                <span class="sr-only">85% Complete</span>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <span class="stats-title">Stat 2</span>
                                        <span class="stats-complete">70%</span>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-primary progress-without-number" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%;">
                                                <span class="sr-only">70% Complete</span>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <span class="stats-title">Stat 3</span>
                                        <span class="stats-complete">2%</span>
                                        <div class="progress">
                                            <div class="progress-bar progress-bar-primary progress-without-number" role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="100" style="width: 2%;">
                                                <span class="sr-only">2% Complete</span>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>-->
        </div>

    </div>

</aside>
