<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>

                                                <h2 class='panel-title'>Add PurchasedBanner</h2>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD User ID !-->
                                <?php $form->renderDecorated('userid'); ?> 

                                <!--  ADD Valid Until !-->
                                <?php $form->renderDecorated('validuntil'); ?> 

                                <!--  ADD Order ID !-->
                                <?php $form->renderDecorated('orderid'); ?> 

                                <!--  ADD Advert ID !-->
                                <?php $form->renderDecorated('advertid'); ?> 

                                <!--  ADD City ID !-->
                                <?php $form->renderDecorated('cityid'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderDecorated('date'); ?> 

                                <!--  ADD Image ID !-->
                                <?php $form->renderDecorated('imageid'); ?> 

                                <!--  ADD Banner Type !-->
                                <?php $form->renderDecorated('banner_type'); ?> 


                                <!-- Submit Button !-->
                                <br/>
                                <?php $form->renderDecorated('submit'); ?>

</div>
            </section>
        </div>
    </div>
</form>


