<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel panel-primary'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>View MobileNotification</h2>
                    <p class='panel-subtitle'Use this form to edit your MobileNotification</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD ID !-->
                    <?php $form->renderInfo('id'); ?> 

                    <!--  ADD Title !-->
                    <?php $form->renderInfo('title'); ?> 

                    <!--  ADD Message !-->
                    <?php $form->renderInfo('message'); ?> 

                    <!--  ADD Link !-->
                    <?php $form->renderInfo('link'); ?> 

                    <!--  ADD Link Text !-->
                    <?php $form->renderInfo('linktext'); ?> 

                    <!--  ADD Date !-->
                    <?php $form->renderInfo('date'); ?> 

                    <!--  ADD Release Date !-->
                    <?php $form->renderInfo('releasedate'); ?> 

                    <!--  ADD Enable !-->
                    <?php $form->renderInfo('enable'); ?> 

                    <!--  ADD By IP !-->
                    <?php $form->renderInfo('byip'); ?> 


                </div>
            </section>
        </div>
    </div>
</form>


