<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>

                                                <h2 class='panel-title'>Add CreditChange</h2>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD User ID !-->
                                <?php $form->renderDecorated('userid'); ?> 

                                <!--  ADD Status !-->
                                <?php $form->renderDecorated('status'); ?> 

                                <!--  ADD Value !-->
                                <?php $form->renderDecorated('value'); ?> 

                                <!--  ADD Charge ID !-->
                                <?php $form->renderDecorated('chargeid'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderDecorated('date'); ?> 

                                <!--  ADD Message !-->
                                <?php $form->renderDecorated('message'); ?> 


                                <!-- Submit Button !-->
                                <br/>
                                <?php $form->renderDecorated('submit'); ?>

</div>
            </section>
        </div>
    </div>
</form>


