<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>

                                                <h2 class='panel-title'>Add UserOrder</h2>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD User ID !-->
                                <?php $form->renderDecorated('userid'); ?> 

                                <!--  ADD Type !-->
                                <?php $form->renderDecorated('type'); ?> 

                                <!--  ADD Item ID !-->
                                <?php $form->renderDecorated('itemid'); ?> 

                                <!--  ADD Payment Product Type !-->
                                <?php $form->renderDecorated('paymenttype'); ?> 

                                <!--  ADD Payment Item ID !-->
                                <?php $form->renderDecorated('paymentitemid'); ?> 

                                <!--  ADD price !-->
                                <?php $form->renderDecorated('price'); ?> 

                                <!--  ADD Price Currency !-->
                                <?php $form->renderDecorated('pricecurrency'); ?> 

                                <!--  ADD date !-->
                                <?php $form->renderDecorated('date'); ?> 


                                <!-- Submit Button !-->
                                <br/>
                                <?php $form->renderDecorated('submit'); ?>

</div>
            </section>
        </div>
    </div>
</form>


