<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <section class='panel panel-danger'>
                                <header class='panel-heading'>
                                    <div class='panel-actions'>
                                        <a href='#' class='fa fa-caret-down'></a>
                                        <a href='#' class='fa fa-times'></a>
                                    </div>
                                    <h2 class='panel-title'>Delete UserOrder </h2>
                                </header>
                                <div class='panel-body'>
                                    <p>Are you sure you want to remove this object?</p>
                                    <form method='post'>
                                        <input class='btn btn-danger' type='submit' name='delete' value='Delete' />
                                    </form>
                                </div>
                            </section>