<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel panel-primary'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>View InvoiceProducts</h2>
                    <p class='panel-subtitle'Use this form to edit your InvoiceProducts</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD ID !-->
                    <?php $form->renderInfo('id'); ?> 

                    <!--  ADD Invoice ID !-->
                    <?php $form->renderInfo('invoiceid'); ?> 

                    <!--  ADD Product ID !-->
                    <?php $form->renderInfo('productid'); ?> 

                    <!--  ADD Date !-->
                    <?php $form->renderInfo('date'); ?> 

                    <!--  ADD Count !-->
                    <?php $form->renderInfo('count'); ?> 

                    <!--  ADD Message !-->
                    <?php $form->renderInfo('message'); ?> 


                </div>
            </section>
        </div>
    </div>
</form>


