<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>

                                                <h2 class='panel-title'>Add MelkPhoneListner</h2>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD Purpose ID !-->
                                <?php $form->renderDecorated('melkpurposeid'); ?> 

                                <!--  ADD Type ID !-->
                                <?php $form->renderDecorated('melktypeid'); ?> 

                                <!--  ADD Bedroom Start !-->
                                <?php $form->renderDecorated('bedroom_start'); ?> 

                                <!--  ADD Bedroom End !-->
                                <?php $form->renderDecorated('bedroom_end'); ?> 

                                <!--  ADD Phone ID !-->
                                <?php $form->renderDecorated('phoneid'); ?> 

                                <!--  ADD Received Count !-->
                                <?php $form->renderDecorated('receivedcount'); ?> 

                                <!--  ADD Status !-->
                                <?php $form->renderDecorated('status'); ?> 

                                <!--  ADD Rent Price Start !-->
                                <?php $form->renderDecorated('rent_price_start'); ?> 

                                <!--  ADD Rent Price End !-->
                                <?php $form->renderDecorated('rent_price_end'); ?> 

                                <!--  ADD Rahn Start !-->
                                <?php $form->renderDecorated('rent_pricerahn_start'); ?> 

                                <!--  ADD Rahn End !-->
                                <?php $form->renderDecorated('rent_pricerahn_end'); ?> 

                                <!--  ADD Sale Start !-->
                                <?php $form->renderDecorated('sale_price_start'); ?> 

                                <!--  ADD Sale End !-->
                                <?php $form->renderDecorated('sale_price_end'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderDecorated('date'); ?> 

                                <!--  ADD City ID !-->
                                <?php $form->renderDecorated('cityid'); ?> 


                                <!-- Submit Button !-->
                                <br/>
                                <?php $form->renderDecorated('submit'); ?>

</div>
            </section>
        </div>
    </div>
</form>


