
<?php echo $this->getContent() ?>

<div align="right">
    <?php echo $this->tag->linkTo(array("user/new", "Create user")) ?>
</div>

<?php echo $this->tag->form(array("user/search", "autocomplete" => "off")) ?>

<div align="center">
    <h1>Search user</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="userid">Userid</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("userid", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="fname">Fname</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("fname", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="lname">Lname</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("lname", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="gender">Gender</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("gender", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="imagelink">Imagelink</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("imagelink", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="regdate">Regdate</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("regdate", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="active">Active</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("active", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="verified">Verified</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("verified", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton("Search") ?></td>
    </tr>
</table>

</form>
