<section class="panel">
    <header class="panel-heading">
        <div class="panel-actions">
            <a href="#" class="fa fa-caret-down"></a>
            <a href="#" class="fa fa-times"></a>
        </div>

        <h2 class="panel-title">Users List</h2>
    </header>
    <div class="panel-body">

        <?php
        echo $users->header;
        echo $users->table;
        echo $users->footer;
        ?>

    </div>
</section>


