
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("user/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("user", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit user</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="fname">Fname</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("fname", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="lname">Lname</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("lname", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="gender">Gender</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("gender", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="imagelink">Imagelink</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("imagelink", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="regdate">Regdate</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textField(array("regdate", "type" => "date")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="active">Active</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("active", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="verified">Verified</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("verified", "type" => "number")) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
