<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>Edit Area</h2>
                                                <p class='panel-subtitle'Use this form to edit your Area</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD City ID !-->
                                <?php $form->renderDecorated('cityid'); ?> 

                                <!--  ADD Name !-->
                                <?php $form->renderDecorated('name'); ?> 

                                <!--  ADD By User !-->
                                <?php $form->renderDecorated('byuserid'); ?> 

                                <!--  ADD Enable !-->
                                <?php $form->renderDecorated('enable'); ?> 


                                <!-- Submit Button !-->
                                <br/>
                                <?php $form->renderDecorated('submit'); ?>

</div>
            </section>
        </div>
    </div>
</form>


