<div class="row">
    <div class="col-md-12">
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method="post">
    <div class="row">
        <div class="col-lg-12">
            <section class="panel">
                <header class="panel-heading">
                    <div class="panel-actions">
                        <a href="#" class="fa fa-caret-down"></a>
                        <a href="#" class="fa fa-times"></a>
                    </div>

                    <h2 class="panel-title">View FAQ</h2>
                </header>
                <div class="panel-body">

                    <!-- Head !-->
                    <?php $form->renderInfo("head"); ?>

                    <!-- Title !-->
                    <?php $form->renderInfo("title"); ?>

                    <!-- Message !-->
                    <?php $form->renderInfo("message"); ?>

                </div>
            </section>
        </div>
    </div>
</form>