<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel panel-primary'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>View Melk</h2>
                    <p class='panel-subtitle'Use this form to edit your Melk</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD ID !-->
                    <?php $form->renderInfo('id'); ?> 

                    <!--  ADD Valid Date !-->
                    <?php $form->renderInfo('validdate'); ?> 

                    <!--  ADD User ID !-->
                    <?php $form->renderInfo('userid'); ?> 

                    <!--  ADD Type !-->
                    <?php $form->renderInfo('melktypeid'); ?> 

                    <!--  ADD Purpose !-->
                    <?php $form->renderInfo('melkpurposeid'); ?> 

                    <!--  ADD Condition !-->
                    <?php $form->renderInfo('melkconditionid'); ?> 

                    <!--  ADD Home Size !-->
                    <?php $form->renderInfo('home_size'); ?> 

                    <!--  ADD Lot Size !-->
                    <?php $form->renderInfo('lot_size'); ?> 

                    <!--  ADD Sale Price !-->
                    <?php $form->renderInfo('sale_price'); ?> 

                    <!--  ADD Price Per Unit !-->
                    <?php $form->renderInfo('price_per_unit'); ?> 

                    <!--  ADD Ejare !-->
                    <?php $form->renderInfo('rent_price'); ?> 

                    <!--  ADD Rahn !-->
                    <?php $form->renderInfo('rent_pricerahn'); ?> 

                    <!--  ADD Bedrooms !-->
                    <?php $form->renderInfo('bedroom'); ?> 

                    <!--  ADD Bath !-->
                    <?php $form->renderInfo('bath'); ?> 

                    <!--  ADD State ID !-->
                    <?php $form->renderInfo('stateid'); ?> 

                    <!--  ADD City ID !-->
                    <?php $form->renderInfo('cityid'); ?> 

                    <!--  ADD Create By !-->
                    <?php $form->renderInfo('createby'); ?> 

                    <!--  ADD Featured !-->
                    <?php $form->renderInfo('featured'); ?> 

                    <!--  ADD Approved !-->
                    <?php $form->renderInfo('approved'); ?> 

                    <!--  ADD Date !-->
                    <?php $form->renderInfo('date'); ?> 


                </div>
            </section>
        </div>
    </div>
</form>


