<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel panel-default'>
                <header class='panel-heading'>
                    <h2 class='panel-title'>افزودن اجازه ارسال</h2>
                </header>
                <div class='panel-body'>
                    <!--  ADD User Post From !-->
                    <?php $form->renderDecorated('userpost1'); ?> 

                    <!--  ADD User Post To !-->
                    <?php $form->renderDecorated('userpost2'); ?> 

                    <!--  ADD Can Send !-->
                    <?php $form->renderDecorated('cansend'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


