<div class='row'>
    <div class='col-md-6'>
        <h1><?= _("Verify Phone Number"); ?></h1>
        <hr/>
        <?php echo $this->getContent(); ?>
        <div class='alert alert-info'>
            <h3 style="margin-top: 0px;"><?= _("Phone Already Verified"); ?></h3>
            <p><?= _("This phone number already verified and do not need to verify again!"); ?></p>
        </div>
    </div>
</div>