<?php if ($show == 1) : ?>
    <div class='row'>
        <div class='col-md-6'>
            <h1>Verify Phone Number</h1>
            <hr/>
            <?php echo $this->getContent(); ?>
            <form method="post">
                <!-- Verify Code !-->
                <?php echo $form->renderDecorated('verifycode', '300px'); ?>
                <?php echo $form->renderDecorated('submit'); ?>
            </form>
            <!-- Resend !-->
            <hr/>
            <p>If you have not received any message yet, click on this button to resend verification number again:</p>
            <form method="post">
                <input type='hidden' name='resend' value='1'/>
                <input type='submit' class='btn btn-success' value='Resend Verification Number'>
            </form>
        </div>
    </div>
<?php else : ?>
<?php endif; ?>