<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>
                                                <h2 class='panel-title'>Edit BongahAction</h2>
                                                <p class='panel-subtitle'Use this form to edit your BongahAction</p>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD Bongah ID !-->
                                <?php $form->renderDecorated('bongahid'); ?> 

                                <!--  ADD Action Code !-->
                                <?php $form->renderDecorated('actioncode'); ?> 

                                <!--  ADD Data !-->
                                <?php $form->renderDecorated('data'); ?> 

                                <!--  ADD Date !-->
                                <?php $form->renderDecorated('date'); ?> 


                                <!-- Submit Button !-->
                                <br/>
                                <?php $form->renderDecorated('submit'); ?>

</div>
            </section>
        </div>
    </div>
</form>


