<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<!-- User Charts !-->
<div class="row">
    <div class="col-md-12">
        <section class="panel">
            <header class="panel-heading">
                <div class="panel-actions">
                    <a href="#" class="fa fa-caret-down"></a>
                    <a href="#" class="fa fa-times"></a>
                </div>

                <h2 class="panel-title">Logins</h2>
                <p class="panel-subtitle">visit user logins</p>
            </header>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-condensed mb-none ">
                        <tr>
                            <th>User ID</th>
                            <th>Name</th>
                            <th>Date</th>
                            <th>Agent</th>
                            <th>IP</th>
                            <th>Action</th>
                        </tr>
                        <?php foreach ($users->items as $item) { ?>
                            <tr>
                                <td><?php echo $item->userid; ?></td>
                                <td><a href="<?php echo $this->url->get("track/uservisits/") . $item->userid ?>"><?php echo $item->getUser()->getFullName(); ?></a></td>
                                <td><?php echo $item->getDate(); ?></td>
                                <td><?php echo $item->agent; ?></td>
                                <td><?php echo $item->ip; ?></td>
                                <td>
                                    <a href="<?php echo $this->url->get("track/login/" . $item->userid); ?>" class="on-default edit-row"><i class="fa fa-pencil"></i></a>
                                </td>
                            </tr>
                        <?php } ?>
                    </table>
                </div>
                <!-- Paginatoing Items !-->
                <div class="center">
                    <div class="pagination pagination-centered">
                        <li><a class="pag" href="<?php echo $this->url->get("track/login/") ?>">First</a> </li>
                        <li> <a href="<?php echo $this->url->get("track/login/$users->before") ?>">Previous</a></li>
                        <li> <a href="<?php echo $this->url->get("track/login/$users->next") ?>">Next</a></li>
                        <li> <a href="<?php echo $this->url->get("track/login/$users->last") ?>">Last</a></li>
                    </div>
                    <div>
                        <?php echo "You are in page ", $users->current, " of ", $users->total_pages; ?>
                    </div>
                </div>
            </div>
        </section>
    </div>

</div>