<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>Edit SMSProvider</h2>
                    <p class='panel-subtitle'Use this form to edit your SMSProvider</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD Name !-->
                    <?php $form->renderDecorated('name'); ?> 

                    <!--  ADD Description !-->
                    <?php $form->renderDecorated('description'); ?> 

                    <!--  ADD Infos !-->
                    <?php $form->renderDecorated('infos'); ?> 

                    <!--  ADD Date !-->
                    <?php $form->renderDecorated('date'); ?> 

                    <!--  ADD Website URL !-->
                    <?php $form->renderDecorated('websitename'); ?> 

                    <!--  ADD Enable !-->
                    <?php $form->renderDecorated('enable'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


