<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>
                    <h2 class='panel-title'>Edit Article</h2>
                    <p class='panel-subtitle'Use this form to edit your Article</p>
                </header>
                <div class='panel-body'>



                    <!--  ADD Title !-->
                    <?php $form->renderDecorated('title'); ?> 

                    <!--  ADD Text !-->
                    <?php $form->renderDecorated('text'); ?> 

                    <!--  ADD User ID !-->
                    <?php $form->renderDecorated('userid'); ?> 

                    <!--  ADD Date !-->
                    <?php $form->renderDecorated('date'); ?> 

                    <!--  ADD Approved !-->
                    <?php $form->renderDecorated('approved'); ?> 

                    <!--  ADD Approved !-->
                    <?php $form->renderDecorated('link'); ?> 

                    <!--  ADD Delete !-->
                    <?php $form->renderDecorated('delete'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


