<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post'>
    <div class='row'>
        <div class='col-lg-12'>
            <section class='panel'>
                <header class='panel-heading'>
                    <div class='panel-actions'>
                        <a href='#' class='fa fa-caret-down'></a>
                        <a href='#' class='fa fa-times'></a>
                    </div>

                    <h2 class='panel-title'>Add Invoice</h2>
                </header>
                <div class='panel-body'>



                    <!--  ADD User ID !-->
                    <?php $form->renderDecorated('userid'); ?> 

                    <!--  ADD Price !-->
                    <?php $form->renderDecorated('price'); ?> 

                    <!--  ADD Currency !-->
                    <?php $form->renderDecorated('currency'); ?> 

                    <!--  ADD Status !-->
                    <?php $form->renderDecorated('status'); ?> 

                    <!--  ADD User Status !-->
                    <?php $form->renderDecorated('user_status'); ?> 

                    <!--  ADD City ID !-->
                    <?php $form->renderDecorated('cityid'); ?> 

                    <!--  ADD Address !-->
                    <?php $form->renderDecorated('address'); ?> 

                    <!--  ADD User Comment !-->
                    <?php $form->renderDecorated('usercomment'); ?> 

                    <!--  ADD Address Longitude !-->
                    <?php $form->renderDecorated('address_longitude'); ?> 

                    <!--  ADD Address Latitude !-->
                    <?php $form->renderDecorated('address_latitude'); ?> 

                    <!--  ADD Address GPSApprox !-->
                    <?php $form->renderDecorated('address_gpsapprox'); ?> 

                    <!--  ADD Phone !-->
                    <?php $form->renderDecorated('phone'); ?> 

                    <!--  ADD Mobile !-->
                    <?php $form->renderDecorated('mobile'); ?> 

                    <!--  ADD Deliver Date !-->
                    <?php $form->renderDecorated('deliverdate'); ?> 


                    <!-- Submit Button !-->
                    <br/>
                    <?php $form->renderDecorated('submit'); ?>

                </div>
            </section>
        </div>
    </div>
</form>


