<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<div class='row'>
    <div class='col-md-12'>
        <ul>
            <?php foreach ($list->items as $article) : ?>
                <li>
                    <h3><a href="<?php echo $this->url->get("article/view/$article->id"); ?>"><?php echo $article->title; ?></a></h3>
                    <p class='last-article-date'><?php echo $article->getDate(); ?></p>
                </li>
            <?php endforeach; ?>
        </ul>
        <?php
        echo $list->footer;
        ?>
    </div>
</div>