<div class='row'>
                                <div class='col-md-12'>
                                    <?php echo $this->getContent() ?>
                                </div>
                            </div>
                            <form method='post'>
                                <div class='row'>
                                    <div class='col-lg-12'>
                                        <section class='panel'>
                                            <header class='panel-heading'>
                                                <div class='panel-actions'>
                                                    <a href='#' class='fa fa-caret-down'></a>
                                                    <a href='#' class='fa fa-times'></a>
                                                </div>

                                                <h2 class='panel-title'>Add BongahAmlakKeshvar</h2>
                                            </header>
                                            <div class='panel-body'>

                             

                                <!--  ADD State !-->
                                <?php $form->renderDecorated('state'); ?> 

                                <!--  ADD City !-->
                                <?php $form->renderDecorated('city'); ?> 

                                <!--  ADD Name !-->
                                <?php $form->renderDecorated('name'); ?> 

                                <!--  ADD Code !-->
                                <?php $form->renderDecorated('code'); ?> 

                                <!--  ADD Phone !-->
                                <?php $form->renderDecorated('phone'); ?> 

                                <!--  ADD Mobile !-->
                                <?php $form->renderDecorated('mobile'); ?> 

                                <!--  ADD Address !-->
                                <?php $form->renderDecorated('address'); ?> 

                                <!--  ADD City ID !-->
                                <?php $form->renderDecorated('cityid'); ?> 

                                <!--  ADD State ID !-->
                                <?php $form->renderDecorated('stateid'); ?> 


                                <!-- Submit Button !-->
                                <br/>
                                <?php $form->renderDecorated('submit'); ?>

</div>
            </section>
        </div>
    </div>
</form>


