<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<script>
    window.saleValuesMap = [<?php echo implode(", ", $salePriceOptions); ?>];
    window.rahnValuesMap = [<?php echo implode(", ", $largePriceOptions); ?>];
    window.ejareValuesMap = [<?php echo implode(", ", $smallPriceOptions); ?>];

</script>  
<form method='post' enctype="multipart/form-data">
    <div class='row request-melk-page'>
        <div class='col-md-12'>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">درخواست ملک</h3>
                </div>
                <div class="panel-body">
                    <p class="hidden">مشخصات ملک مورد نیاز خود را وارد نمایید تا در هنگام دریافت ملک جدید متناسب با درخواست شما،  <span style="color:red;font-weight: bold">رایگان</span> توسط پیامک مطلع گردید.</p>
                    <p>دیگر نیازی به خواندن روزنامه یا مراجعه به بنگاه نیست، مشخصات ملک مورد نظر خود را وارد نمایید تا املاک متناسب را   <span style="color:red;font-weight: bold">رایگان</span> توسط پیامک دریافت نمایید.</p>
                    <hr/>
                    <div class='row'>
                        <div class='col-md-6'>
                            <div class="panel panel-default">
                                <div class="panel-heading  hidden-sm hidden-xs">
                                    <h4 class="panel-title">مشخصات ملک مورد نظر</h4>
                                </div>
                                <div class="panel-body">
                                    <!-- Type Selection !-->
                                    <div class='row'>
                                        <div class='col-md-6'>
                                            <!--  ADD Type !-->
                                            <?php $form->renderDecorated('melktypeid'); ?> 

                                        </div>
                                        <div class='col-md-6'>
                                            <!--  ADD Purpose !-->
                                            <?php $form->renderDecorated('melkpurposeid'); ?> 

                                        </div>
                                    </div>

                                    <hr/>
                                    <!-- Range Infos !-->
                                    <div data-colname="bedroom_range" class='col-md-12'>
                                        <?php $form->renderDecorated('bedroom_range'); ?>
                                    </div>

                                    <div data-colname="sale_range" class='col-md-12'>
                                        <?php $form->renderDecorated('sale_range'); ?> 
                                    </div>

                                    <div data-colname="rahn_range" class='col-md-12'>
                                        <?php $form->renderDecorated('rahn_range'); ?> 
                                    </div>

                                    <div data-colname="ejare_range" class='col-md-12'>
                                        <?php $form->renderDecorated('ejare_range'); ?> 
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class='col-md-6'>
                            <!-- Location Info !-->
                            <div class="panel panel-default">
                                <div class="panel-heading  hidden-sm hidden-xs">
                                    <h4 class="panel-title">موقعیت ملک</h4>
                                </div>
                                <div class="panel-body">
                                    <div class='row'>
                                        <div class='col-md-12'>
                                            <div class='row'>
                                                <div class='col-md-6'>
                                                    <!--  ADD State ID !-->
                                                    <?php $form->renderDecorated('stateid'); ?> 
                                                </div>
                                                <div class='col-md-6'>
                                                    <!--  ADD City ID !-->
                                                    <?php $form->renderDecorated('cityid'); ?> 
                                                </div>
                                            </div>
                                            <!--  ADD Address !-->
                                            <?php $form->renderDecorated('address'); ?> 
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <!-- Contact Info !-->
                            <div class="panel panel-default">
                                <div class="panel-heading hidden-sm hidden-xs">
                                    <h4 class="panel-title">شماره تماس</h4>
                                </div>
                                <div class="panel-body">
                                    <!--  ADD Mobile !-->
                                    <?php $form->renderDecorated('mobile'); ?> 
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr/>
                    <div class="center">
                        <p>برای ارسال اطلاعات ملک درخواستی بر روی کلید زیر کیلک نمایید</p>
                        <?php $form->renderDecorated('submit'); ?> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>


    // hide all steps at start
    $(".melk-step-panel").hide();
    /**
     * this function will go to the requestd step without any validate
     * @param {type} newStep
     * @param {type} oldStep
     * @returns {undefined}
     */
    function showStep(newStep, oldStep)
    {
        // hide all steps at first time
        $(".melk-step-panel[data-step='" + oldStep + "']").fadeOut(250, function() {
            $(".melk-step-panel[data-step='" + newStep + "']").fadeIn(250, function() {

            });
        });
        // show in wizard mode
        $(".melk-wizard-step[data-step='" + oldStep + "']").removeClass('active').addClass("done");
        $(".melk-wizard-step[data-step='" + newStep + "']").addClass('active').removeClass("done");


        $('html, body').animate({scrollTop: 0}, 400);
        return false;

    }

    /**
     * this function will ready step
     * @param {type} step
     * @returns {undefined}
     */
    function readyStep(step)
    {
        if (step == 2)
        {
            // get melk type
            // we have to show all optiosn first
            $("#lot_size_holder").show();
            $("#bedroom_holder").show();
            $("#bath_holder").show();
            $("#home_size_holder").show();
            switch ($("#melktypeid").val())
            {
                case "1":
                    // khane
                    break;
                case "2":
                    // aparteman
                    $("#lot_size_holder").hide();
                    break;
                case "3":
                    // daftar kar
                    $("#bath_holder").hide();
                    $("#lot_size_holder").hide();
                    break;
                case "4":
                    // vila
                    break;
                case "5":
                    // zamin
                    $("#bedroom_holder").hide();
                    $("#bath_holder").hide();
                    $("#home_size_holder").hide();
                    break;
                case "6":
                    // otaghe kar
                    $("#lot_size_holder").hide();
                    $("#bedroom_holder").hide();
                    $("#bath_holder").hide();
                    break;
                default:
                    // Type Is Not valid
                    alert("نوع ملک معتبر نمیباشد");
                    break;
            }


            // check for purpose
            switch ($("#melkpurposeid").val())
            {
                case "1":
                    // forosh
                    $("#sale_price_start_holder").show();
                    $("#sale_price_end_holder").show();

                    $("#rent_price_start_holder").hide();
                    $("#rent_price_end_holder").hide();

                    $("#rent_pricerahn_start_holder").hide();
                    $("#rent_pricerahn_end_holder").hide();
                    break;
                case "2":
                    // ejare
                    $("#sale_price_start_holder").hide();
                    $("#sale_price_end_holder").hide();

                    $("#rent_price_start_holder").show();
                    $("#rent_price_end_holder").show();

                    $("#rent_pricerahn_start_holder").show();
                    $("#rent_pricerahn_end_holder").show();
                    break;
                case "3":
                    // forosh va ejare
                    $("#sale_price_start_holder").show();
                    $("#sale_price_end_holder").show();

                    $("#rent_price_start_holder").show();
                    $("#rent_price_end_holder").show();

                    $("#rent_pricerahn_start_holder").show();
                    $("#rent_pricerahn_end_holder").show();
                    break;
                default:
                    // Type Is Not valid
                    alert("منظور ملک معتبر نمیباشد");
                    break;
            }
        }


        if (step == 3)
        {

        }



        if (step == 4)
        {

        }


        if (step == 5)
        {

        }


        if (step == 6)
        {

        }
    }

    /**
     * this function will validate step
     * @param {type} step
     * @returns {undefined}
     */
    function validStep(step) {

        // step one is choose type and purpose
        if (step == 2)
        {
            // Moshakasatee Melk
            switch ($("#melktypeid").val())
            {
                case "1":
                    // khane
                    if ($("#home_size").val() == "")
                    {
                        alert("مقدار سایز خانه را وارد نمایید");
                        return false;
                    }

                    if ($("#lot_size").val() == "")
                    {
                        alert("مقدار متراژ زمین را وارد نمایید");
                        return false;
                    }

                    break;
                case "2":
                    // aparteman
                    if ($("#home_size").val() == "")
                    {
                        alert("متراژ آپارتمان را وارد نمایید");
                        return false;
                    }

                    break;
                case "3":
                    // daftar kar
                    if ($("#home_size").val() == "")
                    {
                        alert("متراژ دفتر را وارد نمایید");
                        return false;
                    }
                    break;
                case "4":
                    // vila
                    if ($("#lot_size").val() == "")
                    {
                        alert("مقدار متراژ زمین را وارد نمایید");
                        return false;
                    }
                    break;
                case "5":
                    // zamin
                    if ($("#lot_size").val() == "")
                    {
                        alert("مقدار متراژ زمین را وارد نمایید");
                        return false;
                    }
                    break;
                case "6":
                    // otaghe kar
                    if ($("#home_size").val() == "")
                    {
                        alert("متراژ اتاق را وارد نمایید");
                        return false;
                    }
                    break;
                default:
                    // Type Is Not valid
                    alert("نوع ملک معتبر نمیباشد");
                    break;
            }



        }
        if (step == 3)
        {
            // Moghiyate  Melk
            if ($("#address").val() == "")
            {
                alert("حداقل یک منطقه را وارد نمایید");
                return false;
            }
            // Moghiyate  Melk
            if ($("#private_address").val() == "")
            {
                alert("آدرس دقیق ملک را وارد نمایید");
                return false;
            }
        }
        if (step == 4)
        {
            // Gheymat  Melk
            // check for purpose
            switch ($("#melkpurposeid").val())
            {
                case "1":
                    // forosh
                    if ($("#sale_price").val() == "")
                    {
                        alert("قیمت ملک را وارد نمایید");
                        return false;
                    }
                    break;
                case "2":
                    // ejare

                    if ($("#rent_pricerahn").val() == "")
                    {
                        alert("قیمت رهن را وارد نمایید");
                        return false;
                    }

                    if ($("#rent_price").val() == "")
                    {
                        alert("قیمت اجاره را وارد نمایید");
                        return false;
                    }

                    break;
                case "3":
                    // forosh va ejare
                    if ($("#sale_price").val() == "")
                    {
                        alert("قیمت ملک را وارد نمایید");
                        return false;
                    }

                    if ($("#rent_pricerahn").val() == "")
                    {
                        alert("قیمت رهن را وارد نمایید");
                        return false;
                    }

                    if ($("#rent_price").val() == "")
                    {
                        alert("قیمت اجاره را وارد نمایید");
                        return false;
                    }
                    break;
                default:
                    // Type Is Not valid
                    alert("منظور ملک معتبر نمیباشد");
                    break;
            }
        }

        if (step == 6)
        {
            // Etelate Tamas
            if ($("#private_phone").val() == "")
            {
                alert("تلفن تماس را وارد نمایید");
                return false;
            }

            if ($("#private_mobile").val() == "")
            {
                alert("شماره موبایل را وارد نمایید");
                return false;
            }
        }

        return true;
    }


    // add event on next button click
    $('body').on('click', '#nextbtn', function() {
        // get step
        var currenctStep = $(this).data('step');
        if (validStep(currenctStep))
        {
            readyStep(currenctStep + 1);
            showStep(currenctStep + 1, currenctStep);

        }

    });

    // add event on next button click
    $('body').on('click', '#backbtn', function() {
        // get step
        var currenctStep = $(this).data('step');
        showStep(currenctStep - 1, currenctStep);
    });
    // show step 1
    showStep(0, 0);


    function onPurposeChange() {
        $("div[data-colname='sale_range']").hide();

        $("div[data-colname='ejare_range']").hide();

        $("div[data-colname='rahn_range']").hide();


        switch ($("#melkpurposeid").val())
        {
            case "1":
                // forosh
                $("div[data-colname='sale_range']").show().focus();
                break;
            case "2":
                //  ejare
                $("div[data-colname='ejare_range']").show().focus();
                $("div[data-colname='rahn_range']").show();
                break;
            default:
                // Type Is Not valid
                alert("منظور ملک معتبر نمیباشد");
                break;
        }
    }

    function onMelkTypeChange() {
        // hide all fields 
        hideAll();

        switch ($("#melktypeid").val())
        {
            case "1":
                // khane
                $("div[data-colname='bedroom_range']").show();
                break;
            case "2":
                // aparteman
                $("div[data-colname='bedroom_range']").show();
                break;
            case "3":
                // daftar kar
                $("div[data-colname='bedroom_range']").show();
                break;
            case "4":
                // vila
                break;
            case "5":
                // zamin
                break;
            case "6":
                // otaghe kar
                $("div[data-colname='bedroom_range']").show();
                break;
            default:
                // Type Is Not valid
                alert("نوع ملک معتبر نمیباشد");
                break;
        }

    }

    function hideAll() {
        $("div[data-colname='bedroom_range']").hide();
    }

    $("#melkpurposeid").change(function() {
        onPurposeChange();
    });


    $("#melktypeid").change(function() {
        onMelkTypeChange();

        // focous on purpose
        $("#melkpurposeid").focus();
    });

    onPurposeChange();
    onMelkTypeChange();

</script>

<script>

    var citiesid = [];
    var cities = [];
<?php
foreach ($cities as $city) {
    echo "citiesid[$city->id] = \"$city->name\";\n";
    $ci = $city->getStateCitiesIDWithComma();
    echo "cities[$city->stateid] = \"$ci\";\n";
}
?>


    function onstatechange(selectedstate)
    {
        var ids = cities[selectedstate];
        var cityids = ids.split(",");
        // remove old cities
        var citylisteleemnt = $('#cityid');
        citylisteleemnt.find('option').remove().end();
        $.each(cityids, function(index, id) {
            if (index == 0)
            {
                oncitychange(citiesid[id]);
            }
            citylisteleemnt.append('<option value="' + id + '">' + citiesid[id] + '</option>');
        });

    }


    function oncitychange(city)
    {
        var state = $("#stateid").find("option:selected").text();
        var address = "ایران، " + city;

    }

    $("#stateid").change(function() {
        onstatechange(this.value);
    });

    $("#cityid").change(function() {
        var city = citiesid[$(this).val()];
        oncitychange(city);
    });


</script>

