<div class='row'>
    <div class='col-md-12'>
        <?php echo $this->getContent() ?>
    </div>
</div>
<form method='post' enctype="multipart/form-data">
    <div class='row'>
        <div class='col-lg-12'>

            <!-- Wizards -->
            <div class="nav nav-pills nav-justified navbar melk-wizard hidden-sm hidden-xs">
                <li data-step="0" class="melk-wizard-step active"><a href="#">توضیحات</a></li>
                <li data-step="1" class="melk-wizard-step"><a href="#"><span class="glyphicon glyphicon-home"></span>نوع ملک</a></li>
                <li data-step="2" class="melk-wizard-step "><a href="#"><span class="glyphicon glyphicon-pencil"></span>مشخصات ملک</a></li>
                <li data-step="3" class="melk-wizard-step "><a href="#"><span class="glyphicon glyphicon-map-marker"></span>موقعیت ملک</a></li>
                <li data-step="4" class="melk-wizard-step "><a href="#"><span class="fa fa-dollar"></span>قیمت</a></li>
                <li data-step="5" class="melk-wizard-step "><a href="#"><span class="glyphicon glyphicon-phone"></span>اطلاعات تماس</a></li>
            </div>


            <div class='row'>
                <div class='col-md-3'>

                </div>
                <div class='col-md-6'>
                    <!-- Tozihat  !-->
                    <div data-step="0" class="panel panel-default melk-step-panel" >
                        <div class="panel-heading">
                            <h3 class="panel-title">توضیحات</h3>
                        </div>
                        <div class="panel-body">
                            <p style="font-size: 22px;">بدون آنکه به بنگاه مراجعه نمایید، مشخصات ملک خود را وارد نمایید تا در هنگام دریافت ملک جدید متناسب با نیاز شما، توسط پیامک شما را مطلع گردانیم</p>
                            <p style="margin-top: 22px;" class="request-melk-info"><span class="fa fa-check-circle"></span> به رایگان مشخصات ملک درخواستی شما برای بنگاه داران ارسال خواهد گردید</p>
                            <p class="request-melk-info"><span class="fa fa-check-circle"></span> در هنگام اضافه شدن یک ملک جدید متناسب با نیاز شما، شما را توسط پیامک مطلع خواهیم نمود</p>
                            <p class="request-melk-info"><span class="fa fa-check-circle"></span> در هر زمان که دوست داشتید میتوانید برای عدم دریافت پیامک اقدام نمایید</p>
                        </div>
                        <div class="panel-footer panel-footer-btn-group">
                            <div id="nextbtn" data-step="0" class="btn btn-primary">شروع</div>
                        </div>
                    </div>


                    <!-- Noe Melk  !-->
                    <div data-step="1" class="panel panel-default melk-step-panel" >
                        <div class="panel-heading">
                            <h3 class="panel-title">نوع ملک</h3>
                        </div>
                        <div class="panel-body">
                            <p>لطفا نوع ملک و نوع درخواست را مشخص نمایید</p>
                            <!--  ADD Type !-->
                            <?php $form->renderDecorated('melktypeid'); ?> 

                            <!--  ADD Purpose !-->
                            <?php $form->renderDecorated('melkpurposeid'); ?> 
                        </div>
                        <div class="panel-footer panel-footer-btn-group">
                            <div id="nextbtn" data-step="1" class="btn btn-primary">مرحله بعد</div>
                        </div>
                    </div>


                    <!-- Moshakasate Melk !-->
                    <div data-step="2" class="panel panel-default melk-step-panel">
                        <div class="panel-heading">
                            <h3 class="panel-title">مشخصات ملک</h3>
                        </div>
                        <div class="panel-body">

                            <p>در صورت لزوم مشخصات زیر را پر نمایید</p>

                            <!--  ADD Bedrooms !-->
                            <?php $form->renderDecorated('bedroom_start'); ?> 
                            <?php $form->renderDecorated('bedroom_end'); ?> 

                        </div>
                        <div class="panel-footer panel-footer-btn-group">
                            <div id="nextbtn" data-step="2" class="btn btn-primary">مرحله بعد</div>
                            <div id="backbtn" data-step="2" class="btn btn-default">مرحله قبل</div>
                        </div>
                    </div>


                    <!--Moghiyate Melk !-->
                    <div data-step="3" class="panel panel-default melk-step-panel">
                        <div class="panel-heading">
                            <h3 class="panel-title">موقعیت ملک</h3>
                        </div>
                        <div class="panel-body">
                            <p>در این قسمت شما میبایست موقعیت و محدوده ملک را مشخص نمایید</p>

                            <div class='row'>
                                <div class='col-md-12'>
                                    <!--  ADD State ID !-->
                                    <?php $form->renderDecorated('stateid'); ?> 

                                    <!--  ADD City ID !-->
                                    <?php $form->renderDecorated('cityid'); ?> 

                                    <!--  ADD Address !-->
                                    <?php $form->renderDecorated('address'); ?> 

                                </div>
                            </div>
                        </div>
                        <div class="panel-footer panel-footer-btn-group">
                            <div id="nextbtn" data-step="3" class="btn btn-primary">مرحله بعد</div>
                            <div id="backbtn" data-step="3" class="btn btn-default">مرحله قبل</div>
                        </div>
                    </div>


                    <!--Gheymat !-->
                    <div data-step="4" class="panel panel-default melk-step-panel">
                        <div class="panel-heading">
                            <h3 class="panel-title">قیمت</h3>
                        </div>
                        <div class="panel-body">
                            <p>حداقل و حداکثر هزینه های ملک را وارد نمایید</p>

                            <!--  ADD Sale Price !-->
                            <?php $form->renderDecorated('sale_price_start'); ?> 
                            <?php $form->renderDecorated('sale_price_end'); ?> 

                            <!--  ADD Rahn !-->
                            <?php $form->renderDecorated('rent_pricerahn_start'); ?> 
                            <?php $form->renderDecorated('rent_pricerahn_end'); ?> 

                            <!--  ADD Ejare !-->
                            <?php $form->renderDecorated('rent_price_start'); ?> 
                            <?php $form->renderDecorated('rent_price_end'); ?> 

                        </div>
                        <div class="panel-footer panel-footer-btn-group">
                            <div id="nextbtn" data-step="4" class="btn btn-primary">مرحله بعد</div>
                            <div id="backbtn" data-step="4" class="btn btn-default">مرحله قبل</div>
                        </div>
                    </div>

                    <!-- Contact !-->
                    <div data-step="5" class="panel panel-default melk-step-panel">
                        <div class="panel-heading">
                            <h3 class="panel-title">اطلاعات تماس</h3>
                        </div>
                        <div class="panel-body">
                            <p>اطلاعات تماس مستقیم خودتان را وارد نمایید تا مشتریان و بنگاه داران بتوانند با شما تماس داشته باشند</p>

                            <!--  ADD Name !-->
                            <?php if (!$this->session->has("userid")) : ?>
                                <?php $form->renderDecorated('fname'); ?> 
                                <?php $form->renderDecorated('lname'); ?> 
                                <?php $form->renderDecorated('email'); ?> 
                                <?php $form->renderDecorated('password'); ?> 
                            <?php endif; ?>
                            
                            
                            <!--  ADD Mobile !-->
                            <?php $form->renderDecorated('mobile'); ?> 


                        </div>
                        <div class="panel-footer panel-footer-btn-group">
                            <div id="nextbtn" data-step="5" class="btn btn-primary">مرحله بعد</div>
                            <div id="backbtn" data-step="5" class="btn btn-default">مرحله قبل</div>
                        </div>
                    </div>


                    <!-- Finish  !-->
                    <div data-step="6" class="panel panel-default melk-step-panel" >
                        <div class="panel-heading">
                            <h3 class="panel-title">پایان</h3>
                        </div>
                        <div class="panel-body final-step">
                            <H1>پایان</H1>
                            <h3>برای ارسال نهایی درخواست بر روی کلید ارسال کلیک نمایید</h3>
                            <!-- Submit Button !-->
                            <br/>
                            <?php $form->renderDecorated('submit'); ?> 
                        </div>
                        <div class="panel-footer panel-footer-btn-group">
                            <div id="backbtn" data-step="6" class="btn btn-default">مرحله قبل</div>
                        </div>
                    </div>
                </div>
                <div class='col-md-3'>

                </div>
            </div>

        </div>
    </div>
</form>
<script>


    // hide all steps at start
    $(".melk-step-panel").hide();
    /**
     * this function will go to the requestd step without any validate
     * @param {type} newStep
     * @param {type} oldStep
     * @returns {undefined}
     */
    function showStep(newStep, oldStep)
    {
        // hide all steps at first time
        $(".melk-step-panel[data-step='" + oldStep + "']").fadeOut(250, function() {
            $(".melk-step-panel[data-step='" + newStep + "']").fadeIn(250, function() {

            });
        });
        // show in wizard mode
        $(".melk-wizard-step[data-step='" + oldStep + "']").removeClass('active').addClass("done");
        $(".melk-wizard-step[data-step='" + newStep + "']").addClass('active').removeClass("done");



    }

    /**
     * this function will ready step
     * @param {type} step
     * @returns {undefined}
     */
    function readyStep(step)
    {
        if (step == 2)
        {
            // get melk type
            // we have to show all optiosn first
            $("#lot_size_holder").show();
            $("#bedroom_holder").show();
            $("#bath_holder").show();
            $("#home_size_holder").show();
            switch ($("#melktypeid").val())
            {
                case "1":
                    // khane
                    break;
                case "2":
                    // aparteman
                    $("#lot_size_holder").hide();
                    break;
                case "3":
                    // daftar kar
                    $("#bath_holder").hide();
                    $("#lot_size_holder").hide();
                    break;
                case "4":
                    // vila
                    break;
                case "5":
                    // zamin
                    $("#bedroom_holder").hide();
                    $("#bath_holder").hide();
                    $("#home_size_holder").hide();
                    break;
                case "6":
                    // otaghe kar
                    $("#lot_size_holder").hide();
                    $("#bedroom_holder").hide();
                    $("#bath_holder").hide();
                    break;
                default:
                    // Type Is Not valid
                    alert("نوع ملک معتبر نمیباشد");
                    break;
            }


            // check for purpose
            switch ($("#melkpurposeid").val())
            {
                case "1":
                    // forosh
                    $("#sale_price_start_holder").show();
                    $("#sale_price_end_holder").show();

                    $("#rent_price_start_holder").hide();
                    $("#rent_price_end_holder").hide();

                    $("#rent_pricerahn_start_holder").hide();
                    $("#rent_pricerahn_end_holder").hide();
                    break;
                case "2":
                    // ejare
                    $("#sale_price_start_holder").hide();
                    $("#sale_price_end_holder").hide();

                    $("#rent_price_start_holder").show();
                    $("#rent_price_end_holder").show();

                    $("#rent_pricerahn_start_holder").show();
                    $("#rent_pricerahn_end_holder").show();
                    break;
                case "3":
                    // forosh va ejare
                    $("#sale_price_start_holder").show();
                    $("#sale_price_end_holder").show();

                    $("#rent_price_start_holder").show();
                    $("#rent_price_end_holder").show();

                    $("#rent_pricerahn_start_holder").show();
                    $("#rent_pricerahn_end_holder").show();
                    break;
                default:
                    // Type Is Not valid
                    alert("منظور ملک معتبر نمیباشد");
                    break;
            }
        }


        if (step == 3)
        {

        }



        if (step == 4)
        {

        }


        if (step == 5)
        {

        }


        if (step == 6)
        {

        }
    }

    /**
     * this function will validate step
     * @param {type} step
     * @returns {undefined}
     */
    function validStep(step) {

        // step one is choose type and purpose
        if (step == 2)
        {
            // Moshakasatee Melk
            switch ($("#melktypeid").val())
            {
                case "1":
                    // khane
                    if ($("#home_size").val() == "")
                    {
                        alert("مقدار سایز خانه را وارد نمایید");
                        return false;
                    }

                    if ($("#lot_size").val() == "")
                    {
                        alert("مقدار متراژ زمین را وارد نمایید");
                        return false;
                    }

                    break;
                case "2":
                    // aparteman
                    if ($("#home_size").val() == "")
                    {
                        alert("متراژ آپارتمان را وارد نمایید");
                        return false;
                    }

                    break;
                case "3":
                    // daftar kar
                    if ($("#home_size").val() == "")
                    {
                        alert("متراژ دفتر را وارد نمایید");
                        return false;
                    }
                    break;
                case "4":
                    // vila
                    if ($("#lot_size").val() == "")
                    {
                        alert("مقدار متراژ زمین را وارد نمایید");
                        return false;
                    }
                    break;
                case "5":
                    // zamin
                    if ($("#lot_size").val() == "")
                    {
                        alert("مقدار متراژ زمین را وارد نمایید");
                        return false;
                    }
                    break;
                case "6":
                    // otaghe kar
                    if ($("#home_size").val() == "")
                    {
                        alert("متراژ اتاق را وارد نمایید");
                        return false;
                    }
                    break;
                default:
                    // Type Is Not valid
                    alert("نوع ملک معتبر نمیباشد");
                    break;
            }



        }
        if (step == 3)
        {
            // Moghiyate  Melk
            if ($("#address").val() == "")
            {
                alert("خیابان اصلی را وارد نمایید");
                return false;
            }
            // Moghiyate  Melk
            if ($("#private_address").val() == "")
            {
                alert("آدرس دقیق ملک را وارد نمایید");
                return false;
            }
        }
        if (step == 4)
        {
            // Gheymat  Melk
            // check for purpose
            switch ($("#melkpurposeid").val())
            {
                case "1":
                    // forosh
                    if ($("#sale_price").val() == "")
                    {
                        alert("قیمت ملک را وارد نمایید");
                        return false;
                    }
                    break;
                case "2":
                    // ejare

                    if ($("#rent_pricerahn").val() == "")
                    {
                        alert("قیمت رهن را وارد نمایید");
                        return false;
                    }

                    if ($("#rent_price").val() == "")
                    {
                        alert("قیمت اجاره را وارد نمایید");
                        return false;
                    }

                    break;
                case "3":
                    // forosh va ejare
                    if ($("#sale_price").val() == "")
                    {
                        alert("قیمت ملک را وارد نمایید");
                        return false;
                    }

                    if ($("#rent_pricerahn").val() == "")
                    {
                        alert("قیمت رهن را وارد نمایید");
                        return false;
                    }

                    if ($("#rent_price").val() == "")
                    {
                        alert("قیمت اجاره را وارد نمایید");
                        return false;
                    }
                    break;
                default:
                    // Type Is Not valid
                    alert("منظور ملک معتبر نمیباشد");
                    break;
            }
        }

        if (step == 6)
        {
            // Etelate Tamas
            if ($("#private_phone").val() == "")
            {
                alert("تلفن تماس را وارد نمایید");
                return false;
            }

            if ($("#private_mobile").val() == "")
            {
                alert("شماره موبایل را وارد نمایید");
                return false;
            }
        }

        return true;
    }


    // add event on next button click
    $('body').on('click', '#nextbtn', function() {
        // get step
        var currenctStep = $(this).data('step');
        if (validStep(currenctStep))
        {
            readyStep(currenctStep + 1);
            showStep(currenctStep + 1, currenctStep);

        }

    });
    // add event on next button click
    $('body').on('click', '#backbtn', function() {
        // get step
        var currenctStep = $(this).data('step');
        showStep(currenctStep - 1, currenctStep);
    });
    // show step 1
    showStep(0, 0);</script>

<script>

    var citiesid = [];
    var cities = [];
<?php
foreach ($cities as $city) {
    echo "citiesid[$city->id] = \"$city->name\";\n";
    $ci = $city->getStateCitiesIDWithComma();
    echo "cities[$city->stateid] = \"$ci\";\n";
}
?>


    function onstatechange(selectedstate)
    {
        var ids = cities[selectedstate];
        var cityids = ids.split(",");
        // remove old cities
        var citylisteleemnt = $('#cityid');
        citylisteleemnt.find('option').remove().end();
        $.each(cityids, function(index, id) {
            if (index == 0)
            {
                oncitychange(citiesid[id]);
            }
            citylisteleemnt.append('<option value="' + id + '">' + citiesid[id] + '</option>');
        });
    }


    function oncitychange(city)
    {
        var state = $("#stateid").find("option:selected").text();
        var address = "ایران، " + city;

    }

    $("#stateid").change(function() {
        onstatechange(this.value);
    });

    $("#cityid").change(function() {
        var city = citiesid[$(this).val()];
        oncitychange(city);
    });


</script>

